### ISSUE TITLE
WatchOS apps not syncing with iPhone 

### ISSUE THREAD

**Issue by jclegg555** [checkra1n/BugTracker#207] opened 2019-11-11 20:27 UTC
**What device + iOS version are you on?**
iPhone X on iOS 13.2.2, Apple Watch Series 4 WatchOS 6.1

**What checkra1n version are you using?**
beta 0.9.1
**What are the steps to reproduce the issue?**
1. Have Apple Watch paired to iPhone
2. Jailbreak with checkra1n
3. Issues begin with iPhone communication with Watch.
...

**What do you expect, and what is happening instead?**
I expect the Watch to sync with my iPhone but apps are not syncing 

**Any other info, error logs, screenshots, ...?**
Things 3 on Apple Watch will not sync with iPhone even when manually synced. Additionally when my alarm goes off on my phone it is no longer going off on my watch as well

**Comment by nullpixel** [comment] 2019-11-11 20:46
Closed as a dupe of #75

**Closed as completed by nullpixel** 2019-11-11 20:46 UTC
Labels: status-duplicate
