### ISSUE TITLE
iPhone8p& iOS13.5.1@0.10.2@error-20

### ISSUE THREAD

**Issue by lantern9** [checkra1n/BugTracker#1477] opened 2020-06-14 15:57 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPhone8p
2. On what version of iOS is it?
13.5.1
3. What version of checkra1n are you using?
0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
15" MacBook Pro, Mid 2014 running Mojave 10.15.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple USB-A Cable, connected directly to the computer
**What are the steps to reproduce the issue?**
I did pretty much everything by the book (not my first time using checkra1n) and unfortunately I get stuck at the 'booting' phase with the following error:
"Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)"

**What do you expect, and what is happening instead?**
I want to “all down”

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment] 2020-06-21 06:54
Sounds like a dupe of #1449.

**Closed as completed by Siguza** 2020-06-21 06:54 UTC
Labels: status-duplicate
