### ISSUE TITLE
iphone 5S ios 12.4.4 cannot jailbroken

### ISSUE THREAD

**Issue by lapin9126** [checkra1n/BugTracker#834] opened 2020-02-07 07:30 UTC
Does anyone have experience jailbroken? (Linux)

**Comment by zurabi97** [comment] 2020-02-07 08:39
Stuck at "Right Before Trigger..."?

**Comment by lapin9126** [comment] 2020-02-07 09:15
Yes. https://yadi.sk/i/9hQYlUhuOv-N_w

**Comment by computersteve** [comment] 2020-02-07 16:12
same problem.. however for me it produces an error then continues and jailbreaks.

**Comment by sudo-ghost** [comment] 2020-02-08 06:48
yea it seems to be a device specific issue from what ive been reaading. it seems the 5s cant be jailbroken at the moment. i have an 8 and a 5s the 8 jailbroke perfectly fine but the 5s has the same issue. it seems the process just stalls at the right before trigger and the only way to stop the process is unplugging the phone and that results in a DFUSyncUpload FAILED: -1 error

**Comment by lapin9126** [comment] 2020-02-08 08:37
It’s a pity, maybe in the future, the problem will be solved.

**Comment by billabongbruno** [comment] 2020-02-08 21:24
Ok, I can help you with this, if you want to.
I posted a guide this morning on how to do it, but it got taken down for "piracy".
Funny, because there wasn't a single pirated mention, link or whatever in there.

Let me know if you need help with the workaround and we'll find some other way to communicate.

Best regards,
Bruno.

**Comment by zoomer555** [comment] 2020-02-09 10:42
> Ok, I can help you with this, if you want to.
> I posted a guide this morning on how to do it, but it got taken down for "piracy".
> Funny, because there wasn't a single pirated mention, link or whatever in there.
> 
> Let me know if you need help with the workaround and we'll find some other way to communicate.
> 
> Best regards,
> Bruno.


can you teach me the workaround? getting really desperate here.

**Comment by billabongbruno** [comment] 2020-02-09 10:54
@zoomer555 , were you able to JB with any version?

**Comment by zoomer555** [comment] 2020-02-09 11:06
no, all previous versions give me error -31 and -20

**Comment by billabongbruno** [comment] 2020-02-09 11:10
Ok. Is there any way we can talk outside of here, seeing that it's "piracy", for some reason (my posts apparently are piracy, but similar posts are not, so it's super weird).

**Comment by arazxa** [comment] 2020-02-10 22:59
Can i get help with same device and issue.

**Comment by kenoButler** [comment] 2020-02-26 02:47
version 0.9.2 worked

**Comment by AMDBartek** [comment] 2020-03-13 18:35
This is a known issue. #984

**Comment by Siguza** [comment] 2020-03-21 05:36
Marking this as duplicate of #984 (this issue is older, but the other one is more generic and thoroughly documented).

**Closed as completed by Siguza** 2020-03-21 05:36 UTC
Labels: status-duplicate
