### ISSUE TITLE
No sound. No Haptic Touch.

### ISSUE THREAD

**Issue by zireaelz97** [checkra1n/BugTracker#243] opened 2019-11-12 13:59 UTC
**What device + iOS version are you on?**
iPhone 8 Plus, iOS 13.2

**What checkra1n version are you using?**
beta 0.9.2
**What are the steps to reproduce the issue?**
1. Enter DFU mode
2. Jailbreak using app
3. Boot into a jailbroken state
...

**What do you expect, and what is happening instead?**
I expect for everything to work normally (or as normal as possible) instead basic functions don't work.

**Any other info, error logs, screenshots, ...?**
I've removed all tweaks and it's still happening so I don't think it's a bad tweak. It took a couple of tries to get it to jailbreak. At first it would just restart into a normal state after the macOS app said it was all done.

**Comment by littlelailo** [comment] 2019-11-12 15:11
Duplicate of #231

**Closed as completed by littlelailo** 2019-11-12 15:11 UTC
Labels: status-duplicate
