### ISSUE TITLE
[Feature Request] Custom Boot-Args & more

### ISSUE THREAD

**Issue by endercypher** [checkra1n/BugTracker#157] opened 2019-11-11 05:05 UTC
Well clearly I’m asking/requesting to have Custom Boot-Args & I mean like all of them. & then to disable stuff like KTRR & KPP. & then the last thing is adding the ability to have CheckRa1n Mount the file system as read/write. I know the default is read only etc since that’s what the amazing team here has decided to do but it would be nice to also have some sort of toggle or something on the CheckRa1n app to toggle it from read only to read/write vice versa.

**Comment by littlelailo** [comment] 2019-11-11 06:33
Duplicate of #110/#115 and #45

**Closed as completed by littlelailo** 2019-11-11 06:33 UTC
Labels: status-duplicate
