### ISSUE TITLE
not working for iPad Pro 12.9 a1652

### ISSUE THREAD

**Issue by NewHospitals** [checkra1n/BugTracker#2105] opened 2021-05-19 13:15 UTC
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1.  iPad Pro 12.9 a1652
2. 14.5.1
3. checkra1n 0.12.4 beta
... 

**What do you expect, and what is happening instead?**
MacBook Pro macOS Sierra 10.12.6

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
USB for iPhone/iPad

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes - Nothing changes

**Any other info, error logs, screenshots, ...?**
[https://ibb.co/vXLgwGK](url)
[https://ibb.co/vsy70MN](url)

**Comment by likkai** [comment] 2021-06-08 05:51
> Open Terminal, Drag the checkra1n app into the window (that should auto-paste its path), then append `/Contents/MacOS/checkra1n` and make sure there is no space between the part you dragged in and the one you appended.
> Then hit space, type `-k`, hit space again, then drag PongoConsolidated.bin into the window and hit enter.
> The GUI should pop up at that point.

Download, extract this file and replace the PongoConsolidated.bin above with the below one
https://github.com/checkra1n/BugTracker/issues/2074#issuecomment-832965843

**Comment by vasilis-ss** [comment] 2021-06-08 08:41
> > Open Terminal, Drag the checkra1n app into the window (that should auto-paste its path), then append `/Contents/MacOS/checkra1n` and make sure there is no space between the part you dragged in and the one you appended.
> > Then hit space, type `-k`, hit space again, then drag PongoConsolidated.bin into the window and hit enter.
> > The GUI should pop up at that point.
> 
> Download, extract this file and replace the PongoConsolidated.bin above with the below one
> [#2074 (comment)](https://github.com/checkra1n/BugTracker/issues/2074#issuecomment-832965843)

Thanks for the input but it's of no use to me, since I don't own a Mac, only a Windows PC...

**Comment by likkai** [comment] 2021-06-08 09:54
Use ubuntu live and download the CLI version of checkra1n. Type `sudo` then drag it into terminal and add the `-k Pongo.bin`
(Replace the Pongo.bin with the actual file name, I forgot what was the name)

**Comment by vasilis-ss** [comment] 2021-06-08 10:42
I really appreciate your help, but I can't make this work. I get command
not found message 😔

I'm not familiar with Mac OS or Ubuntu...

**Comment by Gigaah** [comment] 2021-06-20 17:19
I actually have the exact same issue.Also on 1st gen ipad Pro(9.7" tho) wifi
 As well, I also don't understand well enough how to execute the solution presented. I was just barely sharp enough..to get linux mint on a usb stick and boot it live and find the proper bits on the web to paste into the terminal to get checkra1n 0.12.4 to download and install.
Luckily however, I happen to be on iOS 14.4.2 and I was able to jail break sucessfully with checkra1n 0.12.2 as I had a suspicion there was some snafu yet with the latest checkra1n.

**Comment by vasilis-ss** [comment] 2021-06-21 07:08
Well, I'm on 14.5.1 and 0.12.2 won't do (tried)...

**Comment by Siguza** [comment] 2021-07-05 15:12
Duplicate of #2074.

**Closed as completed by Siguza** 2021-07-05 15:12 UTC
Labels: status-duplicate
