### ISSUE TITLE
ipad pro a1674 ios 14.6

### ISSUE THREAD

**Issue by samymenged** [checkra1n/BugTracker#2130] opened 2021-06-23 16:29 UTC
hi all i try to use checkra1n to jailbreal ipad pro 9.7 model a1674 

not done even i use mac  ,windows ,cli mode , i cant 

i try to add option like the screen shoot  but noth
![Immagine](https://user-images.githubusercontent.com/86361994/123133056-a7580300-d44f-11eb-911d-a06e5f776118.jpg)
![photo_2021-06-23_18-27-08](https://user-images.githubusercontent.com/86361994/123134354-fce0df80-d450-11eb-9fab-ed79d5b8a216.jpg)
ing [](url)

**Comment by osamex1069** [comment] 2021-06-25 16:29
I tried too on the same iPad model but without success on iOS 14.6 as same for iOS 14.7 beta

**Comment by matycrebo** [comment] 2021-06-26 07:39
same here

**Comment by Siguza** [comment] 2021-07-05 14:50
Duplicate of #2074.

**Closed as completed by Siguza** 2021-07-05 14:50 UTC
Labels: status-duplicate
