### ISSUE TITLE
Boot loop on iPad after trying 0.9.5 and then going back to 0.9.2 after realizing 0.9.5 won't boot

### ISSUE THREAD

**Issue by FM1337** [checkra1n/BugTracker#394] opened 2019-11-15 21:22 UTC
**What device + iOS version are you on?**
iPad 6th Gen iOS 13.2.2

**What checkra1n version are you using?**
0.9.2
**What are the steps to reproduce the issue?**
1. Attempt to boot checkra1n's latest beta (0.9.5)
2. Figure out that it still isn't working with the iPad
3. Downgrade to 0.9.2 and attempt to boot
...

**What do you expect, and what is happening instead?**
Excepted: It should go through the normal boot sequence and then boot up like normal
Reality: It gets to the Apple logo after the checkra1n logo and then stays on the Apple logo for a bit, and then goes black and then shows the Apple logo again.
**Any other info, error logs, screenshots, ...?**
N/A

**Comment by nullpixel** [comment] 2019-11-15 21:27
closed as a dupe of #393

**Closed as completed by nullpixel** 2019-11-15 21:27 UTC
Labels: status-duplicate

**Comment by FM1337** [comment] 2019-11-15 21:29
@nullpixel I believe this is a different issue, I know about #393 but I'm in a boot loop now after trying 0.9.5 when 0.9.2 worked fine before trying 0.9.5

**Comment by nullpixel** [comment] 2019-11-15 21:29
can you boot stock?

**Comment by FM1337** [comment] 2019-11-15 21:30
yes

**Comment by nullpixel** [comment] 2019-11-15 21:35
Okay so honestly - hopping between checkra1n versions like that is by no means supported, but it shouldn't break stuff :/

**Comment by FM1337** [comment] 2019-11-15 21:37
I'll run through a reset of the iPad to see if that fixes it

**Comment by nullpixel** [comment] 2019-11-15 21:38
👍 thanks :)

**Comment by FM1337** [comment] 2019-11-15 21:51
okay reset the iPad through stock mode, set it up quickly, all my tweaks and stuff came back after booting with 0.9.2 but cydia was complaining about something not being found, so i restored rootfs through the checkra1n app and then rebooted and rejailbroke and reinstalled cydia. It seems to be working now

**Comment by nullpixel** [comment] 2019-11-15 21:58
awesome!
