### ISSUE TITLE
always error 31 on iPad air with linux

### ISSUE THREAD

**Issue by PsxMicha** [checkra1n/BugTracker#2128] opened 2021-06-16 12:32 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPad Air (wifi only)
2. On what version of iOS is it?
12.5.3 (also tried 12.5.4)
3. What version of checkra1n are you using?
0.12.4
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Ubuntu Linux, also tried bootra1n and Checkn1x
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A Lighning Cable to USB 2.0 Port. Also tried 3.0

**What are the steps to reproduce the issue?**
1. sudo checkra1n
2. hit start on checkra1n
3. hold top and home button to get into DFU mode
4. when it says "right before bug trigger" it switches to error 31 after a while
...

**What do you expect, and what is happening instead?**

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

Hey guys!

My ipad was jailbreaked before, but my battery power went away and now I have to re jailbreak my ipad again. It used to work before flawlessly with checkra1n, but now I always get error 31 :( I tried different cables, computers, usb ports, ubuntu, bootra1n, everything! I always get error 31 :-\ How can I fix this?

**Comment by turtleb0x** [comment] 2021-06-22 02:46
I have the same exact issue.

**Comment by Siguza** [comment] 2021-07-05 14:56
Duplicate of #1169.

**Closed as completed by Siguza** 2021-07-05 14:56 UTC
Labels: status-duplicate
