### ISSUE TITLE
Freezes and Respring when trying to change Wallpaper 

### ISSUE THREAD

**Issue by rajdixon** [checkra1n/BugTracker#177] opened 2019-11-11 14:38 UTC
**What device + iOS version are you on?**
iPhone X - 13.2.2

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1. Go to Settings and to Wallpaper
2. When trying to select a new wallpaper, the phone freezes and resprings.
3.
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by littlelailo** [comment] 2019-11-11 15:18
Duplicate of #84

**Closed as completed by littlelailo** 2019-11-11 15:18 UTC
Labels: status-duplicate
