### ISSUE TITLE
iPadOS Smart Keyboard does not work when connected to charger.

### ISSUE THREAD

**Issue by Jalohann** [checkra1n/BugTracker#143] opened 2019-11-11 01:40 UTC
**What device + iOS version are you on?**
iPad Pro 10.5 Inch iOS 13.2.2

**What checkra1n version are you using?**
0.9 beta 1
**What are the steps to reproduce the issue?**
1. Connect iPad keyboard (iPad Unplugged)
2. Verify it works
3. Connect Charger
4. The keyboard no longer works.
...

**What do you expect, and what is happening instead?**
The keyboard should work when connected to a charger.

**Any other info, error logs, screenshots, ...?**
Smart Connector is clean, the issue does not occur in userland when checkra1n is disabled.

**Comment by nullpixel** [comment] 2019-11-11 07:55
Closed as a dupe of #48

**Closed as completed by nullpixel** 2019-11-11 07:55 UTC
Labels: status-duplicate
