### ISSUE TITLE
The internet connection appears to be offline

### ISSUE THREAD

**Issue by Xwdit** [checkra1n/BugTracker#10] opened 2019-11-10 13:49 UTC
'The internet connection appears to be offline',not able to install cydia,in wifi or in 3g

**Comment by marcos1** [comment] 2019-11-10 13:52
Duplicate it's likely that you have a Chinese iPhone

**Comment by nullpixel** [comment] 2019-11-10 13:52
Hi, do you have a Chinese iPhone?

**Comment by Xwdit** [comment] 2019-11-10 13:52
But i'm in france

**Comment by Xwdit** [comment] 2019-11-10 13:53
> Hi, do you have a Chinese iPhone?

Yes it's a chinese iphone but in in france....

**Comment by nullpixel** [comment] 2019-11-10 13:53
Hi, I've closed this issue as a duplicate of #3, because Chinese iPhones require additional steps for us to get WiFi working.

**Closed as completed by nullpixel** 2019-11-10 13:53 UTC
Labels: status-duplicate
