### ISSUE TITLE
SSH package installation to checkra1n device fails

### ISSUE THREAD

**Issue by anynon** [checkra1n/BugTracker#1925] opened 2020-12-30 16:02 UTC
**Tell us about your setup:** 
1. What iDevice are you using? iPhone 7/8 (Happens on two Devices)
2. On what version of iOS is it? 13.3.1/14.2
3. What version of checkra1n are you using? 0.12.1
4. What is your host system: OS X 10.15.7
5. How are you connecting to the device: USB-A

**What are the steps to reproduce the issue?**
1.  Try to install a package to a device running the checkra1n with OpenSSH installed via "make install"
2.  Install fails

**What do you expect, and what is happening instead?**
I expected the package to install to the device, but instead tar and dpkg throws an error.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
```
dm.pl: building package `com.opa334.ccsupport:iphoneos-arm' in `./packages/com.opa334.ccsupport_1.2.1-6+debug_iphoneos-arm.deb'
==> Installing…
tar: unrecognized option `--warning=no-timestamp'
Try `tar --help' or `tar --usage' for more information.
dpkg-deb: error: tar subprocess returned error exit status 64
dpkg: error processing archive /tmp/_theos_install.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /tmp/_theos_install.deb
make: *** [internal-install] Error 1'
```

This issue does not happen on Checkra1n 0.12.0, as after downgrading it no longer occurred

**Comment by Siguza** [comment] 2021-01-02 02:17
Seems like a duplicate of #1871.

**Closed as completed by Siguza** 2021-01-02 02:17 UTC
Labels: status-duplicate
