### ISSUE TITLE
error 31 

### ISSUE THREAD

**Issue by dnt0105** [checkra1n/BugTracker#34] opened 2019-11-10 14:34 UTC
![169110F0-416D-4A43-A229-41F861D87226](https://user-images.githubusercontent.com/57593643/68545858-67a2eb80-03d1-11ea-9196-50c51f303973.jpeg)
**What device + iOS version are you on?**
iphone 7 ios 13.1.3
iphone 6s ios 13.1.3

**What are the steps to reproduce the issue?**
1.run checkra
2.dfu on iphone
3.errot 31
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by zMyao** [comment] 2019-11-10 15:01
![1272048B-7F57-44FE-80C3-CDC5B0719839](https://user-images.githubusercontent.com/47767723/68546072-f897b800-040d-11ea-821b-44121476ed42.png)
Using iphone5s on 12.4.3 system

**Comment by nullpixel** [comment] 2019-11-10 15:34
Hi, what Mac is this on?

**Comment by dnt0105** [comment] 2019-11-10 15:48
i have the mac 10.14 on vmware

**Comment by g0dy666cz** [comment] 2019-11-10 15:48
Same here, running 10.15 in vmware , iphone 6S

**Comment by AidanDaniel97** [comment] 2019-11-10 15:53
Same issue here on Macbook Pro 2017, iPad Air (1st gen) on ios 12.4.3
I am using a usb hub but I am unsure why that would affect it?

**Comment by Baselk52** [comment] 2019-11-10 15:55
same here 
mac os 10.10 
iphone 7+ 13.1.1

**Comment by nullpixel** [comment] 2019-11-10 15:55
@g0dy666cz @dnt0105 VMware is not supported. It has to be ran on a supported Hackintosh or Mac.

@AidanDaniel97: we do a lot of magic with the USB stack so try running it with the USB cable directly connected to your Mac.

**Comment by nullpixel** [comment] 2019-11-10 15:56
Closed as a dupe of #9

**Closed as completed by nullpixel** 2019-11-10 15:55 UTC
Labels: status-duplicate
