### ISSUE TITLE
Webpages will not load

### ISSUE THREAD

**Issue by TheChaseJ** [checkra1n/BugTracker#1695] opened 2020-09-23 15:59 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPad Air 2
2. On what version of iOS is it?
14.0
3. What version of checkra1n are you using?
0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacOS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A

**What are the steps to reproduce the issue?**
1. Open Safari or Chrome
2. Webpages don’t load
3.
...

**What do you expect, and what is happening instead?**
Webpages to load

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
No

**Any other info, error logs, screenshots, ...?**

**Comment by noob698** [comment] 2020-09-23 16:44
Try using VPN

**Comment by TheChaseJ** [comment] 2020-09-23 20:00
VPN will not load. Actually, No network connectivity in any app except Cydia.

Edit: Does not happen with Safe Mode ticked. But, I have no network related tweaks installed.

**Comment by Siguza** [comment] 2020-09-23 23:10
Can't reproduce, and the fact that it works in Safe Mode basically confirms that it's a tweak.  
Doesn't have to be network related, as long as it loads into a process and crashes or hangs it, or makes it go out of memory, it can cause issues.  
Marking this as not caused to checkra1n.

**Closed as completed by Siguza** 2020-09-23 23:10 UTC
Labels: status-invalid
