### ISSUE TITLE
Ipad pro 1st gen ios 14.6 detected corrupted kerninfo

### ISSUE THREAD

**Issue by mashtyme** [checkra1n/BugTracker#2118] opened 2021-06-03 08:26 UTC
**Tell us about your setup:**
1. What iDevice are you using?
Ipad pro 1st gen model J98aAP
2. On what version of iOS is it?
tried both 14.3 and 14.6
3. What version of checkra1n are you using?
0.12.4
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Lubuntu Eoan Ermine 19.10
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Original Apple Lightning to USB A

**What are the steps to reproduce the issue?**
1. attempt to jailbreak
2. ipad booting up, checkra1n logo showing
3. lines on ipad states: Found old-style rdsk! Detected corrupted kern_info! Enabling USB done! pongoOS
4. reboot to iOS without checkra1n
...

**What do you expect, and what is happening instead?**
jailbreak should complete

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
no, tried to start checkra1n in CLI mode with ipad in DFU, same results

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes, I even tried updating ios in attempt to rewrite corrupted files but nothing changed

**Any other info, error logs, screenshots, ...?**
after forcingly rebooting ipad error -79 appears. it seems this kind of error was there since ver. 0.12.3 for ipad pro 1st gen. Please patch it asap

**Comment by DorianRudolph** [comment] 2021-06-04 00:44
I have the same error on my iPad Pro 9.7 on 14.4 with 0.12.3 and 0.12.4. But 0.12.2 works for me.

**Comment by mashtyme** [comment] 2021-06-04 08:33
thank you very much for your feedback, today i'll try with the older version. My fear is it could be my Ipad's fault of being permanently damaged and I don't know what the cause is.

**Comment by chlny** [comment] 2021-06-10 04:39
I'm also getting the issue - ipad pro 1st gen 12.9in.  UI sticks on "booting" and ipad doesn't progress past the pongos> prompt.

Using odysseyn1x with 0.12.4

**Comment by iywdde** [comment] 2021-06-10 13:17
I got the same :/

**Comment by mashtyme** [comment] 2021-06-10 13:41
Update: i tried with 0.12.2 and failed anyway. I noticed that on 0.12.4 it gives a USBMUX (-79) error when rebooting. Hope they fix it on 0.12.5, for now I'm using appdb for a couple of apps I need

**Comment by Crantox-c** [comment] 2021-06-13 05:02
I have same issue iPad Pro 9.7 iOS 14.5.1

**Comment by mashtyme** [comment] 2021-06-15 09:29
If someone has MacOS/Linux and wants to try a workaround to this problem I leave you this link: https://www.reddit.com/r/jailbreak/comments/nds387/tutorial_checkra1n_workaround_using_pongoos_if/

I got no luck as my Linux f*cked up python repos so I can't tell if it works

**Comment by sajidmirza6** [comment] 2021-06-17 11:02
iPad Pro 12.9 A1652  14.6 shows me same problem with error -20 and does not boot
I hope the new update will fix this issue.

**Comment by Crantox-c** [comment] 2021-06-17 11:26
> iPad Pro 12.9 A1652 14.6 shows me same problem with error -20 and does not boot
> I hope the new update will fix this issue.

I found a fix thanks to @mBoN_LU on Telegram (this is not some kind of bot comments) he told me to click the link( https://mega.nz/folder/QoxUxa7b#sNOtgvLp965P2O4sPew8UQ ) and to download the pongo os a9x folder in the link. After that i followed the instruction.txt. (If you're on Ubuntu you don't need to do the xattr command, and in the drag checkra1n from package content step on ubuntu you have to to your system disk and go to bin scroll untill you find checkra1n and drag and drop it in terminal as told everything other just follow txt file) .

**Comment by Gf191** [comment] 2021-06-20 20:55
> > iPad Pro 12.9 A1652 14.6 shows me same problem with error -20 and does not boot
> > I hope the new update will fix this issue.
> 
> I found a fix thanks to @mBoN_LU on Telegram (this is not some kind of bot comments) he told me to click the link( https://mega.nz/folder/QoxUxa7b#sNOtgvLp965P2O4sPew8UQ ) and to download the pongo os a9x folder in the link. After that i followed the instruction.txt. (If you're on Ubuntu you don't need to do the xattr command, and in the drag checkra1n from package content step on ubuntu you have to to your system disk and go to bin scroll untill you find checkra1n and drag and drop it in terminal as told everything other just follow txt file) .

It worked for me, Thanks so much

**Comment by 1024kbdotcodotnz** [comment] 2021-06-22 00:33
I solved this on an A1584, 1st gen iPad Pro 12.9” by using checkra1n 12.2 from terminal & parsing -s (safe mode) before -c (CLI). It didn’t work with -c -s but did with -s -c.  OS platform is High Sierra.

**Comment by Siguza** [comment] 2021-07-05 15:03
Duplicate of #2074.

**Closed as completed by Siguza** 2021-07-05 15:03 UTC
Labels: status-duplicate

**Comment by NgDTien** [comment] 2022-09-05 15:09
I found out that using checkra1n with an AMD device usually cause error 79 and 20. I tried jailbreaking my Ipad Air 2 on 14.5.1 using an Intel laptop and it worked on the 1st run. Can anyone confirm if checkra1n does not work on AMD pc?

**Comment by apple22251** [comment] 2023-07-25 23:10
Ok update it is fixed: first this is only for the ipads that i have.  First you need to have a terminal, (a mac) u will then extract these files https://mega.nz/folder/BgwECQoI#DSVtkajECztFk4YzJXpgkA and follow the guide. or follow my guide :). u want to make sure u extract the files if u dont it will not work. ( I leanred hard way) then open up terminal and copy and paste this: xattr -cr ..........( not the dots) once u have that then drag in the extracted file and plug it with it (make sure there is a space between) press enter. Once that is in then you are going to go to the app checkra1n on your desktop then click on show package contents then mac0s folder drag and drop checkra1n to the terminal.  then type -k then drag and drop the extracted .bin (the same file u put in before) press enter. Boom u are in enjoy 🙂
