### ISSUE TITLE
iPad Mini Problem

### ISSUE THREAD

**Issue by xavomar** [checkra1n/BugTracker#901] opened 2020-02-15 03:52 UTC
**Tell us about your setup:**
1.iPad Mini
2.14.4.4
3. last one 0.9.8
4. Capitan
5. usb on Macbook

**What are the steps to reproduce the issue?**
1. connect to computer 
2. Open and executed Checkra1n
3.just crash and shows "Error Report - Request for Permission..." on every iPad Mini i try to jailbreak

**What do you expect, and what is happening instead?**

just work
**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment] 2020-02-26 00:02
There is no iOS 14.4.4...

**Comment by xavomar** [comment] 2020-02-26 00:42
iOS 13.4 mean

**Comment by Siguza** [comment] 2020-02-26 00:43
Well that's not supported yet. Marking as duplicate of #877 then.

**Closed as completed by Siguza** 2020-02-26 00:43 UTC
Labels: status-duplicate

**Comment by xavomar** [comment] 2020-02-26 00:45
Have to double check,  I'm on a trip and don't have it on me to verify the
ios
