### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by xpuska513** [checkra1n/BugTracker#199] opened 2019-11-11 19:04 UTC
Since windows is not supported due to the drivers is not giving much control for you then maybe Linux drivers(if available) can give you this control?
So in a few words, will this jailbreak support Linux distros?

**Comment by viggou** [comment] 2019-11-11 20:17
yes it will and they already said that

**Comment by nullpixel** [comment] 2019-11-11 23:14
Closed as a dupe of #1

**Closed as completed by nullpixel** 2019-11-11 23:14 UTC
Labels: status-duplicate
