### ISSUE TITLE
Cannot use mobile data after checkra1n.

### ISSUE THREAD

**Issue by vismittu** [checkra1n/BugTracker#247] opened 2019-11-12 14:59 UTC
**What device + iOS version are you on?**
iPhone X iOS 13.1.3

**What checkra1n version are you using?**
0.9.2
**What are the steps to reproduce the issue?**
1.Install checkra1n
2.Try using mobile data.
3.
...

**What do you expect, and what is happening instead?**
The mobile data to work.

**Any other info, error logs, screenshots, ...?**

**Comment by littlelailo** [comment] 2019-11-12 15:07
Duplicate of #38

**Closed as completed by littlelailo** 2019-11-12 15:07 UTC
Labels: status-duplicate
