### ISSUE TITLE
Linux version of Checkra1n ( CLI/GUI ) on older devices not working.

### ISSUE THREAD

**Issue by ilhamisayev** [checkra1n/BugTracker#1611] opened 2020-08-10 21:57 UTC
**Tell us about your setup:**
1. What iDevice are you using? iphone 5s ( Global ) 
2. On what version of iOS is it? iOS 12.4.8
3. What version of checkra1n are you using? 10.2 but actually tried every linux version
4. What is your host system (OS version? Hackintosh? VM? etc.)? Kali Linux /Ubuntu
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Apple Original Usb Cable USB 2.0

**What are the steps to reproduce the issue?**
1. Get An IPhone 5s
2. Connect to PC lol
3. Run Checkra1n
...

**What do you expect, and what is happening instead?**
it get stuck on right before trigger.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
BootRa1n 9.8 is only working method ( unplug & plug method ) but sometimes it dont/cant prompt iphone to boot or something like that. And thank you for your hard work appreciate y'all

**Comment by Siguza** [comment] 2020-08-10 22:15
Dupe of #1169.

**Closed as completed by Siguza** 2020-08-10 22:15 UTC
Labels: status-duplicate
