### ISSUE TITLE
iPad Air 1st Gen (Cellular) iOs 12.4.7 [ERROR]

### ISSUE THREAD

**Issue by moiifernandz** [checkra1n/BugTracker#1511] opened 2020-06-22 16:09 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPad Air 1st Gen (Cellular)
2. On what version of iOS is it?
iOS 12.4.7
3. What version of checkra1n are you using?
0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
I did try it in Ubuntu 18.04 and now in Ubuntu 20.04
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A included in the iPad and iPhone box

**What are the steps to reproduce the issue?**
1. I connect the iPad Air to the checkra1n app
2. I Start the process, recovery mode, DFU...
3. And the iPad freezes in the step ''Right before trigger (this is the real bug setup)''
...

**What do you expect, and what is happening instead?**
I hope see the verbose boot, but it won't boot instead

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
The error occurs both if I run the application in the terminal using the sudo command or  not and if I run it in the applications menu

**Comment by demhademha** [comment] 2020-06-22 16:21
Quickly unplug / rep lug your charger

**Comment by moiifernandz** [comment] 2020-06-22 17:50
@demhademha  I already did it, the verbose boot was seen but the jailbreak was not achieved :/

**Comment by moiifernandz** [comment] 2020-06-22 17:52
In checkra1n 0.9.8 the jailbreak on my ipad works, but in this version doesn't work

**Comment by Siguza** [comment] 2020-06-23 03:19
Duplicate of #1169.

**Closed as completed by Siguza** 2020-06-23 03:19 UTC
Labels: status-duplicate
