### ISSUE TITLE
5S 12.4.3 stuck at booting with 0.9.6 GUI

### ISSUE THREAD

**Issue by dypxy** [checkra1n/BugTracker#574] opened 2019-12-03 06:14 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 5s
2. On what version of iOS is it?
12.4.3
3. What version of checkra1n are you using? GUI or CLI?
0.9.6 GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Hackintosh mojave 10.14.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A 2.0
**What are the steps to reproduce the issue?**
1. Jailbreak with steps as per requested in Checkra1n GUI
2. 
3.
...

**What do you expect, and what is happening instead?**
Successful jailbreak, but it's just somehow stuck at 'booting now' process and then followed by error bootstrap something with possibly caused by tweaks in GUI. The problem is I just restored rootfs from checkra1n 0.9, so should be no tweaks installed.

But, jailbreak runs normal with CLI (did this after 3 times failed with GUI)

**Does the issue also occur if you enable Safe Mode?**
No, but I can't open cydia because it's not installed yet

**Any other info, error logs, screenshots, ...?**
![IMG_1513](https://user-images.githubusercontent.com/58458237/70025074-3ebee200-159c-11ea-90ca-8b8501ba3ebc.JPG)

**Comment by Siguza** [comment] 2019-12-03 20:16
This sounds like a duplicate of #560.

**Closed as completed by Siguza** 2019-12-03 20:16 UTC
Labels: status-duplicate
