### ISSUE TITLE
checkra1n GUI is not HiDPI aware (GUI clips into fixed window dimensions)

### ISSUE THREAD

**Issue by intelfx** [checkra1n/BugTracker#1339] opened 2020-05-12 06:15 UTC
**Tell us about your setup:**

> 1. What iDevice are you using?

irrelevant

> 2. On what version of iOS is it?

irrelevant

> 3. What version of checkra1n are you using?

0.10.1

> 4. What is your host system (OS version? Hackintosh? VM? etc.)?

Arch Linux / GNOME 3 / Wayland

> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

irrelevant

**What are the steps to reproduce the issue?**

I use a GNOME 3 session in Wayland, however I suppose other HiDPI setups will lead to this bug as well.

1. Get a HiDPI setup (for GNOME 3: configure monitor scaling to >100%)
2. Install checkra1n GUI build from a *.deb
2. Launch checkra1n GUI (`checkra1n --gui`)

**What do you expect, and what is happening instead?**

**Observed** clipping in GUI, i. e. window size is probably hardcoded for 96 DPI, while the GUI itself scales up appropriately and gets hidden "behind" the window boundary (see screenshot below). The window itself cannot be resized.

**Expected** no clipping to occur.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

irrelevant

**Any other info, error logs, screenshots, ...?**

![Снимок экрана от 2020-05-12 09-12-01](https://user-images.githubusercontent.com/1158172/81644696-eb956900-9430-11ea-8957-e8290770bc88.png)

**Comment by nergzd723** [comment] 2020-05-15 10:29
See #1193, and AFAIK it's wayland-only issue.

edit: and it does the same thing without any scaling too.

**Comment by Siguza** [comment] 2020-05-16 05:23
Marking as duplicate of #1193.

**Closed as completed by Siguza** 2020-05-16 05:23 UTC
Labels: status-duplicate
