### ISSUE TITLE
Random reboot once a day or two

### ISSUE THREAD

**Issue by youngslim** [checkra1n/BugTracker#652] opened 2019-12-18 15:10 UTC
**Tell us about your setup:**
1. What iDevice are you using?  **iPhone X**
2. On what version of iOS is it?  **12.3(17C54)**
3. What version of checkra1n are you using? GUI or CLI?  **GUI**
4. What is your host system (OS version? Hackintosh? VM? etc.)? **Sierra macos**
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? **USB-A**

**What are the steps to reproduce the issue?**
1. Some times you touch the screen and ready to unlock, it respring for a very long time and finally reboot
2. Some times it just suddenly respring for a very long time and finally reboot
3.A lot jetsamevent and 2 stocks+backboardd in log
...

**What do you expect, and what is happening instead?**
Help find out what makes it reboot

**Does the issue also occur if you enable Safe Mode?**
Didn't try it 

**Any other info, error logs, screenshots, ...?**
logs 

[panic-full-2019-12-18-212604.477.txt](https://github.com/checkra1n/BugTracker/files/3979028/panic-full-2019-12-18-212604.477.txt)
[stacks+backboardd-2019-12-18-212333.txt](https://github.com/checkra1n/BugTracker/files/3979029/stacks%2Bbackboardd-2019-12-18-212333.txt)
[stacks+backboardd-2019-12-18-212433.txt](https://github.com/checkra1n/BugTracker/files/3979030/stacks%2Bbackboardd-2019-12-18-212433.txt)

**Comment by Siguza** [comment] 2019-12-18 20:23
Looks like a duplicate of #533.

**Closed as completed by Siguza** 2019-12-18 20:23 UTC
Labels: status-duplicate
