### ISSUE TITLE
iPhone X Global

### ISSUE THREAD

**Issue by spiouki** [checkra1n/BugTracker#1849] opened 2020-11-16 11:06 UTC
**Tell us about your setup:**
1. What iDevice are you using?iPhone X 
2. On what version of iOS is it?iOs 14.2
3. What version of checkra1n are you using?12.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?Hackintosh
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple provided cable
**What are the steps to reproduce the issue?**
1. iPhone X global is not supported even-though website says iphone X ios14.2 is  
2. 
3.
...

**What do you expect, and what is happening instead?**
I expect a more detailed list of devices that are supported on your website so that I dont
Loose my jb again.
**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment] 2020-11-17 23:26
Duplicate of #1823.

**Closed as completed by Siguza** 2020-11-17 23:26 UTC
Labels: status-duplicate
