### ISSUE TITLE
Jailbrake process freezes at 80% 

### ISSUE THREAD

**Issue by vasilis-ss** [checkra1n/BugTracker#2125] opened 2021-06-08 06:56 UTC
**Tell us about your setup:**
1. What iDevice are you using? iPad Pro 9.7" Gen 1
2. On what version of iOS is it? 14.6
3. What version of checkra1n are you using? 1.1.7
4. What is your host system (OS version? Hackintosh? VM? etc.)? windows pc
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? new iPad original caple

**What are the steps to reproduce the issue?**
1. Boot checkra1n with bootable USB
2. Check "Allow untested OS versions"
3. Start 
...

**What do you expect, and what is happening instead?**
I expect Boot to complete after jailbrake, it freezes at 80% with the following message on device screen:

Found old-style rdsk!
Detected corrupted kerninfo!
Enabling USB
Done!
pongoOS>

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?** no

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?** Yes

**Any other info, error logs, screenshots, ...?**

![20210606_215806](https://user-images.githubusercontent.com/85545176/121137437-4f11e600-c83f-11eb-9ea3-596f14270523.jpg)
![20210608_093140](https://user-images.githubusercontent.com/85545176/121137486-5a651180-c83f-11eb-9ed1-95265a8cacbd.jpg)

**Comment by likkai** [comment] 2021-06-08 08:30
https://github.com/checkra1n/BugTracker/issues/2105#issuecomment-856465352

**Comment by Siguza** [comment] 2021-07-05 14:58
Duplicate of #2074.

**Closed as completed by Siguza** 2021-07-05 14:58 UTC
Labels: status-duplicate
