### ISSUE TITLE
Error -30

### ISSUE THREAD

**Issue by danylonovosad** [checkra1n/BugTracker#1196] opened 2020-04-11 18:46 UTC
IPhone 5s
IOS 12.4.6 (16G183)
checkra1n v.0.10.1 beta

**Comment by nergzd723** [comment] 2020-04-11 19:42
Bad bug report BTW, but see #1169

**Comment by Siguza** [comment] 2020-04-12 03:09
Closing this due to lack of information.  
If this affects macOS, please open a new ticket and fill out the template.  
If this affects Linux, consider it a duplicate of #1169.

**Closed as completed by Siguza** 2020-04-12 03:09 UTC
Labels: status-invalid
