### ISSUE TITLE
iPados 13.2.2

### ISSUE THREAD

**Issue by tariq-192** [checkra1n/BugTracker#72] opened 2019-11-10 16:54 UTC
**What device + iOS version are you on?**iPados13.2.2

**What are the steps to reproduce the issue?**1
1.
2.
3.
...

**What do you expect, and what is happening instead?** when i open checkra1n loader clicking cydia crash app

**Any other info, error logs, screenshots, ...?**

**Comment by robsee** [comment] 2019-11-10 16:59
See Issue #2 for the workaround

**Comment by nullpixel** [comment] 2019-11-10 17:05
Closing as a dupe of #2.

**Closed as completed by nullpixel** 2019-11-10 17:05 UTC
Labels: status-duplicate
