### ISSUE TITLE
can't show notification to AppleWatch & error 

### ISSUE THREAD

**Issue by wilwillyy** [checkra1n/BugTracker#139] opened 2019-11-10 23:35 UTC
hello, im using 6S 13.2 and checkra1n version is 0.9.1
im using watch version 6.1.1.

After jailbreak, the application watch on phone cannot show the menu.
and notification not showing on watch.

i hope this bug will fix soon.
thx

https://imgur.com/IXhWqLM

**Comment by nullpixel** [comment] 2019-11-10 23:38
Hi, thanks for the bug report. It’s already been reported as #75 so I’m going to close this one as a duplicate of that.

**Closed as completed by nullpixel** 2019-11-10 23:38 UTC
Labels: status-duplicate
