### ISSUE TITLE
iPhone 6s Cydia Crash on boot Issue

### ISSUE THREAD

**Issue by antontech393** [checkra1n/BugTracker#565] opened 2019-12-02 00:04 UTC
I'm on iOS 13.2.3 on an iPhone 6s with checkra1n beta 0.9.6, when i try to jailbreak and install the checkra1n app, it is successful. But when i try to install the cydia package manager, it opens for a split second and then crashes.

**Comment by Siguza** [comment] 2019-12-02 00:40
Any chance you could attach a crash log?

**Comment by antontech393** [comment] 2019-12-02 00:42
no because no info was stored on the phone

**Comment by iuseaios13on6s** [comment] 2019-12-02 23:15
same issues anyone knows if this is being worked on

**Comment by Siguza** [comment] 2020-02-07 00:32
Assuming this is a duplicate of #60.

**Closed as completed by Siguza** 2020-02-07 00:32 UTC
Labels: status-duplicate
