### ISSUE TITLE
iPad 6ta error -20 bad tweak

### ISSUE THREAD

**Issue by maurediaz96** [checkra1n/BugTracker#425] opened 2019-11-17 04:00 UTC
I had the jailbreak and installed a damaged tweak I had to proceed to reactivate the jailbreak again I get an error -20 from there restore with iTunes to jailbreak again from scratch and keep giving error -20 and check the option safely and even So it gives error -20 what can I do I have iPad 6th generation. Thanks in advance

**Comment by DanyL** [comment] 2019-11-17 08:25
Duplicate of #393

**Closed as completed by DanyL** 2019-11-17 08:25 UTC
Labels: status-duplicate
