### ISSUE TITLE
iPad stuck on booting

### ISSUE THREAD

**Issue by Noodleyp** [checkra1n/BugTracker#1220] opened 2020-04-14 22:34 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPad Air 2
2. On what version of iOS is it?
iOS 13.4.1
3. What version of checkra1n are you using?
0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
macOS 10.12.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A
**What are the steps to reproduce the issue?**
1. Plug in iPad
2. Click Jailbreak
3.follow instructions
...

**What do you expect, and what is happening instead?**
I expect it to jailbreak, but it gets stuck on booting

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
No

**Comment by Siguza** [comment] 2020-04-14 23:58
Duplicate of #1168.

**Closed as completed by Siguza** 2020-04-14 23:58 UTC
Labels: status-duplicate
