### ISSUE TITLE
Installer crashes when trying to install cydia

### ISSUE THREAD

**Issue by wbraffman** [checkra1n/BugTracker#7] opened 2019-11-10 13:44 UTC
**iPad7 + 13.1?**

**What are the steps to reproduce the issue?**
1. Jailbreak the device
2. Open app on device
3. click cydia
...

**What do you expect, and what is happening instead?**
To install cydia, but instead it just crashes

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment] 2019-11-10 13:49
Hi, I've closed this issue as a duplicate of #2.

**Closed as completed by nullpixel** 2019-11-10 13:49 UTC
Labels: status-duplicate
