### ISSUE TITLE
Checkra1n v0.11.0 doesn't support iPad Pro 1st gen (A9X)

### ISSUE THREAD

**Issue by EliasSfeir** [checkra1n/BugTracker#1710] opened 2020-09-27 20:37 UTC
1. What iDevice are you using?

iPad Pro 9.7 inch 1st gen (A9X)

2. On what version of iOS is it?

iOS 14.0

3. What version of checkra1n are you using?

0.11.0

4. What is your host system (OS version? Hackintosh? VM? etc.)?

MacOS 10.15.7 (MacBook Pro 2016 15inch)

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

USB-A to a type C converter (cable is fine, used to work on iOS 13 and works on my iPod Touch iOS 12).

**What are the steps to reproduce the issue?**

1.  Jailbreak with checkra1n
2. The device boots fine but stock, no checkra1n loader app.
3. Seems that it panics halfway.
4. Tried booting with all options and it doesn't work.

**What do you expect, and what is happening instead?**

I am expecting to boot jailbroken with loader app to install Cydia but instead it seems to boot stock.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

Yes.

**Any other info, error logs, screenshots, ...?**

I get error -20 from checkra1n app.

**Comment by Siguza** [comment] 2020-09-27 20:50
Duplicate of #1692.

**Closed as completed by Siguza** 2020-09-27 20:50 UTC
Labels: status-duplicate
