### ISSUE TITLE
Checkra1n doesn't work when trying to jailbreak m1 macbook

### ISSUE THREAD

**Issue by pwninitd** [checkra1n/BugTracker#2035] opened 2021-03-17 17:41 UTC
**Tell us about your setup:**
1. Trying to jailbreak macbook air m1 
2. Big Sur
3. 0.12.2
4. Macbook pro 2017
5. USB-C to USB-C

**What are the steps to reproduce the issue?**
1. Just try jailbreaking a macbook air m1.....
...

**What do you expect, and what is happening instead?**
I expected to be able to jailbreak it but i doesn't seem to work.

**Comment by worf1337** [comment] 2021-03-18 23:06
Known issue.

**Comment by Siguza** [comment] 2021-03-25 08:10
Duplicate of #1862.

The frustrating thing is that this is caused by two issues, one of which we fixed months ago, but the other one is tied to a weirdness in the USB stack that requires big refactoring on our end. Rest assured we're working on it though. :/

**Closed as completed by Siguza** 2021-03-25 08:10 UTC
Labels: status-duplicate
