### ISSUE TITLE
Not letting me install cydia 

### ISSUE THREAD

**Issue by razza-rock** [checkra1n/BugTracker#40] opened 2019-11-10 15:00 UTC
**What device + iOS version are you on?**
I Pad 6 GEN 

**What are the steps to reproduce the issue?**
1.
2.
3.
...

**What do you expect, and what is happening instead?**
i would like someone to help and give me a bit of advice 

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment] 2019-11-10 15:01
Hi, I've closed this issue as a duplicate of #2.

**Closed as completed by nullpixel** 2019-11-10 15:01 UTC
Labels: status-duplicate
