### ISSUE TITLE
iPad Air 2 (13.4.1)

### ISSUE THREAD

**Issue by ZSSK1** [checkra1n/BugTracker#1318] opened 2020-05-06 09:49 UTC
**Tell us about your setup:**
1. iPad Air 2
2. iOS 13.4.1
3. Checkra1n 0.10.1
4. Linux ubuntu,checn1x,bootra1n
5. USB-A

**What are the steps to reproduce the issue?**
1. at the jailbreak loading stage

**What do you expect, and what is happening instead?**
Jailbreak, but instead, it hangs on reading the kernel

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
![B25E6732-B435-4890-BB6F-312694C61B0D](https://user-images.githubusercontent.com/45142881/81163417-8664f200-8fb0-11ea-8a90-08dc0d159ec8.jpeg)
![954C9BFC-D25B-470D-A830-896570C48F3B](https://user-images.githubusercontent.com/45142881/81163440-8ebd2d00-8fb0-11ea-8155-d81185c43127.jpeg)

![image](https://user-images.githubusercontent.com/45142881/81163765-10ad5600-8fb1-11ea-957d-7e98207d8abf.jpg)

**Comment by Joshfindit** [comment] 2020-05-06 15:15
Duplicate of https://github.com/checkra1n/BugTracker/issues/1168

**Comment by Siguza** [comment] 2020-05-06 23:40
^

**Closed as completed by Siguza** 2020-05-06 23:40 UTC
Labels: status-duplicate
