### ISSUE TITLE
Phone not entering DFU mode after multiple attempts - iPhone SE first gen

### ISSUE THREAD

**Issue by domainxh** [checkra1n/BugTracker#1844] opened 2020-11-14 00:43 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPhone SE 1st Gen

2. On what version of iOS is it?
14.1

3. What version of checkra1n are you using?
Beta 0.12.0

4. What is your host system (OS version? Hackintosh? VM? etc.)?
Mac OS 11.0.1

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple's USB-C to lighting

**What are the steps to reproduce the issue?**
Following step by step tutorial from the Checkra1n application. 

**What do you expect, and what is happening instead?**
iPhone to enter DFU mode, but after 30 or so attempts, it keeps failing with the error message "Whoops, the device didn't enter DFU mode. Click Retry to try again."

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
NA

**Any other info, error logs, screenshots, ...?**
NA

**Comment by asdfugil** [comment] 2020-11-14 10:28
Apple USB-C to lighting doesn't work.
Duplicate of #1

**Closed as completed** 2020-11-14 15:22 UTC
