### ISSUE TITLE
Cydia Crashes When Opened

### ISSUE THREAD

**Issue by GuyInHiding** [checkra1n/BugTracker#262] opened 2019-11-12 22:25 UTC
**What device + iOS version are you on?**
iPhone SE 13.2.2

**What checkra1n version are you using?**
0.9.2
**What are the steps to reproduce the issue?**
1.Jailbreak
2.Install Cydia through checkra1n app
3.Attempt to open Cydia
...

**What do you expect, and what is happening instead?**
I expect Cydia to open and when I open it I get a white screen and then it crashes

**Any other info, error logs, screenshots, ...?**
I have looked at issue #60 and tried everything people recommended and when I ssh into my phone and cd to `var/mobile/library/cydia/` I get an error saying `-bash: var/mobile/library/cydia/: No such file or directory`

**Comment by GuyInHiding** [comment] 2019-11-12 23:18
Update: Cydia has disappeared and when I try to install it through checkra1n I can only click on cancel and not install
![IMG_0660](https://user-images.githubusercontent.com/42387188/68718961-c48cd600-0578-11ea-855a-15116a76030d.PNG)
Edit: Restored system and installed Cydia, but it still crashes when opened

**Comment by martin341** [comment] 2019-11-12 23:30
I have the same problem on an iphone 8 plus on ios 13.2.2

**Comment by Shadowedstalker** [comment] 2019-11-12 23:43
Cydia crashing and won't open..

ssh into your phone go to var/mobile/Library/Cydia and delete metadata.cb0 . Cydia will open. reinstall tweaks.

**Comment by GuyInHiding** [comment] 2019-11-12 23:44
> Cydia crashing and won't open..
> 
> ssh into your phone go to var/mobile/Library/Cydia and delete metadata.cb0 . Cydia will open. reinstall tweaks.

That does not work
I stated in the original post that terminal says that directory does not exist
![image](https://user-images.githubusercontent.com/42387188/68720184-78dc2b80-057c-11ea-8bd9-bfa29bc7012b.png)

**Comment by Shadowedstalker** [comment] 2019-11-12 23:46
Instead of do the whole directory go one by one

cd var/
cd mobile/
cd library/
cd cydia.

during each you can ls to view all in the directory.

**Comment by GuyInHiding** [comment] 2019-11-12 23:47
The only directories I have are Library and Media
![image](https://user-images.githubusercontent.com/42387188/68720312-d1abc400-057c-11ea-89fe-1125a0ef1ad5.png)

**Comment by Shadowedstalker** [comment] 2019-11-12 23:48
OK, here's your problem.

type CD /
now you will be at root and LS you will see the directories.

**Comment by Shadowedstalker** [comment] 2019-11-12 23:48
ls

**Comment by GuyInHiding** [comment] 2019-11-12 23:55
How do I delete the file?

**Comment by GuyInHiding** [comment] 2019-11-12 23:57
I got it working! Thank you!!

**Comment by Shadowedstalker** [comment] 2019-11-12 23:58
rm metadata.cb0

**Comment by Shadowedstalker** [comment] 2019-11-12 23:58
Cydia opening again?

**Comment by martin341** [comment] 2019-11-13 00:05
I’ll try this later because I’m facing the same problem

**Comment by MuchiMuchiPink** [comment] 2019-11-13 10:05
@Shadowedstalker should have said `cd /var/mobile/Library/Cydia` instead of `cd var/mobile/Library/Cydia` When you ssh into the phone you sit in the home directory of the user root which is` /var/root`, thus the directory` var/` is not found. Pretty sure you know, but remember not everyone here is that savvy.

**Comment by Shadowedstalker** [comment] 2019-11-13 13:24
I did know that and I mentioned that above 


@GuyInHiding
Author
GuyInHiding commented 14 hours ago

The only directories I have are Library and Media
image
@Shadowedstalker
Shadowedstalker commented 14 hours ago

OK, here's your problem.

type CD /
now you will be at root and LS you will see the directories.

**Comment by Shadowedstalker** [comment] 2019-11-13 13:29
But I do see you point.

**Comment by Shadowedstalker** [comment] 2019-11-13 23:13
I see you are trying to help others, Thanks. Can you close this issue so that people aren't trying to add comments and can help others.

thanks.

**Comment by Siguza** [comment] 2020-02-07 00:30
Duplicate of #60.

**Closed as completed by Siguza** 2020-02-07 00:30 UTC
Labels: status-duplicate
