### ISSUE TITLE
Cannot connect to SMB server in the Files app after jailbreaking

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#622] opened 2019-12-11 19:40 UTC
**Tell us about your setup:**
1. iPad Pro 1st gen
2. 13.2.3
3. GUI 0.9.6
4. Catalina 10.15.1
5. USB-A-C hub

**What are the steps to reproduce the issue?**
1. Connect to smb server in the files app
2. It won't

**What do you expect, and what is happening instead?**
I tried this unjailbroken and it worked perfectly. Could not reconnect to it after jailbreaking.

**Does the issue also occur if you enable Safe Mode?**
No!

**Comment by Siguza** [comment] 2019-12-12 04:17
Duplicate of #171.

**Closed as completed by Siguza** 2019-12-12 04:17 UTC
Labels: status-duplicate
