### ISSUE TITLE
Could not get kernel task port (os/kern failure)

### ISSUE THREAD

**Issue by jorgschulze73** [checkra1n/BugTracker#1062] opened 2020-03-17 11:11 UTC
**Tell us about your setup:**
1. What iDevice are you using? iPhone 7
2. On what version of iOS is it? 13.2.3
3. What version of checkra1n are you using? GUI or CLI? 0.9.8.2 CLI
4. What is your host system (OS version? Hackintosh? VM? etc.)? Mac
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Normal USB cable

**What are the steps to reproduce the issue?**
1. I created an iOS dylib which is supposed to be loaded in an app through MobileSubstrate (`/Library/MobileSubstrate/DynamicLibraries/`)
2. This dylib is very simple, just tries to get the kernel task port (`task_for_pid(0)`):
```
mach_port_t kernel_task_port = MACH_PORT_NULL;
kern_return_t kr = task_for_pid(mach_task_self(), 0, &kernel_task_port);
if (kr != KERN_SUCCESS) {
    NSLog(@"No task port! Error: %#x (%s)", kr, mach_error_string(kr));
    return;
}
```
3. I ad-hoc code signed the library using jtool with the following entitlements:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>get-task-allow</key>
	<true/>
	<key>task_for_pid-allow</key>
	<true/>
	<key>platform-application</key>
	<true/>
	<key>com.apple.private.security.no-container</key>
	<true/>
</dict>
</plist>
```
4. I start the target application
5. `task_for_pid` returns `Error: 0x5 ((os/kern) failure)`

**What do you expect, and what is happening instead?**
I would expect the kernel task port to be put into the `kernel_task_port` variable, and `KERN_SUCCESS` to be returned from the call to `task_for_pid`.

**Comment by jorgschulze73** [comment] 2020-03-17 15:01
I guess this is happening because app is run as `mobile` and not as `root`? 
I tried to `setuid(0)` and `setgid(0)` in order to run as `root` but it's not working: guess it's an use case you've never implemented?
And if that's the case, is there any way to get access to the kernel task port from userland?

**Comment by Siguza** [comment] 2020-03-18 22:30
Yes, you need to be root. And you cannot just become root by using `setuid`, since you need to be root in order to use that in the first place.  
Moreover, entitlements on libraries don't mean anything. They are only looked at for the main binary of any process.

Forgive my skepticism, but if you are this unfamiliar with Mach and BSD APIs, are you sure you should be making changes to kernel memory, and even more from within an app context? If you truly feel like you do, create a dedicated XPC daemon that runs as root and talk to that from your tweak.

Going to close this as "no action needed", since, for all I can tell, tfp0 and access permissions are working as intended.

**Closed as completed by Siguza** 2020-03-18 22:30 UTC
Labels: status-no-action-required

**Comment by jorgschulze73** [comment] 2020-03-19 03:49
I’m sorry, but doesn’t something like the host special port 4 patch allow to export the kernel task port in userland, without root being a pre-requirement? Why can’t we have something similar with checkra1n as well?

**Comment by Siguza** [comment] 2020-03-19 07:00
hsp4 also requires root, and always did. And that's by design. You don't _want_ anything else to have the kernel task port.
