### ISSUE TITLE
Doesn't Work on M1 MacBook Air 2020 (BigSur), Stuck at "Waiting for DFU Devices"

### ISSUE THREAD

**Issue by mpacepa** [checkra1n/BugTracker#1862] opened 2020-11-21 14:49 UTC
Tell us about your setup:

1.  What iDevice are you using? iPhone X (Verizon)

2.  On what version of iOS is it? iOS 13.7

3.  What version of checkra1n are you using? 0.12.1

4.  What is your host system (OS version? Hackintosh? VM? etc.)? ARM, 2020 M1 MacBook Air, BigSur

5.  How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Official Apple USB-A cable with USB-C adapter.

After putting device in recovery mode, I follow the directions to hold down power button + volume down, iPhone restarts and then is stuck with a black screen.  In the app, it says "Waiting for DFU Devices" and never goes any further.  

Tried it on my wife's Intel x86 MacBook Pro (2017) & MojaveOS and no issues.  jailbreak goes through and works perfectly then.  same (official apple) USB cable and everything.

issue only occurs on my new M1 2020 MacBook Air with BigSur.  Tried it multiple times -- same result every time.  

iPhone is then stuck in recovery mode and have to manually kick the phone out of that mode.

My guess is the issue lies with the fact its an ARM chip and/or BigSur and/or a combination of the two.

**Comment by RonaldRegister** [comment] 2020-12-12 15:46
Can confirm the same issue here. iPhone X with an M1 MacBook. Checkra1n 0.12.1 stuck at "Waiting for DFU devices"
I'm using the official USB-C to USB-A adapter from Apple, with an original USB-A to Lightning cable.

**Comment by CarlesLlobet** [comment] 2020-12-15 20:14
I can confirm same issue here.

Tell us about your setup:

What iDevice are you using? iPad mini 2

On what version of iOS is it? iOS 12.5

What version of checkra1n are you using? 0.12.1

What is your host system (OS version? Hackintosh? VM? etc.)? ARM, 2020 M1 MacBook Air, BigSur

How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Official Apple USB-A cable with USB-C adapter.

After putting device in recovery mode, I follow the directions to hold down power button + home down, iPad restarts and then is stuck with a black screen. In the app, it says "Waiting for DFU Devices" and never goes any further.

I also tried running it with rosetta:
`cd /Applications/checkra1n.app/Content/MacOS && sudo arch -x86_64 checkra1n`

But exactly same result, after successfully putting my iPad in DFU Mode, stuck in "Waiting for DFU devices"

**Comment by git-anish** [comment] 2020-12-28 04:07
any updates on this?

**Comment by osnelson-git** [comment] 2021-01-15 21:52
Tell us about your setup:

What iDevice are you using? iPod Touch

On what version of iOS is it? iOS 14.2

What version of checkra1n are you using? 0.12.2

What is your host system (OS version? Hackintosh? VM? etc.)? ARM, 2020 M1 MacBook Air, BigSur

How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Official Apple USB-A cable with USB-C adapter.

After putting device in recovery mode, I follow the directions to hold down power button + volume down, iPhone restarts and then is stuck with a black screen. In the app, it says "Waiting for DFU Devices" and never goes any further.  If I force quit Checkra1n, disconnect the iPod touch and re-attach it I can get this message: 
iPod Touch (7th gen) connected in DFU mode.
ECID: 0x1958942293....
Please connect device in Normal/Recovery mode or run checkra1n in CLI mode

**Comment by dheerajbred** [comment] 2021-01-18 20:23
Same issue
iPhone 6s (IOS 13.3) and Ipad pro 12 inch (old)(IOS 14.3)
M1 Mac Mini 16gb ram
Able to do it in the old windows laptop using belenaetcher and a USB drive. But on mac it is not working.


https://user-images.githubusercontent.com/46578244/104959686-c4982980-59f8-11eb-8b4a-640270f457b6.mov
device restarts but stuck with a black screen. No code running scene was shown.

**Comment by webmanjonny** [comment] 2021-01-21 10:02
Hi all, I had the exact same issue. Turns out it was the USB C cable that fixed the problem. Try another cable to anyone who can't get it working on M1 BigSur!

**Comment by alomerry** [comment] 2021-01-22 20:01
Same issue
iPhone 6s(IOS 13.3)
M1 MacBook Air 16GB ram.
Able to do it in the old desktop by hackintosh.

**Comment by ET02** [comment] 2021-02-17 11:07
Same for me
iPhone X(GSM) 
iOS 13.6.1
M1 MacBook Pro 8 gb ram.

**Comment by CarlesLlobet** [comment] 2021-02-17 11:43
Please stop commenting same issues with Apple Silicon (M1) Macs.
It is a known issue that checkra1n does not currently support M1 Macs and stated officially in their last release in the website:
![image](https://user-images.githubusercontent.com/6575422/108199565-84be8200-711d-11eb-98a6-7b9dbc8b742e.png)

Since there is a lot of demand they'll probably look to support it soon, hence the issue is still open and they have not closed it, but there is no point in this issue being commented by every Mac M1 user.

**Comment by Grandboy46** [comment] 2021-02-26 11:08
Same Problem, tried CLI, normal version, no luck.

**Comment by tuguldur** [comment] 2021-04-10 02:34
any updates on this? 🥺

**Comment by Siguza** [comment] 2021-04-30 01:22
Should be fixed in 0.12.3.

**Closed as completed by Siguza** 2021-04-30 01:22 UTC
Labels: status-fixed
