### ISSUE TITLE
IOS 14.3 Jailbreak not working

### ISSUE THREAD

**Issue by Florian-Mahlberg** [checkra1n/BugTracker#1898] opened 2020-12-17 17:35 UTC
Tell us about your setup:

1. iPad 2019
2. 14.3
3. 0.12.1
4. MacOS / Kali
5. Official apple usb cable

What are the steps to reproduce the issue?

1. Trying to Jailbreak

What do you expect, and what is happening instead?
No checkra1n was installed. Checkra1n has a timeout

Did you see a popup on the device stating it entered "Safe Mode" due to an error?
No

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?
Yes

**Comment by huqfeVmewzy3w** [comment] 2020-12-18 02:44
https://github.com/checkra1n/BugTracker/issues/1898#issue-770238780

**Comment by huqfeVmewzy3w** [comment] 2020-12-18 02:44
> #1898 (comment)

**Comment by Siguza** [comment] 2020-12-20 21:34
Duplicate of #1879.

**Closed as completed by Siguza** 2020-12-20 21:34 UTC
Labels: status-duplicate
