### ISSUE TITLE
Ipad Mini 4 Timeout during jailbreak

### ISSUE THREAD

**Issue by nuc1** [checkra1n/BugTracker#1365] opened 2020-05-18 15:56 UTC
**Tell us about your setup:**
1. What iDevice are you using?
 ipad Mini 4
2. On what version of iOS is it?
 13.4.1
3. What version of checkra1n are you using?
0.10.1 for Mac
4. What is your host system (OS version? Hackintosh? VM? etc.)?
 Mac OS Catalina 10.15.2
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
 Apple USB -> Lightning cable

**What are the steps to reproduce the issue?**
1. Start Checkra1n
2. Set ipad to recovery mode
3. Set ipad in DFU mode
4. Start jailbreak
5. See checkra1n logo on ipad screen (appears to be working)
...

**What do you expect, and what is happening instead?**
 Receive error for timeout (suspected tweak)
 ipad has been restored to factory settings before jailbreak attempt
 happens even if in Safe Mode

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment] 2020-05-18 20:11
Duplicate of #1168.

**Closed as completed by Siguza** 2020-05-18 20:11 UTC
Labels: status-duplicate
