### ISSUE TITLE
SMB Connections / Ejection Fails In Jailbroken State

### ISSUE THREAD

**Issue by PRTNaus** [checkra1n/BugTracker#592] opened 2019-12-06 05:58 UTC
**Tell us about your setup:**
1. What iDevice are you using? **iPad Air 2**
2. On what version of iOS is it? **13.2.3**
3. What version of checkra1n are you using? GUI or CLI? **GUI**
4. What is your host system (OS version? Hackintosh? VM? etc.)? **iMac 27" Catalina**
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? **Apple Lightning Cable**

**What are the steps to reproduce the issue?**
1. Connect to SMB share on LAN.
2. Successfully access network share.
3. Jailbreak with checkra1n 0.9.6.
4. Install Cydia.
5. Open files.
6. Click on your previously setup share which won't load/connect/mount.
6.5. Attempting to 'eject' the share will fail, it won't do ANYTHING and seeing up a new share also does nothing.
7. Hard reset.
8. Works fine un-jailbroken.
...

**What do you expect, and what is happening instead?**
I expect to be able to connect to my SMB share on my local network which works fine un-jailbroken but is incredibly broken jailbroken.

**Does the issue also occur if you enable Safe Mode?**
Yes, unfortunately.

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment] 2019-12-12 04:17
Duplicate of #171.

**Closed as completed by Siguza** 2019-12-12 04:17 UTC
Labels: status-duplicate
