### ISSUE TITLE
MacOS 11.2.1 

### ISSUE THREAD

**Issue by MuMuTian** [checkra1n/BugTracker#2010] opened 2021-02-18 03:56 UTC
**Tell us about your setup:**
1. What iDevice are you using? mac11.2.1
2. On what version of iOS is it? 12.5.1
3. What version of checkra1n are you using? lastest
4. What is your host system (OS version? Hackintosh? VM? etc.)? mac
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? usb-c

**What are the steps to reproduce the issue?**
1.  start  press home and side btn 
2. restart 
3. Loop this step1.2

I guess my os version is too new.
I changed to another mac 11.0.1, it can successfully jailbreak.

**Comment by moabbikr** [comment] 2021-02-20 01:06
Same with 11.3 Beta

**Comment by teelekkung** [comment] 2021-02-23 01:48
#1994 and #2005 has the same issue report before

**Comment by Siguza** [comment] 2021-04-30 02:05
Duplicate of #1994.

**Closed as completed by Siguza** 2021-04-30 02:05 UTC
Labels: status-duplicate
