### ISSUE TITLE
iPad Air 1 issue 

### ISSUE THREAD

**Issue by CertifiedDealerOne** [checkra1n/BugTracker#564] opened 2019-12-01 23:45 UTC
**Tell us about your setup:**
1. What iDevice are you using?   MacBook Pro retina Catalina 10.15.1
2. On what version of iOS is it?  iOS 13.2.2
3. What version of checkra1n are you using? GUI or CLI? checkra1n beta version 0.9.6
4. What is your host system (OS version? Hackintosh? VM? etc.)? macOS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? 3rd party cable USB-A

**What are the steps to reproduce the issue?**
1. when I plug the device for jailbreak then open the tool its show the window and ready for jailbreak 
2. when I launch its put the device in recovery mode and don't show the second window to press for getting in DFU mode for jailbreak
3. its stuck on the window and Next button don't react to any press, its not response 
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?** ive tried all available and still same issue, and im not alone in this situation, ive done many model of iPad but iPad Air 1, its really a issue with checkra1n, 

**Any other info, error logs, screenshots, ...?** no its frozen don't show anything

**Comment by Siguza** [comment] 2019-12-02 00:48
Duplicate of #292

**Closed as completed by Siguza** 2019-12-02 00:48 UTC
Labels: status-duplicate
