### ISSUE TITLE
Safe Mode option not working

### ISSUE THREAD

**Issue by psilynt1** [checkra1n/BugTracker#1613] opened 2020-08-11 15:09 UTC
**Tell us about your setup:**
1. What iDevice are you using?
- iPhone 7 Plus
2. On what version of iOS is it?
- 13.6
3. What version of checkra1n are you using?
- checkra1n 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
- OSX 10.15.6 on 2016 MBP
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
- Tried multiple different cables and methods of connecting the phone directly to two different Macbook Pros (2015 MBP & 2016 MBP). USBA-to-lightning (oem Apple cable), USBC-to-lightning, USBC-adapter-to-USBA-to-lightning. Makes no difference.

**What are the steps to reproduce the issue?**
1. Install a bad cydia package that causes springboard to crash ("Bolders" was my pick ...) and then hard reboot the phone into a jailed state.
2. Enable "Safe Mode" and "Untested Versions" checkboxes within checkra1n and follow steps to jailbreak. 
3. checkra1n says it's done but the phone fails to boot twice then starts up jailed.

**What do you expect, and what is happening instead?**
- I hoped to see springboard start in jailbroken safe mode so I can uninstall the bad package. Instead, it fails to boot twice, then starts up in a jailed state with no checkra1n app on the phone.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
- This ticket is about that exact button not working.

**Any other info, error logs, screenshots, ...?**
- I've also tried holding the volume up button during bootup many, many times with slight variations on when I start holding the button but it never boots into safe mode that way either. Read multiple guides, watched multiple videos, and tried all the tricks I could find mentioned about getting checkra1n into safe mode but no dice. 
- Will be happy to provide anything else requested.

**Comment by Siguza** [comment] 2020-08-11 15:29
Running an iPhone 8 here with iOS 13.6.  
Installed "Bolders", which put Springboard into Substrate's Safe Mode, but that's still working. Then rebooted and rejailbroken with Safe Mode, everything worked as expected. Was able to uninstall the package and have everything go back to normal.

I'm pretty sure Substrate is not being launched for you and the cause for the crash lies elsewhere. More logging would be ideal, but that's a real pain to get without a serial cable... I suppose you could try verbose boot and see if anything relevant is logged there? :/

**Comment by demhademha** [comment] 2020-08-11 15:32
Out of interest, what happens when you jailbreak with safemode off?

**Comment by psilynt1** [comment] 2020-08-11 15:43
> I'm pretty sure Substrate is not being launched for you and the cause for the crash lies elsewhere. More logging would be ideal, but that's a real pain to get without a serial cable... I suppose you could try verbose boot and see if anything relevant is logged there? :/

I enabled verbose boot but I'm not able to get much out of what I'm seeing. It runs through like normal until the checkra1n logo, then I can see the verbose boot output scroll by, followed by the apple logo appearing, at which point it proceeds to boot loop until it comes up in a jailed state.

> Out of interest, what happens when you jailbreak with safemode off?

I see the same behavior with and without safe mode enabled, two boot attempts then it comes up jailed.

**Comment by Siguza** [comment] 2020-08-11 15:47
What do you mean by "two boot attempts"?

**Comment by psilynt1** [comment] 2020-08-11 16:09
My apologies, I thought it was two boot attempts but I sat down just now and took some more detailed notes on exactly what happens and it appears that it is three boot attempts. I have listed the behavior out below. I believe what I'm seeing are reboots of some kind but not positive.
- Start checkra1n osx app (with all options enabled)
- Recovery screen/DFU stuff
- First apple logo appears (~2 sec)
- checkra1n logo appears (~5 sec)
- verbose boot appears (~10 sec)
- checkra1n osx app shows "done"
- Second apple logo appears (60 sec exactly) (first boot attempt)
- Black screen/Reboot (~1 sec)
- Third apple logo appears (60 sec exactly) (second boot attempt)
- Black screen/Reboot (~1 sec)
- Fourth apple logo appears (60 sec exactly) (third boot attempt)
- Black screen/Reboot (~5 sec)
- Fifth apple logo appears (~25 sec)
- Lock screen is finally displayed, phone in jailed state

**Comment by Siguza** [comment] 2020-08-11 20:31
And when you normally reboot your phone without checkra1n, it always boots on the first try?

**Comment by psilynt1** [comment] 2020-08-11 20:50
> And when you normally reboot your phone without checkra1n, it always boots on the first try?

Thats correct, without checkra1n it boots within 30 seconds without issue everytime.

**Comment by saifallfe** [comment] 2020-08-14 06:35
Thanks

**Comment by QQChowey** [comment] 2020-09-01 05:19
Perhaps it was a conflict between two tweaks?

**Comment by Siguza** [comment] 2020-09-03 01:17
I think I know what the issue is here. It stems from a bad design decision on our end, I guess.

**Comment by Fiery117** [comment] 2020-09-04 14:33
Will it be fixed?

**Comment by edoo1** [comment] 2020-09-09 19:25
When will it be fixed?

**Comment by JStormCatcher** [comment] 2020-09-16 06:52
I’m having this issue as well, really hope it gets fixed soon because I have a Windows PC and I’m using bootra1n. If it’s fixed then I’ll have to wait for bootra1n to update as well..

**Comment by EmanuelPermane** [comment] 2020-09-17 01:54
@JStormCatcher @edoo1 @Fiery117 @psilynt1 check out #1676 to see if it helps you.

**Comment by JStormCatcher** [comment] 2020-09-17 02:34
> 
> 
> @JStormCatcher @edoo1 @Fiery117 @psilynt1 check out #1676 to see if it helps you.

I have a Windows PC and I was using bootra1n to jailbreak my phone.

**Comment by Siguza** [comment] 2020-09-22 04:17
Should be fully fixed on 0.11.0.

**Closed as completed by Siguza** 2020-09-22 04:17 UTC
Labels: status-fixed
