### ISSUE TITLE
apple keyboard disconnecting

### ISSUE THREAD

**Issue by rcpag1103** [checkra1n/BugTracker#246] opened 2019-11-12 14:50 UTC
**What device + iOS version are you on?**
1
ios 13.2.2 ipad 7th gen

**What checkra1n version are you using?**
i checked in 0.9.1 and 0.9.2 still same issue
**What are the steps to reproduce the issue?**
1. when in unjailbroken state, no issues with smart keyboard
2.when in jailbroken state, keyboard suddenly cannot be recognized
3.
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment] 2019-11-13 18:05
closed as a dupe of #48

**Closed as completed by nullpixel** 2019-11-13 18:05 UTC
Labels: status-duplicate
