### ISSUE TITLE
Cydia is not Open

### ISSUE THREAD

**Issue by King-Software** [checkra1n/BugTracker#1998] opened 2021-02-12 20:11 UTC
Using an Ipad Air 2 Wifi with the Checkra1n 0.12.2 Beta. The jailbreake works fine, but after installing Cydia i can not open it. It open, load a few second and than i got back to the Homescreen

**Comment by Siguza** [comment] 2021-02-27 15:36
Duplicate of #804.

**Closed as completed by Siguza** 2021-02-27 15:36 UTC
Labels: status-duplicate
