### ISSUE TITLE
Error code -27

### ISSUE THREAD

**Issue by Willianbt** [checkra1n/BugTracker#108] opened 2019-11-10 19:53 UTC
Hello!
I have a problem, giving error code 27. The following message appears during jailbreak installation: "Error report - Request for Permission".

Help me

Iphone 7 GSM
iOs 13.1.3

**Comment by Lonegwadiwaitor** [comment] 2019-11-10 19:57
Have you made sure to click the 'Trust this Computer?' box on your iPhone?

**Comment by Willianbt** [comment] 2019-11-10 19:58
No, it's not showing up to me hahaha

**Comment by Willianbt** [comment] 2019-11-10 20:04
YES, trust this computer

**Comment by Lonegwadiwaitor** [comment] 2019-11-10 20:27
Just to confirm, works now?

**Comment by Willianbt** [comment] 2019-11-10 20:29
no, now it's in error code -31

**Comment by Lonegwadiwaitor** [comment] 2019-11-10 20:33
Are you on a Hackintosh or an actual Mac?

**Comment by Willianbt** [comment] 2019-11-10 20:33
Hackintosh

**Comment by nullpixel** [comment] 2019-11-10 20:52
Dupe of #9, hackintoshes are not supported technically.

**Closed as completed by nullpixel** 2019-11-10 20:52 UTC
Labels: status-duplicate
