### ISSUE TITLE
Error -20 iPad Pro 9.7 1st gen iOS 14.5 (A9X / iOS 14.5: Detected corrupted kerninfo)

### ISSUE THREAD

**Issue by BorisYeltsin** [checkra1n/BugTracker#2082] opened 2021-05-03 08:17 UTC
**Tell us about your setup:**
1. iPad Pro 9.7 1st gen
2. 14.5
3. beta 0.12.3
4. iMac Big Sur 11.3
5. Directly into the USB via authentic USB-A cable

Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)

Doesn't work even on the freshly reset device

**Comment by 513Kernal** [comment] 2021-05-03 08:46
I’m also having the same problem.

iPad Pro 9.7 first gen
14.5
Mac Catalina 
Beta 0.12.3
USB A-Lightning multiple cables tried
iPad was also factory reset getting the same errors as above 

tried with safe mode, with all options on except for a11 bypass, before and after FDR (factory data reset) as well as tried to update Mac.

**Comment by BorisYeltsin** [comment] 2021-05-03 08:46
and the terminal version of Checkrain doesn't work either

**Comment by 513Kernal** [comment] 2021-05-03 08:48
![A3ABE48F-D1DD-4332-BB33-9E9D8B60E5CE](https://user-images.githubusercontent.com/78218137/116857430-cb733280-abca-11eb-99d9-2f016a22a003.jpeg)


I assume yours looks like this as well

**Comment by BorisYeltsin** [comment] 2021-05-03 08:51
> I assume yours looks like this as well

Yep 😞

**Comment by BorisYeltsin** [comment] 2021-05-03 08:55
and I also tried to disable the password. No luck

**Comment by BorisYeltsin** [comment] 2021-05-03 08:59
![IMG_9374](https://user-images.githubusercontent.com/33380863/116858425-04c99380-ac07-11eb-927c-099f93bee8f7.jpg)

**Comment by 513Kernal** [comment] 2021-05-03 09:19
Yeah I’ve disabled passcodes
Tried with no Apple ID 
Tried with Apple ID before reset
Tried with Apple ID after reset

**Comment by waqasnasir4** [comment] 2021-05-03 09:35
Step by Step Guide on how I did it 
https://m.imgur.com/a/NjVJnSg
Might work or might not, give it a shot

**Comment by BorisYeltsin** [comment] 2021-05-03 09:47
> Step by Step Guide on how I did it
> https://m.imgur.com/a/NjVJnSg
> Might work or might not, give it a shot

doesn't work 😞

**Comment by BorisYeltsin** [comment] 2021-05-03 10:00
I guess the most active discussion on the task is here
https://github.com/checkra1n/BugTracker/issues/2074#issue-872983397

**Comment by 513Kernal** [comment] 2021-05-03 11:15
> Step by Step Guide on how I did it
> https://m.imgur.com/a/NjVJnSg
> Might work or might not, give it a shot

Are you using a iPad Pro with A9X on 14.5?

**Comment by waqasnasir4** [comment] 2021-05-03 11:40
> > Step by Step Guide on how I did it
> > https://m.imgur.com/a/NjVJnSg
> > Might work or might not, give it a shot
> 
> Are you using a iPad Pro with A9X on 14.5?

Sorry no I have an iPhone X 14.5

**Comment by hostrogo** [comment] 2021-05-03 11:55
> > Step by Step Guide on how I did it
> > https://m.imgur.com/a/NjVJnSg
> > Might work or might not, give it a shot
> 
> Are you using a iPad Pro with A9X on 14.5?

I have an iPad Pro with A9X, and it does not work for me too.

**Comment by Glazesglib0f** [comment] 2021-05-03 12:41
I have the same issue
checkrian 0.12.3
Restore to 14.5 factory state (w/o passcode & login apple id)
checkrian stuck at booting and ipad stuck at boot logo w/ checkrian "pangoOS>"
option safe mode/untest ios doesn't work

Restore to 14.4.2 -> same issue

**Comment by mystrain** [comment] 2021-05-03 13:02
Same issue it’s so frustrating

**Comment by mystrain** [comment] 2021-05-03 13:53
Hi guys 

I think your issues are related to this:

A9X / iOS 14.5: Detected corrupted kerninfo #2074

**Comment by BorisYeltsin** [comment] 2021-05-03 14:07
> Hi guys
> 
> I think your issues are related to this:
> 
> A9X / iOS 14.5: Detected corrupted kerninfo #2074

Hi! I've already mentioned your thread :)

**Comment by jujjja** [comment] 2021-05-03 14:09
We re more and more to see this issue without having the possibility to comeback to 14.4.2. This should be shared so that no more get the same issue! 
By the way, since 14.4.2 can t be jailbreaked after 14.5 update, could this be explained by another kind of update from Apple? (boot partition or what else?)

**Comment by hostrogo** [comment] 2021-05-03 14:56
> We re more and more to see this issue without having the possibility to comeback to 14.4.2. This should be shared so that no more get the same issue!
> By the way, since 14.4.2 can t be jailbreaked after 14.5 update, could this be explained by another kind of update from Apple? (boot partition or what else?)

Update of the firmware of the device, probably.

**Comment by mystrain** [comment] 2021-05-03 17:12
> > Hi guys
> > I think your issues are related to this:
> > A9X / iOS 14.5: Detected corrupted kerninfo #2074
> 
> Hi! I've already mentioned your thread :)

Thank you.
The more people that complain the more they will notice and get an update soon, I hope.

**Comment by Siguza** [comment] 2021-05-03 18:15
Duplicate of #2074.

**Closed as completed by Siguza** 2021-05-03 18:15 UTC
Labels: status-duplicate
