### ISSUE TITLE
Checkra1n 0.11.0 stuck at  booting stage on ipad mini2 while checkra1n version 0.10.2 works as expect

### ISSUE THREAD

**Issue by berkejf** [checkra1n/BugTracker#1698] opened 2020-09-24 01:10 UTC
**Tell us about your setup:**
1. What iDevice are you using? ipad mini 2
2. On what version of iOS is it?  ios 12.4.7
3. What version of checkra1n are you using? 0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?  OSX 10.11
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A

**What are the steps to reproduce the issue?**
1. run checkra1n
2. boot ipad mini2 into DFU mode
3. start patch on ipad mini2
4. ipad mini2 show the patching status till Booting, but never booted
5. checkra1n program display booting timeout

**What do you expect, and what is happening instead?**
it should boot successfully and got jailbreak.  I change to version 0.10.2. it works as expected.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by DEALWITHIT199** [comment] 2020-09-25 14:14
Checkra1n 0.11.0 doesn't support iPad Mini 2. So use Checkra1n 0.10.2 it supports iPad Mini 2.

**Comment by n0k0m3** [comment] 2020-10-01 02:13
Maybe some clues for @Siguza to solve issue #1692

**Comment by Siguza** [comment] 2020-10-04 19:27
Dupe of #1689.

**Closed as completed by Siguza** 2020-10-04 19:27 UTC
Labels: status-duplicate
