### ISSUE TITLE
iPhone not Jailbreaking

### ISSUE THREAD

**Issue by Souldbminer** [checkra1n/BugTracker#1542] opened 2020-07-07 05:20 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 6,1/ iPhone 5s
2. On what version of iOS is it?
IOS 12.4.7
3. What version of checkra1n are you using?
0.10.2 Beta
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MacOS X 10.14.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
apple USB cable
**What are the steps to reproduce the issue?**
1. i tried the jailbreak 3 times, but this message popped up: send error to chekara1n team
with CPU type and other stuff. so basically it cannot progress to install the jailbreak. but when i click yes then it continues jailbreaking.
\

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
Nope

**Comment by Siguza** [comment] 2020-07-10 13:14
Closing this because it has zero detail.  
If you still have the issue, please file a new ticket and fill out the "steps to reproduce" part.

**Closed as completed by Siguza** 2020-07-10 13:14 UTC
Labels: status-invalid
