### ISSUE TITLE
iPad Pro 1st 9.7 error 20 on iOS 14.1

### ISSUE THREAD

**Issue by alezzzzzz1** [checkra1n/BugTracker#1794] opened 2020-11-06 07:14 UTC
1.What iDevice are you using?
iPad Pro 1st 9.7 WiFi only 
On what version of iOS is it?
14.1
2.What version of checkra1n are you using?
Any version (currently on 0.11)
3.What is your host system (OS version? Hackintosh? VM? etc.)?
MacBook Air 2012
4.How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)
 USB-A original lightning cable
5.What are the steps to reproduce the issue?

1)Plug in iPad 
2)Run checkra1n
3)Get to "Booting..." stage
4)Watch iPad  reboot into normal mode
6.What do you expect, and what is happening instead?
I expect to boot with checkra1n enabled. Instead, I am booting into normal, unjailbroken mode and checkra1n says “error20”

7.Does the issue also occur if you tick "Safe Mode" in the checkra1n options?
Yes, issue occurs no matter what

**Comment by Sandwhich253989** [comment] 2020-11-06 08:36
Duplicate of #1689

**Closed as completed** 2020-11-20 06:33 UTC
