### ISSUE TITLE
Cant Jailbreak Ipad mini 4 

### ISSUE THREAD

**Issue by Dutches90** [checkra1n/BugTracker#1325] opened 2020-05-09 21:56 UTC
**Tell us about your setup:**
1. What iDevice are you using?
Ipad mini 4 A1550
2. On what version of iOS is it?
13.4.1 after full restoring with no data inside

3. What version of checkra1n are you using?
0.10.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Mac OS High Sierra 10.13.6

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Directly via USB with original lighting cable that was tested ok with more than 100 devices for jailbreak 
**What are the steps to reproduce the issue?**
1. Made the Jailbreak via checkrain 0.10.1
2. After putting the device in DFU directly push the volume up button and home button entering diagnostics after first step of jain
3. After the device entered diagnostics try to mina usb, press start but nothing happened
...

**What do you expect, and what is happening instead?**
Jailbreak the device so that i can use silver and ticket to use the device

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**

**Comment by demhademha** [comment] 2020-05-12 07:21
.,. You don’t need diagnostics, just enter DFU mode

**Comment by Siguza** [comment] 2020-05-16 05:29
Duplicate of #1168.

**Closed as completed by Siguza** 2020-05-16 05:29 UTC
Labels: status-duplicate
