### ISSUE TITLE
Checkra1n on iPhone show No internet connect then close

### ISSUE THREAD

**Issue by qyouqme** [checkra1n/BugTracker#11] opened 2019-11-10 13:49 UTC
**What device + iOS version are you on?**
iPhone 6s+iOS 13.2.2

**What are the steps to reproduce the issue?**
1.
2.
3.
...

**What do you expect, and what is happening instead?**
Run Checkra1n app on iPhone

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment] 2019-11-10 13:54
Hi, do you have a Chinese iPhone?

**Comment by qyouqme** [comment] 2019-11-10 13:57
> Hi, do you have a Chinese iPhone?

Yes.

**Comment by nullpixel** [comment] 2019-11-10 13:58
Hi, I've closed this issue as a duplicate of #3.

**Closed as completed by nullpixel** 2019-11-10 13:58 UTC
Labels: status-duplicate
