### ISSUE TITLE
Doesn't work on iPad Pro 9.7 (A9X) with iOS 14 & iOS 14.0.1

### ISSUE THREAD

**Issue by shikiroot** [checkra1n/BugTracker#1707] opened 2020-09-26 09:34 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPad Pro 9.7 (A9X)
2. On what version of iOS is it?
iOS 14 & iOS 14.0.1
3. What version of checkra1n are you using?
0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
macOS 10.15.7
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A
**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**
After displaying the checkra1n icon and other log information, the screen becomes black and the system restarts to normal mode.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
YES

**Any other info, error logs, screenshots, ...?**

**Comment by BorisYeltsin** [comment] 2020-09-26 10:42
Same story. Tried to factory reset the device still nothing. Getting Error 20 every time on two different Macs. Also tried different cables still no luck

**Comment by Siguza** [comment] 2020-09-26 16:25
Duplicate of #1692.

**Closed as completed** 2020-09-26 16:25 UTC
Labels: status-duplicate
