### ISSUE TITLE
Checkra1n do not reconice my iphone SE

### ISSUE THREAD

**Issue by danielhmorenog** [checkra1n/BugTracker#1696] opened 2020-09-23 20:11 UTC
**Tell us about your setup:**
1. What iDevice are you using? Iphone SE 1 generation
2. On what version of iOS is it? ios 14.0
3. What version of checkra1n are you using? 0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)? bootra1n
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? usb A Apple

**What are the steps to reproduce the issue?**
1. connect the usb with bootra1n
2. run checkra1n whit sudo 
3.connect my iphone
...

**What do you expect, and what is happening instead?**
I expected that checkra1n reconice my device but instead don't so I can´t continue

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes also happend the same 

**Any other info, error logs, screenshots, ...?**
I try on 2 differents pcs and in both happend the same, I check my cable on winwows and work perfect
my device had Jailbreak with checkra1n 0.10.2 on ios 13 and the only thing that I do was turn off the device and turn on again to install ios 14 and then make jailbreak

**Comment by Siguza** [comment] 2020-09-23 21:48
Could this be a dupe of #1686? Could you try and see if `usbmuxd` is running, or try running `sudo apt-get update && sudo apt-get upgrade`?

**Comment by demhademha** [comment] 2020-09-24 18:11
Refer to https://github.com/foxlet/bootra1n/issues/93

**Comment by DEALWITHIT199** [comment] 2020-09-24 21:48
Again and again, Please "Don't use bootra1n because its still in beta and has a lot of bugs. iPhone is not Recognized solved! go to this [link](https://github.com/foxlet/bootra1n/issues/95)

**Comment by DEALWITHIT199** [comment] 2020-09-25 15:20
> **Tell us about your setup:**
> 
> 1. What iDevice are you using? Iphone SE 1 generation
> 2. On what version of iOS is it? ios 14.0
> 3. What version of checkra1n are you using? 0.11.0
> 4. What is your host system (OS version? Hackintosh? VM? etc.)? bootra1n
> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? usb A Apple
> 
> **What are the steps to reproduce the issue?**
> 
> 1. connect the usb with bootra1n
> 2. run checkra1n whit sudo
>    3.connect my iphone
>    ...
> 
> **What do you expect, and what is happening instead?**
> I expected that checkra1n reconice my device but instead don't so I can´t continue
> 
> **Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
> yes also happend the same
> 
> **Any other info, error logs, screenshots, ...?**
> I try on 2 differents pcs and in both happend the same, I check my cable on winwows and work perfect
> my device had Jailbreak with checkra1n 0.10.2 on ios 13 and the only thing that I do was turn off the device and turn on again to install ios 14 and then make jailbreak

Did you Press "Trust this computer" when you connect your iPhone in checkra1n?. try re-connecting your iPhone to checkra1n and a message should appear on your iPhone saying "Trust this computer?" make sure to click on Trust, and your iPhone should be recognized.

**Comment by DEALWITHIT199** [comment] 2020-09-25 15:22
> Refer to [foxlet/bootra1n#93](https://github.com/foxlet/bootra1n/issues/93)

Bootra1n is still in beta and has a lot of bugs so please use checkn1x rather than bootra1n because checkn1x is better and stable.

**Comment by rzakx** [comment] 2020-09-27 11:20
Follow these steps:

1. sudo apt-get update && sudo apt-get upgrade
2. service usbmuxd restart
3. open checkra1n, plug in device, if it still isnt connected: apt remove checkra1n  and install it again: apt install checkra1n

it solved my problem ;)

**Comment by Siguza** [comment] 2020-09-27 20:50
Marking this as a dupe until I hear otherwise.

**Closed as completed by Siguza** 2020-09-27 20:50 UTC
Labels: status-duplicate
