### ISSUE TITLE
ios 13.6.1 checkrain not working no more.

### ISSUE THREAD

**Issue by ducky3333** [checkra1n/BugTracker#1616] opened 2020-08-13 04:54 UTC
**Tell us about your setup:**
1. What iDevice are you using? iphone 8
2. On what version of iOS is it? 13.6.1
3. What version of checkra1n are you using? 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? big sur lastet build beta
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? anker 7 in hub

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**  safe mode was same.

**Any other info, error logs, screenshots, ...?**
no need

**Comment by TheAwesome98-Real** [comment] 2020-08-16 10:05
There is no information we can’t help.

**Comment by Siguza** [comment] 2020-08-17 13:41
Closing this due to lack of information. If your issue persists, please file a new ticket and make sure to fill out the steps to reproduce.

**Closed as completed by Siguza** 2020-08-17 13:41 UTC
Labels: status-invalid
