### ISSUE TITLE
DFU impossible

### ISSUE THREAD

**Issue by cat24max** [checkra1n/BugTracker#395] opened 2019-11-15 21:53 UTC
**What device + iOS version are you on?**
iPhone X 13.2.2

**What checkra1n version are you using?**
0.9.5

**What are the steps to reproduce the issue?**
1. Connect phone in normal mode
2. Go to recovery with checkra1n
3. Follow the instructions to enter DFU

**What do you expect, and what is happening instead?**
Expected: DFU mode
Happening: Device is **always** booting normally. Getting into DFU from Recovery on the iPhone X is completely impossible.

**Any other info, error logs, screenshots, ...?**
I opened this issue because #291 was closed, however this issue is not completely resolved. Jailbreaking without "clean dfu" always disables the touchscreen and Face ID.

**EDIT: If anyone experiences this and you're using a USB C cable: Use a USB A cable :)**

**Comment by nullpixel** [comment] 2019-11-15 21:56
How are you entering DFU mode? I suspect it's an issue with how you're following the instructions.

> Jailbreaking without "clean dfu" always disables the touchscreen and Face ID.

We're deliberately disabling the entry of DFU mode manually because it causes those issues.

**Comment by kpwn** [comment] 2019-11-15 21:57
Are you using a USB-C cable?

**Comment by cat24max** [comment] 2019-11-15 21:57
I am following the instructions on screen down to the millisecond. Have tried all combinations, played with the timings a lot.

@kpwn Yup.

**Comment by kpwn** [comment] 2019-11-15 22:00
Yeah, there's a known issue with how Apple manufactures those cables (in the new revisions, older ones were fine.. duh) that makes them not suitable for entering DFU. Try with a third party cable or a USB-A one.

**Comment by cat24max** [comment] 2019-11-15 22:04
I just connected my USB-C hub (equipped with 3 USB-A ports) and used my USB A cable.
I was just able to jailbreak my iPhone X for the first time without ANY issues (yet).

The hub didn't work with the old sequence, but works with the new one right now. So technically this should be solved.

**Comment by nullpixel** [comment] 2019-11-15 22:10
marking as fix, but I guess you could call it a dupe of any of the USB C issues (who's # which escapes me right now)

**Closed as completed** 2019-11-15 22:09 UTC
Labels: status-fixed

**Comment by cat24max** [comment] 2019-11-15 22:11
Yup it probably is. I didn't think about it because I tried it before and which cable I used didn't make any difference.
Thanks for all your work @kpwn @nullpixel
