### ISSUE TITLE
the Itunes screen wont appear and I can't put it in DFU mode 

### ISSUE THREAD

**Issue by Al-Rashed** [checkra1n/BugTracker#1097] opened 2020-03-26 19:16 UTC
**Tell us about your setup:**
1. What iDevice are you using? Ipad 6th Generation
2. On what version of iOS is it? 13.3.1
3. What version of checkra1n are you using, and GUI or CLI? 0.10.0 Beta and 0.9.8.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? OS Version
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-C

**What are the steps to reproduce the issue?**
1. it wont enter the DFU Mode 

3.
...

**What do you expect, and what is happening instead?**
2. it should gives me the screen to connect my ipad to itunes but instead it gives a black screen 
[Video.zip](https://github.com/checkra1n/BugTracker/files/4389447/Video.zip)

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
Attached is a video

**Comment by Siguza** [comment] 2020-03-26 22:15
Closing this a duplicate of #1: 

> ## Apple USB-C cables
> 
> In order to enter DFU, iDevices need to detect that a cable is plugged in. For some reason Apple's own USB-C to lightning cables fail to be detected by the SecureROM, so that particular kind of cable cannot be used to enter DFU. There is nothing we can do about that.
> 
> We recommend that you use either a USB-A cable with an adapter, or a 3rd party USB-C cable.

**Closed as completed by Siguza** 2020-03-26 22:15 UTC
Labels: status-duplicate
