### ISSUE TITLE
iPhone 5S: Hangs on "Right before trigger" for more than 10 minutes

### ISSUE THREAD

**Issue by the2048** [checkra1n/BugTracker#893] opened 2020-02-13 04:22 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 5S GSM (A1533)
2. On what version of iOS is it?
12.4.5
3. What version of checkra1n are you using? GUI or CLI?
0.9.8 CLI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Ubuntu 18.04.4 LTS
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A to Lightning, Apple OEM cable
**What are the steps to reproduce the issue?**
1. Connect 5S to ThinkPad.
2. Enter DFU mode after auto recovery mode.
3. Wait.
4. Should be hung up.
**What do you expect, and what is happening instead?**
What do I expect: Progress bar to move forward and device to reboot jailbroken
What happens: Device is stuck at a black screen, and after 15 minutes the device will restart leaving checkra1n hung up.

**Does the issue also occur if you enable Safe Mode?**
Yes.

**Any other info, error logs, screenshots, ...?**
None, seeing as how I can't even make it past "Right before trigger".

**Comment by matthewaudio** [comment] 2020-02-13 16:26
metoo!  on mac

**Comment by bigrck64** [comment] 2020-02-19 17:10
same problem with iPhone5s on iOS 12.4.4 + checkra1n 0.9.8 gui on mac, was OK with checkra1n 0.9.7

**Comment by Rencio7** [comment] 2020-02-24 20:47
I have exactly the same problem. iPhone 5s 12.4.5. Ubuntu... I have tried GUI and CLI to no avail. If I unplug and replug when it hangs the phone does go  through a verbose (can see checkra1n symbol  etc) and code but then it just hangs.

**Comment by AMDBartek** [comment] 2020-03-13 18:33
This is a known issue. #984

**Comment by Siguza** [comment] 2020-03-21 05:35
Marking this as duplicate of #984 (this issue is older, but the other one is more generic and thoroughly documented).

**Closed as completed by Siguza** 2020-03-21 05:35 UTC
Labels: status-duplicate
