### ISSUE TITLE
Don't work fine on iOS 13.6 

### ISSUE THREAD

**Issue by lopsandrea** [checkra1n/BugTracker#1599] opened 2020-08-05 14:51 UTC
**Tell us about your setup:**
1. What iDevice are you using? iPad5,4
2. On what version of iOS is it? 13.6
3. What version of checkra1n are you using? 0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Hackintosh
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?Apple 

**What are the steps to reproduce the issue?**
1. Options, check Allow untested version
2. Wait for the process to finish
3.Try running iproxy 2222 44

**What do you expect, and what is happening instead?**
I expected to establish a connection, but remains on hold

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Nothing, it always goes to "All done"

**Comment by Remoojoker** [comment] 2020-08-07 12:42
hey i have same problem some one help please  ?

**Comment by Siguza** [comment] 2020-08-07 20:29
Cannot reproduce. Tested on iPhone 8, 13.6.

**Comment by lopsandrea** [comment] 2020-08-08 07:16
> Cannot reproduce. Tested on iPhone 8, 13.6.

It is probably due to the A8X processor

**Comment by Siguza** [comment] 2020-08-09 02:21
Updated my iPad Air 2 to 13.6, still can't reproduce.

**Comment by demhademha** [comment] 2020-08-09 18:51
Are your devices  iCloud bypassed / iCloud locked?

**Comment by lopsandrea** [comment] 2020-08-09 18:52
> Are your devices  iCloud bypassed / iCloud locked?

Yep, could that be a problem?

**Comment by Siguza** [comment] 2020-08-09 18:58
Yes. iCloud locked devices are not supported by checkra1n, and ever since the release of checkm8, Apple has constantly been changing the iOS environment pre-activation.

Gonna close this then, under the assumption that the iCloud lock is the culprit.

**Closed as completed by Siguza** 2020-08-09 18:58 UTC
Labels: status-invalid
