### ISSUE TITLE
After jailbreaking no network more

### ISSUE THREAD

**Issue by bolker** [checkra1n/BugTracker#654] opened 2019-12-19 01:26 UTC
Iphone 6 , iphone 6s
Version 13.3.2
used checkra1n 0.9.6

after jailbreaking alle is good but if i pute SIM card cant connecte to network and with Appel store more .

**Comment by Siguza** [comment] 2019-12-19 06:23
Duplicate of #38.

**Closed as completed by Siguza** 2019-12-19 06:23 UTC
Labels: status-duplicate
