### ISSUE TITLE
iPhone 7 Error -6 and error -31

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#101] opened 2019-11-10 19:17 UTC
**What device + iOS version are you on?**
iPhone 7 iOS 13.2.2

**What checkra1n version are you using?**
Beta 0.9
**What are the steps to reproduce the issue?**
1. iPhone 7 in DFU mode
2. Tried both CLI and GUI
3. Error -6 and error -31 (sometimes [*] Checking if device is ready freeze, which sometimes freezes my PC too)
... 

**What do you expect, and what is happening instead?**

To jailbreak this phone
**Any other info, error logs, screenshots, ...?**
For iPhone SE, it works, sometimes with error -6 but jailbreak is successful
I'm using macOS Mojave 10.14.6 (Hackintosh)
 One time it worked, somehow, Cydia and tweaks worked
Everything else is good, when i was on jailbroken, almost all tweaks i wanted worked (iOS 12.4 ones), even Zebra package manager

**Comment by nullpixel** [comment] 2019-11-10 19:18
This is a duplicate of #9 - some hackintoshes are not supported.

**Closed as completed by nullpixel** 2019-11-10 19:18 UTC
Labels: status-duplicate
