### ISSUE TITLE
iOS 14 timed out waiting for bootstrap upload

### ISSUE THREAD

**Issue by jack2000xd** [checkra1n/BugTracker#1615] opened 2020-08-12 21:39 UTC
**Tell us about your setup:**
1. What iDevice are you using? iPhone X 
2. On what version of iOS is it? iOS 14
3. What version of checkra1n are you using?0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Mac OS Catalina 10.15.2
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB C through usb hub 

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**
Error code -20

**Comment by Siguza** [comment] 2020-08-12 22:44
Dupe of #1513

**Closed as completed by Siguza** 2020-08-12 22:44 UTC
Labels: status-duplicate
