### ISSUE TITLE
JB do not works if I need to redo it

### ISSUE THREAD

**Issue by ThiPereira** [checkra1n/BugTracker#1853] opened 2020-11-17 14:27 UTC
I have an iPhone 7 Plus with iOS 14.2
I had to redo the jailbreak but it doesn't work just to run Checkra1n again.
I had to uninstall Cydia and install everything again from scratch.

**Comment by Siguza** [comment] 2020-11-18 04:47
Assuming this is a duplicate of #1825.

**Closed as completed by Siguza** 2020-11-18 04:47 UTC
Labels: status-duplicate
