### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mintiii** [checkra1n/BugTracker#1984] opened 2021-02-02 20:57 UTC
Getting an error on checkra1n 0.12.2 the device is an iPhone 8+ on 14.0

iPhone is connected to a mac on macOS Catalina 10.15 beta using an USB-A to USB-C Adapter

<img width="481" alt="Untitled" src="https://user-images.githubusercontent.com/36900442/106661569-582c3700-656f-11eb-86a4-523b62e16b9f.png">

**Comment by Siguza** [comment] 2021-02-03 17:30
Not an exact dupe of #1857, but probably same root cause...

**Closed as completed by Siguza** 2021-02-03 17:30 UTC
Labels: status-duplicate
