### ISSUE TITLE
'The Internet connection appears to be offline' message shown after clicked into checkra1n

### ISSUE THREAD

**Issue by lehoe** [checkra1n/BugTracker#58] opened 2019-11-10 16:07 UTC
**What device + iOS version are you on?**

**What are the steps to reproduce the issue?**
1.  Install
2.
3.
...

**What do you expect, and what is happening instead?**
The device (iPhone 7 plus) is purchased in China which is somehow related to this issue according to reddit. A similar situation actually happened to me before with Electra jailbreak.

**Any other info, error logs, screenshots, ...?**
![IMG_0497](https://user-images.githubusercontent.com/57595931/68546916-d48ca480-0416-11ea-814a-bca97d86ac6e.PNG)

**Comment by nullpixel** [comment] 2019-11-10 16:09
Hi, I've closed this issue as a duplicate of #3, as it is a bug which affects chinese iPhones.

**Closed as completed by nullpixel** 2019-11-10 16:09 UTC
Labels: status-duplicate
