### ISSUE TITLE
USB Restriction issue

### ISSUE THREAD

**Issue by danforsaken** [checkra1n/BugTracker#1261] opened 2020-04-22 21:32 UTC
In Checkra1n 0.9.5 i could charge my iPhone BFU without a pairing record. I'm wondering if this will be implemented again in the near future?

Sorry if this is the wrong place, please pm me.

**Comment by Siguza** [comment] 2020-04-23 00:02
I just ran a bunch of tests with checkra1n 0.10.1 on iOS 12.3 and 13.4.5 beta 2.  
When cold-booting my devices without having used them for a few hours, USB would always be in restricted mode, and the device would not charge. When unlocking and rebooting, it would always charge BFU. Booting jailbroken or not made no difference.

Given the above, I will close this as "cannot reproduce". If you feel like running further tests and end up discovering an issue that is attributable to jailbroken boot, feel free to reply and I'll reopen the issue.

**Closed as completed by Siguza** 2020-04-23 00:02 UTC
Labels: status-invalid
