### ISSUE TITLE
Error 20 jailbreaking iPad mini 4

### ISSUE THREAD

**Issue by philipje10** [checkra1n/BugTracker#1357] opened 2020-05-16 20:14 UTC
**Tell us about your setup:**
I tried jailbreaking my iPad mini 4 for the first time using Checkra1n, but an error 20 occured after setting up the jailbreak.

1. What iDevice are you using?
iPad mini 4
2. On what version of iOS is it?
iOs 13.4.1
3. What version of checkra1n are you using?
0.10.1 Beta
4. What is your host system (OS version? Hackintosh? VM? etc.)?
macOS Catalina version 10.15.4
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A to lightning
**What are the steps to reproduce the issue?**
1. I need to put my iPad into safe mode
2. It tries installing but freezes after 5 seconds and after 20 seconds my pc gives me the error 20.
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by adeeb1044** [comment] 2020-05-16 21:09
I tried jailbreaking my iPad mini 4 for the first time using Checkra1n, but an error 20 occured after setting up the jailbreak.

What iDevice are you using?
iPad mini 4
On what version of iOS is it?
iOs 13.4.1
What version of checkra1n are you using?
0.10.1 Beta
What is your host system (OS version? Hackintosh? VM? etc.)?
macOS Catalina version 10.15.4
How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A to lightning
What are the steps to reproduce the issue?
I need to put my iPad into safe mode
It tries installing but freezes after 5 seconds and after 20 seconds my pc gives me the error 20.
...

What do you expect, and what is happening instead?

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?
the error comes again 

Any other info, error logs, screenshots, ...?

**Comment by adeeb1044** [comment] 2020-05-16 21:09
i still having the same problem

**Comment by Siguza** [comment] 2020-05-16 22:07
Duplicate of #1168.

**Closed as completed by Siguza** 2020-05-16 22:07 UTC
Labels: status-duplicate
