### ISSUE TITLE
Safemode option not working. Checkra1n 13.6

### ISSUE THREAD

**Issue by Fiery117** [checkra1n/BugTracker#1638] opened 2020-08-23 09:49 UTC
**Tell us about your setup:**
1. What iDevice are you using?: Iphone 6s
2. On what version of iOS is it?: 13.6
3. What version of checkra1n are you using?: 10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? Mac, 10.13.3
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? :Apple lightning cable, other cables tryed, no difference.

**What are the steps to reproduce the issue?**
1. Jailbreak phone with checkra1n
2. On the checkra1n application on the mac, enable the safe mode option and jailbreak.
3. Unlock phone and you will realize that you are not in safemode and all tweaks are still enabled.
...

**What do you expect, and what is happening instead?**
I would expect to see my tweaks disabled after using the safemode option so that when I have a malicious tweak that puts me into a boot loop I wont have to restore my device. 

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**:
ABSOLUTELY 

**Any other info, error logs, screenshots, ...?**
Information: This can be reproduced. Someone else here on github had the same issue as me and it was closed down so please give me a solution.

**Comment by Siguza** [comment] 2020-09-03 01:17
Duplicate of #1613.

**Closed as completed by Siguza** 2020-09-03 01:17 UTC
Labels: status-duplicate
