### ISSUE TITLE
When will be new checkra1n working with Ipad 3 mini wifi

### ISSUE THREAD

**Issue by bsxx** [checkra1n/BugTracker#1628] opened 2020-08-16 15:08 UTC
Hello,
When will appear new checkra1n working with Ipad mini 3 WiFi with firmware 12.4.8?
thanks for answer

**Comment by demhademha** [comment] 2020-08-16 16:57
Options > allow untested ios versions

**Comment by Siguza** [comment] 2020-08-17 13:43
Gonna go out on a limb here and assume this is a duplicate of #1169.

**Closed as completed by Siguza** 2020-08-17 13:43 UTC
Labels: status-duplicate
