### ISSUE TITLE
Checkra1n.app crashes entering DFU mode

### ISSUE THREAD

**Issue by jnguy3n** [checkra1n/BugTracker#2062] opened 2021-04-28 04:32 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 6s

2. On what version of iOS is it?
14.4.2

3. What version of checkra1n are you using?
0.12.2

4. What is your host system (OS version? Hackintosh? VM? etc.)?
2010 MacBook Pro on Catalina 10.15.7(dosdude1's patch)

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A
**What are the steps to reproduce the issue?**
*for my situation*

I've used checkra1n heaps of time, and a bunch of time with iPhone 6s device.
1. plug the device
2. put device into recovery mode
3. then start the DFU procedure
4. as soon as screen shows entering DFU mode, the app crashes and exits
5. the device will still be in DFU mode
...

**What do you expect, and what is happening instead?**
expecting to jailbreak device instead the app crashes, then exits

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
no, nothing on device, it still remains in DFU mode, but the computer I use to jailbreak device
prints out 

"Segment Fault 11"

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
similar when in verbose mode "-v", I receive "error -26"

**Any other info, error logs, screenshots, ...?**
I used checkra1n in CLI mode. checkra1n -c -v...

[checkra1ncrash.txt](https://github.com/checkra1n/BugTracker/files/6389069/checkra1ncrash.txt)

**Comment by heyhello1** [comment] 2021-04-28 15:29
I have the same issue, pls help!!!!!

**Comment by Siguza** [comment] 2021-04-30 01:04
Duplicate of #2060.

**Closed as completed by Siguza** 2021-04-30 01:04 UTC
Labels: status-duplicate
