### ISSUE TITLE
checkra1n not working on 2018 MacBook

### ISSUE THREAD

**Issue by terrorhorizon** [checkra1n/BugTracker#731] opened 2020-01-13 02:01 UTC
**Tell us about your setup:**
This happens with my iPhone 6 and iPad 6th gen
iPhone 6 has iOS 12.4.4, iPad has 13.3
Currently using GUI
Currently using macOS Catalina. 
Trying to connect via USB C to Lightning cable

My 2018 MacBook is the issue. Being that it only uses USB C, I had to go out and buy a USB C to lightning cable to connect my iOS devices. When trying to use checkra1n, it detects the device and is able to put it into recovery mode, but when trying to enter DFU mode, it just boots right into iOS. When I try the same process on my old 2010 MacBook Pro, everything works just fine. Does checkra1n not like USB C?

**Comment by quilenle** [comment] 2020-01-14 03:33
> Does checkra1n not like USB C?

Yes, it doesn't like USB-C.

**Comment by Siguza** [comment] 2020-01-15 15:07
It's not checkra1n, it's the device. The device needs to detect that a cable is connected in order to enter DFU, and apparently Apple's USB-C to Lightning cables aren't good enough for some reason.  
Using a USB-A cable with an adapter should work.

**Comment by terrorhorizon** [comment] 2020-01-15 15:14
Is there any type of aftermarket cable that may work better? It's not a huge deal, it's just a pain to have to charge up my old MacBook for something my new one should be able to do

**Comment by Siguza** [comment] 2020-01-15 15:19
I don't own any USB-C cables myself, but people here on the bug tracker have been saying in masses that USB-A cable + USB-C adapter worked fine for them.

**Comment by Siguza** [comment] 2020-01-15 17:03
Also I'm gonna go ahead and close this, as the issue is down to hardware.

**Closed as completed by Siguza** 2020-01-15 17:03 UTC
Labels: status-invalid
