### ISSUE TITLE
checkra1n app disappeared after enabling jailbreak after shutting down

### ISSUE THREAD

**Issue by gungurbuz** [checkra1n/BugTracker#1185] opened 2020-04-10 11:23 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iphone 7 plus 128 gb
2. On what version of iOS is it?
ios 13.3.1
3. What version of checkra1n are you using?
i have no idea
4. What is your host system (OS version? Hackintosh? VM? etc.)?
first jailbroken on mac then re enabled on linux ubutu
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
original apple usb-a cable

**What are the steps to reproduce the issue?**
1. jailbreak your phone
2. power down your phone
3.use without enabling for 1 month
4.reenable jailbreak on linux ubuntu

**What do you expect, and what is happening instead?**
checkra1n app disappeared and i cant uninstall jailbreak

**Does the issue also occur if you enable Safe Mode?**

no
**Any other info, error logs, screenshots, ...?**
no
actually never mind just ran checkra1n again and the app is back

**Comment by nergzd723** [comment] 2020-04-10 19:08
If the issue is resolved, close it.

**Closed as completed** 2020-04-11 10:34 UTC
Labels: status-invalid
