### ISSUE TITLE
IPAD AIR 2 usbmuxd -79

### ISSUE THREAD

**Issue by mughal1664** [checkra1n/BugTracker#1944] opened 2021-01-05 14:37 UTC
What iDevice are you using? iPad Air 2 a1567
On what version of iOS is it? 14.3 , 14.0, 14.0
What version of checkra1n are you using? 12.1
What is your host system (OS version? Hackintosh? VM? etc.)? iMac Catalina
How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple lightning
What are the steps to reproduce the issue?
Run checkra1n
Recovery mode successfully
When in DFU mode the pad restarts 2 times with no actions seen, no checkra1n boot logo and commands
...
What do you expect, and what is happening instead?
I expected to see the checkra1n boot loader. Instead i only see apple logo

Did you see a popup on the device stating it entered "Safe Mode" due to an error?
Checkra1n presents an -20 error after it waits endlessly for boot to compleet.
It wont detect successfull jailbreak because none happened.

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?
Yes, I’ve checked all options, none worked
3.
...

**What do you expect, and what is happening instead?**

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Comment by pasha5230** [comment] 2021-01-06 17:09
Welcome.talk about ipad.wifi/cellular.lock/unlock

**Comment by Siguza** [comment] 2021-01-08 23:02
Duplicate of #1880.

**Closed as completed by Siguza** 2021-01-08 23:02 UTC
Labels: status-duplicate
