### ISSUE TITLE
Checkra1n Will close 

### ISSUE THREAD

**Issue by arielech** [checkra1n/BugTracker#8] opened 2019-11-10 13:47 UTC
**What device + iOS version are you on?**
Pad 6 (WiFi) (OS 13.1.2) 

**What are the steps to reproduce the issue?**
1.Install checkra1n 
2. click on app to open 
3. tap on Cydia and the app will close automatically and cydia will not install
...

**What do you expect, and what is happening instead?**
i thought the cydia will install after tapping on it but the app will close and nothing will happen.

**Any other info, error logs, screenshots, ...?**
i restarted my ipad and re-ran the app on my macbook and re ran it again on my ipad and the same thing happened

**Comment by nullpixel** [comment] 2019-11-10 13:49
Hi, I've closed this issue as a duplicate of #2.

**Closed as completed by nullpixel** 2019-11-10 13:49 UTC
Labels: status-duplicate
