### ISSUE TITLE
Iphone 8 ios 13.4 dev beta 4 -20 error

### ISSUE THREAD

**Issue by zaramihnea** [checkra1n/BugTracker#1018] opened 2020-03-08 10:00 UTC
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using? GUI or CLI?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. Iphone 8
2. ios 13.4 dev beta 4
3.GUI
4.mac os catalina not original, it is running on an older device (macbook pro late 2011)
5.usb A, 3rd party cable from hama

**What do you expect, and what is happening instead?**
jailbreaking, its giving me -20 error

**Does the issue also occur if you enable Safe Mode?**
yes

**Any other info, error logs, screenshots, ...?**
its sitting at "right before the trigger" a while and after that it says" Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)"

**Comment by iancbogue** [comment] 2020-03-11 00:52
I am also experiencing this error on iOS 13.3.1 on my iPhone 8 Plus. Running Catalina on MacBook7,1 with Catalina Patcher, if that makes a difference. GUI version 0.9.8.2. Also using a 3rd Party (AmazonBasics) USB A to Lightning cable. Occurs with Safe Mode enabled.

**Comment by AMDBartek** [comment] 2020-03-13 18:31
This is a known issue. #984

**Comment by Siguza** [comment] 2020-03-23 05:24
Duplicate of #877.

**Closed as completed by Siguza** 2020-03-23 05:24 UTC
Labels: status-duplicate
