### ISSUE TITLE
Oddyesyra1n messing jailbreak experiance up

### ISSUE THREAD

**Issue by EasonJiangOfficial** [checkra1n/BugTracker#1843] opened 2020-11-13 21:21 UTC
Im on Ios 14.2 with iphone 6s plus and when I used to use version 11 of Checkra1n i used oddyesyra1n but i forgot to rootfs and now when i jailbreak, the checkra1n app and other jailbreak apps like cydia wont show up unless i change the language or respring,someone told me it was because of my preferance files,i was wondering if I could reset them somehow.

**Comment by Siguza** [comment] 2020-11-16 07:31
You don't need to post the same issue multiple times. Dupe of #1835.

**Closed as completed by Siguza** 2020-11-16 07:31 UTC
Labels: status-duplicate
