### ISSUE TITLE
Device fails to enter dfu mode

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#1346] opened 2020-05-13 04:51 UTC
**Tell us about your setup:**
1. What iDevice are you using? iPod touch 6th generation
2. On what version of iOS is it? 12.4.6
3. What version of checkra1n are you using? 0.10.1 beta
4. What is your host system (OS version? Hackintosh? VM? etc.)? macOS Catalina 10.15.3
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-C

**What are the steps to reproduce the issue?**
1. Press start>Next in Checkra1n
2. Click Start
3. Press home button and top button for 4 seconds, then release top button and press home button for 10 seconds.
...

**What do you expect, and what is happening instead?**
I expect the jailbreak to install, but instead it shows that the device failed to enter DFU mode

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**

**Comment by memoasiri07** [comment] 2020-05-14 08:22
> **Tell us about your setup:**
> 
> 1. What iDevice are you using? iPod touch 6th generation
> 2. On what version of iOS is it? 12.4.6
> 3. What version of checkra1n are you using? 0.10.1 beta
> 4. What is your host system (OS version? Hackintosh? VM? etc.)? macOS Catalina 10.15.3
> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-C
> 
> **What are the steps to reproduce the issue?**
> 
> 1. Press start>Next in Checkra1n
> 2. Click Start
> 3. Press home button and top button for 4 seconds, then release top button and press home button for 10 seconds.
>    ...
> 
> **What do you expect, and what is happening instead?**
> I expect the jailbreak to install, but instead it shows that the device failed to enter DFU mode
> 
> **Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
> Yes
> 
> **Any other info, error logs, screenshots, ...?**

**Comment by memoasiri07** [comment] 2020-05-14 08:23
Duplicate of #

> **Tell us about your setup:**
> 
> 1. What iDevice are you using? iPod touch 6th generation
> 2. On what version of iOS is it? 12.4.6
> 3. What version of checkra1n are you using? 0.10.1 beta
> 4. What is your host system (OS version? Hackintosh? VM? etc.)? macOS Catalina 10.15.3
> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-C
> 
> **What are the steps to reproduce the issue?**
> 
> 1. Press start>Next in Checkra1n
> 2. Click Start
> 3. Press home button and top button for 4 seconds, then release top button and press home button for 10 seconds.
>    ...
> 
> **What do you expect, and what is happening instead?**
> I expect the jailbreak to install, but instead it shows that the device failed to enter DFU mode
> 
> **Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
> Yes
> 
> **Any other info, error logs, screenshots, ...?**

[https://github.com/checkra1n/BugTracker/issues/1346#issue-617139174]()

**Comment by Siguza** [comment] 2020-05-16 05:28
Apple's USB-C cables are known to not work, and there's nothing we can do about that. See #1 for more info.

**Closed as completed by Siguza** 2020-05-16 05:28 UTC
Labels: status-invalid
