### ISSUE TITLE
Big Sur doesnt work

### ISSUE THREAD

**Issue by DumbGameMaker** [checkra1n/BugTracker#1917] opened 2020-12-27 22:57 UTC
**Tell us about your setup:**
1. What iDevice are you using? SE 1st Gen
2. On what version of iOS is it? the rare 13.6.1
3. What version of checkra1n are you using? 0.12.1 and 0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)? Big Sur on an M1 mac
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? apple cable through USB-A hub connected to a USB-C port

**What are the steps to reproduce the issue?**
1. try to checkra1n
2. fail
3. look up problem
4. find dead ends
5. make an issue
6. wait for someone to reply
7. 
...

**What do you expect, and what is happening instead?**
it is stuck on 'waiting for DFU devices' it goes into DFU and Recovery mode fine.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
nope

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
not sure

**Any other info, error logs, screenshots, ...?**
no

**Comment by Siguza** [comment] 2020-12-28 17:00
Duplicate of #1862.

**Closed as completed by Siguza** 2020-12-28 17:00 UTC
Labels: status-duplicate
