### ISSUE TITLE
pangooOS error

### ISSUE THREAD

**Issue by GiuCrox** [checkra1n/BugTracker#2162] opened 2021-08-06 15:28 UTC
For various reasons I used Checkra1n on this iPhone 7 and after the first success, the phone restarts and goes into recovery and does not go beyond the Apple logo.

<a href="https://ibb.co/ZStKbnF"><img src="https://i.ibb.co/sCkQX0N/aaaaa.jpg" alt="aaaaa" border="0"></a>

**Comment by Siguza** [comment] 2021-08-07 00:30
Duplicate of #2160, and still not a valid bug report.

**Closed as completed by Siguza** 2021-08-07 00:30 UTC
Labels: status-invalid
