### ISSUE TITLE
Stuck for minutes on heap spray then restarts normally

### ISSUE THREAD

**Issue by zoomer555** [checkra1n/BugTracker#1164] opened 2020-04-09 02:26 UTC
**Tell us about your setup:**
1. What iDevice are you using? iPhone 5s global (not jailbroken before)
2. On what version of iOS is it? 12.4.4
3. What version of checkra1n are you using? 0.10.1 cli and gui
4. What is your host system (OS version? Hackintosh? VM? etc.)? ubuntu
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A 3rd party apple cable.

**What are the steps to reproduce the issue?**
1. Run checkra1n on gui or cli
2. Put phone to DFU
3. Wait for all done
...

**What do you expect, and what is happening instead?**
I expect a successful jailbreak because the A7 support was patched but mine still has this issue, it gets stuck for a few minutes on the heap spray process, right before trigger displays for a few seconds then just restarts normally

**Does the issue also occur if you enable Safe Mode?**
Yes.

**Any other info, error logs, screenshots, ...?**
![IMG_20200409_101621](https://user-images.githubusercontent.com/60062098/78851348-267c3980-7a4c-11ea-8a32-fb5c3d332fd1.jpg)
![IMG_20200409_101621](https://user-images.githubusercontent.com/60062098/78851502-7f4bd200-7a4c-11ea-9342-c6b2a8788a8f.jpg)

![IMG_20200409_101632](https://user-images.githubusercontent.com/60062098/78851377-3ac03680-7a4c-11ea-95c9-7e5a84236a06.jpg)
![IMG_20200409_101639](https://user-images.githubusercontent.com/60062098/78851387-401d8100-7a4c-11ea-96c0-699a20e2b4cb.jpg)

**Comment by zoomer555** [comment] 2020-04-09 11:23
if i use CLI this happens
![Screenshot from 2020-02-05 19-11-46](https://user-images.githubusercontent.com/60062098/78890134-a67bc100-7a97-11ea-9b5c-0cf2ee363dc8.png)

**Comment by zoomer555** [comment] 2020-04-09 11:24
In CLI this happens: 
![Screenshot from 2020-04-09 19-24-35](https://user-images.githubusercontent.com/60062098/78890212-cad79d80-7a97-11ea-8669-68991271361d.png)

**Comment by nergzd723** [comment] 2020-04-09 12:44
Duplicate of #1169, use a workaround

**Comment by zoomer555** [comment] 2020-04-09 13:37
It doesn't get stuck on right before trigger bro. Its on heap spray for a long time then right before trigger appears for seconds then my phone reboots normally.

**Comment by nergzd723** [comment] 2020-04-09 16:50
> It doesn't get stuck on right before trigger bro. Its on heap spray for a long time then right before trigger appears for seconds then my phone reboots normally.

That's almost the same issue with usbfs(if it stays on heap spraying for a while)
So yes, the same bug, the same issue, dup of #1169

**Closed as completed** 2020-04-09 23:20 UTC
Labels: status-duplicate
