### ISSUE TITLE
ios 15 support

### ISSUE THREAD

**Issue by Grandboy46** [checkra1n/BugTracker#2187] opened 2021-09-22 18:52 UTC
Hi @Siguza,

I heard that checkra1n does not work on ios 15. Can you please add support for ios 15 or give more information about ios 15 support?

Sincerely,

**Comment by Gerriarob** [comment] 2021-09-25 19:31
No, it works.

**Comment by Grandboy46** [comment] 2021-09-26 05:51
> No, it works.

https://github.com/checkra1n/BugTracker/issues/2187#issuecomment-927172449

**Comment by Gerriarob** [comment] 2021-09-26 11:40
Have it working on two iPad 6 gen and 1 iPhone 7. iOS 15 and checkra1n

**Comment by Siguza** [comment] 2021-09-26 14:00
Duplicate of #2124.  
Already being worked on.

**Closed by Siguza** 2021-09-26 14:00 UTC
