### ISSUE TITLE
Checkra1n Loader crash when trying to install Cydia.

### ISSUE THREAD

**Issue by lgcrml** [checkra1n/BugTracker#30] opened 2019-11-10 14:25 UTC
**What device + iOS version are you on?**
iPad Pro 2nd generation (10.5-inch) 
iOS 13.2.2

**What are the steps to reproduce the issue?**
1. Run the Checkra1n Loader
2. Under "Install" tap "Cydia".
3. Checkra1n Loader will crash.
...

**What do you expect, and what is happening instead?**
I expect it to bring up an options menu that says "Install" and "Cancel". 
What happens is that Loader crashes.

**Any other info, error logs, screenshots, ...?**
Other info: N/A
Error Logs: N/A
Screenshots: N/A

**Comment by nullpixel** [comment] 2019-11-10 14:27
Hi, I've closed this issue as a duplicate of #2.

**Closed as completed by nullpixel** 2019-11-10 14:27 UTC
Labels: status-duplicate
