### ISSUE TITLE
Restorefs 

### ISSUE THREAD

**Issue by bluegreen19** [checkra1n/BugTracker#186] opened 2019-11-11 16:49 UTC
When I restorefs from Checkra1n app it removes all the tweaks but it doesn’t remove apps like cydia apps like cydia , iCleaner, filza

**Comment by alessaba** [comment] 2019-11-11 18:09
Issue #1 already says that

**Comment by nullpixel** [comment] 2019-11-11 18:28
dupe of #128

**Closed as completed by nullpixel** 2019-11-11 18:28 UTC
Labels: status-duplicate
