### ISSUE TITLE
If English is not set, "Segmentation fault: 11" will occur.

### ISSUE THREAD

**Issue by ichitaso** [checkra1n/BugTracker#52] opened 2019-11-10 15:42 UTC
**What device + iOS version are you on?**
All version

**What are the steps to reproduce the issue?**
You must set your Mac language environment to English.

**What do you expect, and what is happening instead?**
Segmentation fault: 11

**Any other info, error logs, screenshots, ...?**

![iOS13-jailbreak-tool-checkra1n-05](https://user-images.githubusercontent.com/980215/68546645-fdfbff00-041b-11ea-8c86-e92e8999fb15.jpg)

**Comment by ThisIsAccount** [comment] 2019-11-10 16:19
This error might only occur when the system language is Japanese

**Comment by nullpixel** [comment] 2019-11-10 16:38
Closing as a dupe of #22.

**Closed as completed by nullpixel** 2019-11-10 16:38 UTC
Labels: status-duplicate
