### ISSUE TITLE
DFU sync upload fail iPad mini 2

### ISSUE THREAD

**Issue by Silverwarriorin** [checkra1n/BugTracker#1284] opened 2020-04-27 23:06 UTC
Tell us about your setup:

What iDevice are you using?
iPad Mini 2
On what version of iOS is it?
12.4.6
What version of checkra1n are you using?
0.10.1
What is your host system (OS version? Hackintosh? VM? etc.)?
linux
How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A Apple
What are the steps to reproduce the issue?
Install Checkra1n, run it with args -Vvc
What do you expect, and what is happening instead?
Jailbreak works, but it doesn't

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?
Still doesn't work

Sorry I don't have a screenshot.

**Comment by nergzd723** [comment] 2020-04-30 12:33
Duplicate of #1169

**Comment by Siguza** [comment] 2020-05-03 04:51
Indeed a dupe.

**Closed as completed by Siguza** 2020-05-03 04:51 UTC
Labels: status-duplicate
