### ISSUE TITLE
error -79. Ipad 5th ios 14

### ISSUE THREAD

**Issue by mmm286** [checkra1n/BugTracker#1712] opened 2020-09-28 09:49 UTC
**Tell us about your setup:**
1. Ipad 5th
2. IOS 14.0
3. Latest Beta
4. Ubuntu 18
5. Original cable

Always gimes error:

**USBMUX Error (Error code: -79)**

Any help please? 
Thanks

![IMG-7692](https://user-images.githubusercontent.com/5803612/94422541-8e077c00-0187-11eb-81eb-8de11343ec63.jpg)

![IMG-7689](https://user-images.githubusercontent.com/5803612/94422285-27825e00-0187-11eb-994e-000d7f9121de.JPG)

**Comment by jazzmaxx** [comment] 2020-09-30 07:48
I got the same issue on an iPad Pro 1st gen. Using Linux Mint, various USB boot sticks, always USBMUX error -79 comes up. I suspect that checkra1n 0.11.0 does not run on an A9X device even though it was announced to be compatible and tested with A9X. I hope there will be a fix soon.

**Comment by n0k0m3** [comment] 2020-10-01 02:10
Same issue as (many people in here) #1692

**Comment by ShawnTimez** [comment] 2020-10-04 05:09
I have the exact same issue ios 14.0.1 ipad 5th gen A9 processor. Its an issue with usbmux trust because the device is likely locked or icloud locked. Im convinced its an issue with checkra1n and not hardware related. I see Mac users having the same issue error -20 timeout same reason

**Comment by Siguza** [comment] 2020-10-04 19:25
Dupe of #1689.

**Closed as completed by Siguza** 2020-10-04 19:25 UTC
Labels: status-duplicate

**Comment by immivip** [comment] 2020-10-14 19:13
same issue

**Comment by WakaBlazer** [comment] 2020-10-31 08:09
My iPad Pro A9X processor on Linux gave me error code -77 and -79 
And on Mac gave me error code 22 
They lied about iPad OS 14 being able to be jailbroken by Checkra1n 0.11.0

**Comment by galmoham** [comment] 2020-10-31 12:12
Had the same issues with ipadpro 1st generation on iso 14. Was luck 13.×× was still being signed and I quickly downgraded
