### ISSUE TITLE
jailbreak checkrain

### ISSUE THREAD

**Issue by Gulahmad1997** [checkra1n/BugTracker#2033] opened 2021-03-14 10:58 UTC
**Tell us about your setup:** jailbreak
1. What iDevice are you using? ipad air 2 A1567
2. On what version of iOS is it? ios 14.4
3. What version of checkra1n are you using? 0.12.2 and also lower version and patched versions all failed
4. What is your host system (OS version? Hackintosh? VM? etc.)? mac os high sierra
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? apple usb A

**What are the steps to reproduce the issue?** 
1. 
2. 
3.
...

**What do you expect, and what is happening instead?** no boot logo from checkrain

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?** no

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?** yes

**Any other info, error logs, screenshots, ...?** error -20
cant jailbreak ipad air 2 on ios 14.4
info
ipad air 2 cellular
model A1567
ITS Apple A8X triple
all checkrain official and patched versions failed to jailbreak
on latest checkrain 0.12.2 no checkrain loader logo only apple logo hangs a minuts and reboots back normal mode
and activation locked restored mode same problem

**Comment by Siguza** [comment] 2021-04-30 02:01
Duplicate of #1880.

**Closed as completed by Siguza** 2021-04-30 02:01 UTC
Labels: status-duplicate
