### ISSUE TITLE
Error -20 13.4.1 

### ISSUE THREAD

**Issue by blaxahmoney** [checkra1n/BugTracker#1459] opened 2020-06-10 18:33 UTC
**Tell us about your setup:**
1. What iDevice are you using?
IPhone X 
2. On what version of iOS is it?
13.4.1
3. What version of checkra1n are you using?
10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Mac OS Catalina 10.15
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? 
USB A 
Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. The iPhone boots up regularly without being jailbroken after failing with the -20 error code.
2. I have booted in safe mode and boots up but when I reboot and try jailbreak it now boots up in safe mode 
3. I’ve tried another Mac with new install of checkra1n and get the same issue boots up in safe mode 

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes 

**Any other info, error logs, screenshots, ...?**
No

**Comment by Siguza** [comment] 2020-06-21 06:54
Sounds like a dupe of #1449.

**Closed as completed by Siguza** 2020-06-21 06:54 UTC
Labels: status-duplicate
