### ISSUE TITLE
I'm always stuck "Right before trigger (this is the real bug setup)"

### ISSUE THREAD

**Issue by anggoro-farida** [checkra1n/BugTracker#1548] opened 2020-07-10 07:11 UTC
**Tell us about your setup:**
1. What iDevice are you using? (iPhone 5s)
2. On what version of iOS is it? (iOS 12.4.7)
3. What version of checkra1n are you using? (beta 0.10.2)
4. What is your host system (OS version? Hackintosh? VM? etc.)? (elementary OS 5.1)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
(Connector Cable USB-A and My Connector Computer USB 3.0)

**What are the steps to reproduce the issue?**
1. Install checkra1n refer on website for ubuntu
2. run checkra1n with GUI or CLI (sudo checkra1n -c -v -V -s)
3. always stuck in "Right before trigger" GUI mode and in CLI with verbose stuck in "Checkm8 Trigger stage"
...

**What do you expect, and what is happening instead?**
I expect can run successful like on mac, but in most I do more linux distro always stuck

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes, I run on safe mode always stuck in "Right before trigger"

**Any other info, error logs, screenshots, ...?**
![Screenshot from 2020-07-10 14-10-34](https://user-images.githubusercontent.com/60379763/87126907-360f5680-c2b7-11ea-91ed-1fc7e3fe98db.png)

**Comment by Siguza** [comment] 2020-07-10 13:24
Duplicate of #1169.

**Closed as completed by Siguza** 2020-07-10 13:24 UTC
Labels: status-duplicate
