### ISSUE TITLE
Cydia is not opening

### ISSUE THREAD

**Issue by innocent-slime** [checkra1n/BugTracker#1735] opened 2020-10-04 19:29 UTC
**Tell us about your setup:**
1. What iDevice are you using?IpadAir 2
2. On what version of iOS is it? ios 14
3. What version of checkra1n are you using? 0.11.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?linux
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?apple cable

**What are the steps to reproduce the issue?**
1. I jailbreaked my device using an linux with checkrain
2. I hit the download button inside of the checkrain for the cydla
3.it crashed and never opened again even when i try to open it 
...

**What do you expect, and what is happening instead?**i expect to have an openable cydia but its not opening

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**yes

**Any other info, error logs, screenshots, ...?**note:when i click to cydia it opens it , it starts the loading screen but then it crash and close the cydia automaticaly

**Comment by Siguza** [comment] 2020-10-04 19:34
Duplicate of #1687.

**Closed as completed by Siguza** 2020-10-04 19:34 UTC
Labels: status-duplicate
