### ISSUE TITLE
iPad mini 3 jailbreak not working 

### ISSUE THREAD

**Issue by Nico239SF** [checkra1n/BugTracker#974] opened 2020-02-27 15:06 UTC
**Tell us about your setup:**
1. What iDevice are you using? iPad mini 3
2. On what version of iOS is it? 12.4.5
3. What version of checkra1n are you using? GUI or CLI? CLI
4. What is your host system (OS version? Hackintosh? VM? etc.)? Real PC, Bootra1n
5. How are you connecting to the Device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A with Apple original cable. 

**What are the steps to reproduce the issue?**
1. All starts normally
2. After 50 seconds “right before trigger” appears
3. After 2 minutes appears “[369.843503] INFO: task checkra1n:1279 blocked for more than 122 seconds

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
![image](https://user-images.githubusercontent.com/57403036/75456495-e3be4080-597a-11ea-9fb9-17636402e143.jpg)

**Comment by griboedov13** [comment] 2020-02-27 16:58
I have exactly the same error on the iPad mini 3. All actions performed by me and the characteristics of the hardware are identical to Nico239SF.

**Comment by AMDBartek** [comment] 2020-03-13 18:42
This is a known issue. #984

**Comment by Siguza** [comment] 2020-03-21 05:39
Marking this as duplicate of #984 (this issue is older, but the other one is more generic and thoroughly documented).

**Closed as completed by Siguza** 2020-03-21 05:39 UTC
Labels: status-duplicate
