### ISSUE TITLE
Linux checkra1n 0.9.8 to 0.9.8.2 A7 Device Issue, iPhone 5S (Can't Jailbreak)

### ISSUE THREAD

**Issue by sukualam** [checkra1n/BugTracker#1056] opened 2020-03-15 13:17 UTC
checkra1n (beta) 0.9.8.X (linux) still not working yet for my A7 device..

(LINUX, amd64)
checkra1n (beta) 0.9.8 (first linux version) -> stuck at "right before trigger"
but when i unplug device while stuck at "right before trigger" , it show checkra1n credit on my iphone screen but just hang there

checkra1n (beta) 0.9.8.1 -> still stuck at "right before trigger"
but when i unplug device while it "stuck", it just stuck, and nothing happened. and i had to hard reset (Power +home button)

checkra1n (beta) 0.9.8.2 -> still same, stuck at "right before trigger"
and still, stuck there ...

(MACOS)
checkra1n (beta) 0.9.7 (macos) just working fine for my A7 devices.. (cli mode)
checkra1n (beta) 0.9.8.x -> not tried yet, but i think it will run without problem..

My A7 Device is iPhone 5S (GSM)

Why im not using mac? my mac broken..

**What are the steps to reproduce the issue?**
1. run linux distro (i tried live and dualboot)
2. run checkra1n 0.9.8.x (0.9.8.2 now)
3. put iphone in DFU mode, then connect cable to PC, then jelbrek.. ( sudo ./checkra1n -c )
4. jailbreak process shown in terminal, and then... BANG! stuck at right before trigger... (i wait up to 5 minute and just stuck like that)
5. finally i just hard reset (Power + home button)
6. boot normally (no jailbreak)
...

**What do you expect, and what is happening instead?**

jailbreak with success, like when using mac os version

**Does the issue also occur if you enable Safe Mode?**

i even can't pass jailbreak process first

**Any other info, error logs, screenshots, ...?**

DFUSync Error...

**Comment by 141** [comment] 2020-03-16 01:41
I don't have a mac or access to a mac, no emulators or hackintosh work on any of the computers I have access to as well. So I'm in the exact same situation. It seems it relies on a faulty USB host, that many chipsets don't have the fault.

**Comment by AMDBartek** [comment] 2020-03-16 11:35
This is a known issue and it is nothing to do with the USB controller. #984 #1053

**Comment by Siguza** [comment] 2020-03-21 05:42
Marking this as duplicate of #984.

**Closed as completed by Siguza** 2020-03-21 05:42 UTC
Labels: status-duplicate
