### ISSUE TITLE
same issue since 0.9.3 iPad 6th gen still not booting even after updating to 0.9.5...

### ISSUE THREAD

**Issue by chevy4lifeee** [checkra1n/BugTracker#401] opened 2019-11-16 03:16 UTC
**What device + iOS version are you on?**
iPad 6th gen iOS 13.2.2 reverted from 13.3 beta 

**What checkra1n version are you using?**
0.9.3-0.9.5

**Comment by littlelailo** [comment] 2019-11-16 13:25
Duplicate of #393

**Closed as completed by littlelailo** 2019-11-16 13:25 UTC
Labels: status-duplicate
