### ISSUE TITLE
Unable to enter DFU Mode with a USB-C Cable on MBP 2018

### ISSUE THREAD

**Issue by robsee** [checkra1n/BugTracker#69] opened 2019-11-10 16:49 UTC
**What device + iOS version are you on?**
13.2

**What are the steps to reproduce the issue?**
1. Plug USB-C -> Lightning cable into Macbook Pro 2018
2. Following instructions exactly, don't ever get into DFU Mode
3. Use USB-C to USB-A adapter with USB-A to lightning cable, get into DFU mode on the first try
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**
I used 2 different Apple USB-C to lightning cables that would not work for DFU mode

**Comment by robsee** [comment] 2019-11-10 16:51
Obviously I'm not expecting you to fix this, just wanted to provide some info

**Comment by nullpixel** [comment] 2019-11-10 16:51
Hi, this likely isn't an issue with your cable, and it's not checkra1n causing this issue. How are you entering DFU mode?

**Comment by robsee** [comment] 2019-11-10 16:52
I'm following exactly what checkra1n told me to do. I did it 20 times on a couple of different devices without success. I switch to the adapter and USB-A to lightning cable, and it worked on the first try

**Comment by robsee** [comment] 2019-11-10 16:56
My iOS device that I was having the big problems with was an iPad Pro 2017. I was able to get it in to DFU mode on an iPhone 8 with USB-C to lightning cable once, but had errors during the checkra1n boot/install.

**Comment by nullpixel** [comment] 2019-11-10 17:04
Yeah it's probably related to #12. Closing as a dupe of that

**Closed as completed by nullpixel** 2019-11-10 17:04 UTC
Labels: status-duplicate

**Comment by arguiot** [comment] 2019-11-10 21:41
I can confirm with an iPhone 7, USB-C cable aren't working

**Comment by zhtengw** [comment] 2019-11-11 12:45
With iPhone SE, USB-C cable not work too. But USB-A cable works fine.

**Comment by MaxLeiter** [comment] 2019-11-12 00:52
I was able to mitigate this by entering DFU without being plugged in, then plugging in and running checkra1n.

**Comment by adhip94** [comment] 2022-02-13 14:36
@MaxLeiter Looks like the latest checkra1n app doesnt detect the phone in DFU mode.

**Comment by Mengshi12138** [comment] 2025-09-12 06:09
I haven never tried to use USB-A to downgrade my iphone7. Will try later
