### ISSUE TITLE
Error getting passcode state parsing error pls help 

### ISSUE THREAD

**Issue by YahmoStudio** [checkra1n/BugTracker#1956] opened 2021-01-14 16:16 UTC
Hey i want to jailbreak my IPhone x GSM IOS 14.3 phone and evertime i try it this message come
![Screenshot from 2021-01-14 16-16-49](https://user-images.githubusercontent.com/64530630/104617895-ebb2cc00-5683-11eb-86f8-44b9fc3d405e.png)

**Comment by Siguza** [comment] 2021-01-18 03:45
Duplicate of #1941.

**Closed as completed by Siguza** 2021-01-18 03:45 UTC
Labels: status-duplicate
