### ISSUE TITLE
Apple Pencil lagging iOS13.2.3

### ISSUE THREAD

**Issue by photry** [checkra1n/BugTracker#661] opened 2019-12-21 03:21 UTC
I observe such lagging with Note Apps and Proceate. The Pencil works well in Safe Mode. Is there anything with substrate?

**Comment by Siguza** [comment] 2019-12-21 04:08
If it works fine in Safe Mode, the issue is either with Substrate or a tweak. Best I can recommend is installing iCleaner and selectively disabling tweak dylibs until you find the culprit.  
Gonna close this issue now as it's not caused by checkra1n directly.

**Closed as completed by Siguza** 2019-12-21 04:08 UTC
Labels: status-invalid

**Comment by photry** [comment] 2019-12-21 04:21
Thanks.
