### ISSUE TITLE
error 31 on checkra1n

### ISSUE THREAD

**Issue by SAWdev1** [checkra1n/BugTracker#2117] opened 2021-06-02 03:58 UTC
hi i have this error with checra1n am trying to restore my ipad air (wifi) but i cant solve the 31 error i really tried and didnt sleep for to days please help me to solve this problame am on kali linux and usnig checkra1n version 12.4 
PLEASE P L E A S E help me

**Comment by Bukow8** [comment] 2021-06-02 21:18
I get this 31 error too with my iphone se 1 gen on ios 14.4

**Comment by Siguza** [comment] 2021-07-05 15:04
Duplicate of #1169.

**Closed as completed by Siguza** 2021-07-05 15:04 UTC
Labels: status-duplicate
