### ISSUE TITLE
iPhone 8 GSM

### ISSUE THREAD

**Issue by polero106** [checkra1n/BugTracker#1874] opened 2020-11-25 19:23 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 8 GSM
2. On what version of iOS is it?
IOS 12
3. What version of checkra1n are you using?
iOS 14.2 (18B92)
4. What is your host system (OS version? Hackintosh? VM? etc.)
Linux Ubuntu
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple cable type A

**What are the steps to reproduce the issue?**
1. When I open checkra1n it's says that iphone 8 GSM with this version is not supported, I have tried to change the version but it won't work
2. 
3.
...

**What do you expect, and what is happening instead?**
I expect to be able to be able to bypass

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment] 2020-11-27 02:03
Duplicate of #1823.

**Closed as completed by Siguza** 2020-11-27 02:03 UTC
Labels: status-duplicate
