### ISSUE TITLE
Restored via 'Restore System' in Checkra1n but iOS apps still detect a jailbroken device

### ISSUE THREAD

**Issue by hengerr** [checkra1n/BugTracker#279] opened 2019-11-13 12:25 UTC
**What device + iOS version are you on?**
iPhone X (GSM) + iOS 13.2.2

**What checkra1n version are you using?**
checkra1n 0.9.2

**What are the steps to reproduce the issue?**
1. Download OCBC app from app store (https://apps.apple.com/sg/app/ocbc-sg-mobile-banking/id292506828) (this is the app that is still detecting a jailbroken device even after restoring the system via checkra1n)
2. Restore system via Checkra1n
3. OCBC app still detects jailbroken device (not just this app, other apps too)

**What do you expect, and what is happening instead?**
I expected the system to be restored to a unjailbroken state but it seems like it didn't?

**Any other info, error logs, screenshots, ...?**
No screenshots sorry

**Comment by vismittu** [comment] 2019-11-13 15:31
Try resetting your device and data, this will fix your issue.

**Comment by hengerr** [comment] 2019-11-13 15:38
you mean under settings app --> General --> Reset --> Reset all Settings?

**Comment by vismittu** [comment] 2019-11-13 16:13
I mean reset all data and settings. Dont restore from any backup taken after the device was jailbroken.

**Comment by hengerr** [comment] 2019-11-13 16:18
I see. I’m aware of the restore option but specifically I was under the impression that the option to ‘Restore System’ in checkra1n was to restore it to a unjailbroken state. And so, as I described above, that doesn’t seem to be the case, thus I submitted this issue. But thanks for your help anyway!

**Comment by vismittu** [comment] 2019-11-13 16:29
It does restore to unjailbroken state but some traces remain through the os that won’t leave untile you restore your phone completely. This happens in all jailbreaks, not just checkra1n.

**Comment by Shadowedstalker** [comment] 2019-11-13 17:10
I have had success with Liberty Lite via Cydia in stopping apps from detecting the jailbreak.

**Comment by vismittu** [comment] 2019-11-13 18:26
That’ll do the trick but if you don’t want a jailbreak, you need to reset your device totally.

**Comment by hengerr** [comment] 2019-11-14 01:56
> It does restore to unjailbroken state but some traces remain through the os that won’t leave untile you restore your phone completely. This happens in all jailbreaks, not just checkra1n.

I may be wrong since I'm still quite new to this 'Restore rootfs' thing, but I tried it first in unc0ver on my iPhone 6 Plus and it removed the jailbreak and my apps don't detect the jailbroken state anymore.

So I guess that's why I was expecting this 'Restore System' option in Checkra1n to function in a similar way.

**Comment by hengerr** [comment] 2019-11-14 01:57
> I have had success with Liberty Lite via Cydia in stopping apps from detecting the jailbreak.

Same here, but it didn't work for the banking app I listed above, and that's why I wanted to remove the jailbreak completely to allow it to function again.

**Comment by hengerr** [comment] 2019-11-14 01:58
> That’ll do the trick but if you don’t want a jailbreak, you need to reset your device totally.

I understand this, I've actually used the 'Set up as new' option in iTunes when I first got my iPhone X, but I was hoping that this is a bug and the checkra1n team can find a way to fix/find a way to make it work. Thanks for your help though.

**Comment by Shadowedstalker** [comment] 2019-11-14 02:21
It's not a bug, I know the net says "restore  wipes all traces of jailbreak" but this simple is not true. Anyone that has jailbroken a device and then updated and jailbroke it again can verify that when you install tweaks from Cydia all your previous setting take effect again automatically. Have you tried Flex 3? or Break Through?

**Comment by Shadowedstalker** [comment] 2019-11-14 02:28
Though I have no connection to this bank, I am downloading the app to help investigate it.

**Comment by hengerr** [comment] 2019-11-14 02:31
> Though I have no connection to this bank, I am downloading the app to help investigate it.

Hey that’s really nice of you! I’ve downloaded Liberty Lite (Beta) and so far the jailbreak detection message hasn’t pop up yet. However, due to the first few times I tried to log in while running Liberty Lite yesterday, I think I’ve managed to lock myself out of my bank account.

I’ll visit the bank branch later and attempt to use the app as per normal after. Will update here if it works, thanks!

**Comment by Shadowedstalker** [comment] 2019-11-14 02:34
![IMG_0858](https://user-images.githubusercontent.com/41554466/68821806-47875c80-065d-11ea-92de-461ebd1345f6.PNG)
first

![IMG_0859](https://user-images.githubusercontent.com/41554466/68821815-4f470100-065d-11ea-8028-b5316d3ea0b7.PNG)
Second

![IMG_0860](https://user-images.githubusercontent.com/41554466/68821826-54a44b80-065d-11ea-9b0c-b2d2db00db65.PNG)
Third

![IMG_0861](https://user-images.githubusercontent.com/41554466/68821832-5bcb5980-065d-11ea-8634-117ab3746faa.PNG)
result I can access the app without a problem.

**Comment by hengerr** [comment] 2019-11-14 08:51
I've visited the bank and they said that the app will only accept a physical token for authentication when it detects the device is in a jailbroken state, I had been using the electronic token in the app that utilizes Face ID, but they said it won't work as long as the app detects the device is in a jailbroken state. No idea why it won't work now that Liberty Lite (Beta) is blocking the detection though. Thanks for taking the time to look at the app for me too!

**Comment by Shadowedstalker** [comment] 2019-11-14 17:26
Yeah that's a bit odd, as you see from the pictures I had no problems. Granted I cannot log in as I have no connection to the bank.

**Comment by Siguza** [comment] 2019-12-04 03:22
checkra1n's restore option only restores the system partition, everything on `/var` is left untouched. This is the intended behaviour and would also happen if you restored an IPSW with iTunes, so I'm gonna have to close this as "won't fix". :/

**Closed as completed by Siguza** 2019-12-04 03:22 UTC
Labels: status-wontfix

**Comment by dumo** [comment] 2020-01-25 15:48
i have the same issue, when i use unc0ver on my iPhone 7 and it removed the jailbreak and my apps don't detect the jailbroken state anymore. 
After "restore system", I try OTA to ios 13.3.1, some apps still detect the jailbroken state.

**Comment by dumo** [comment] 2020-01-26 03:01
> checkra1n's restore option only restores the system partition, everything on `/var` is left untouched. This is the intended behaviour and would also happen if you restored an IPSW with iTunes, so I'm gonna have to close this as "won't fix". :/

please think twice, we do not want to lose data.

**Comment by RamonBeast** [comment] 2020-01-28 14:43
I have the same problem, banking apps not working anymore even after a full restore, which is surprising as my backup was taken moments before trying checkra1n.

Is there a list of artefacts we can remove manually to bring the phone back to a state in which it doesn't look jailbroken even after removing checkra1n?

**Comment by hirakujira** [comment] 2020-02-09 20:07
Yeah, some apps detects `/var` modification of devices which was jailbroken before.
And I found a way to fix this, which works for my bank app.

First, backup your device with iTunes / Finder (macOS Catalina), then just open Settings > General > Reset and click "Erase All Content and Settings”. After that, restore device backup and it will fix jailbreak detection issue for these apps.
