### ISSUE TITLE
Checkra1n app crashes

### ISSUE THREAD

**Issue by Akalias01** [checkra1n/BugTracker#56] opened 2019-11-10 15:57 UTC
**What device + iOS version are you on?**
iPad 6, cellular 

**What are the steps to reproduce the issue?**
1. Open Checkra1n app, iOS 13.2
2. Select install Cydia
3.
...

**What do you expect, and what is happening instead?**
Cydia app should install. Instead Checkra1n app closes

**Any other info, error logs, screenshots, ...?**

**Comment by nullpixel** [comment] 2019-11-10 15:59
Hi, I've closed this issue as a duplicate of #2.

**Closed as completed by nullpixel** 2019-11-10 15:59 UTC
Labels: status-duplicate
