### ISSUE TITLE
ios 14.3 iphone 7 error code :- 20 checkra1n 

### ISSUE THREAD

**Issue by rajencha** [checkra1n/BugTracker#1923] opened 2020-12-30 09:39 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iphone 7
2. On what version of iOS is it?
14.3
3. What version of checkra1n are you using?
beta 0.12.1
4. What is your host system (OS version? Hackintosh? VM? etc.)?
mac os big sur 11.1
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
usb a with adaptor

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**
it went through all the process but at the end it stuck a while in booting logo even though its already booted and finally error code 20.
tried several times. changed the usb c ports, restarted both mac and iphone time various time.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

no
**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
yes

**Any other info, error logs, screenshots, ...?**
screenshot
![IMG_1117](https://user-images.githubusercontent.com/76772540/103342986-c94f7900-4aef-11eb-9ab0-e3c7f406c9a3.jpeg)

**Comment by Siguza** [comment] 2020-12-31 01:36
Duplicate of #1879.

**Closed as completed by Siguza** 2020-12-31 01:36 UTC
Labels: status-duplicate
