### ISSUE TITLE
M1 device hang

### ISSUE THREAD

**Issue by networkextension** [checkra1n/BugTracker#1877] opened 2020-11-29 13:33 UTC
**Tell us about your setup:**
1. What iDevice are you using? M1
2. On what version of iOS is it? 14.0
3. What version of checkra1n are you using? 0.12.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? Apple M1 MacBook Pro
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USA-USB-C Apple Cable

GUI hang, Waiting for DFU devices

**Comment by blimeybloke** [comment] 2020-11-30 17:28
Same issue here too.  I have an older iPhone see running 14.1, tried multiple cables.  Tried 0.12.1.
The cable is the same I used previously as well.  Gets to "Waiting for DFU Devices" and hangs.

**Comment by Siguza** [comment] 2020-12-02 00:32
Duplicate of #1862.

**Closed as completed by Siguza** 2020-12-02 00:32 UTC
Labels: status-duplicate
