### ISSUE TITLE
I have usb error it’s called USBMUX -79 

### ISSUE THREAD

**Issue by Hamdan129** [checkra1n/BugTracker#1721] opened 2020-10-01 09:54 UTC
**Tell us about your setup:**
1. iPad 5th Generation 
2. iOS 14
3. 0.11.0 beta
4. Ubuntu bootable usb 
5. Anker power line iii 

When I jailbreak my iPad the boot screen animation is small sometimes my iPad go to black screen mode 

Story: when I jailbreak my iPad 5th generation iOS 13.7 it works fine but after a week I mistakenly updated to iOS 14 then when I try to jailbreak again it shows me USBMUX error all the time I hope you can fix it thank you 😊

**Comment by Sandwhich253989** [comment] 2020-10-04 07:53
Duplicate of #1689

**Closed as completed** 2020-10-04 19:23 UTC
Labels: status-duplicate
