### ISSUE TITLE
iPad air (iOS 12.4.5) Stuck on right before trigger and DFUSyncUpload Failed: -1

### ISSUE THREAD

**Issue by Moaaga** [checkra1n/BugTracker#891] opened 2020-02-12 22:35 UTC
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using? GUI or CLI?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. 
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by parapenT1sta** [comment] 2020-02-13 09:25
Same issue with iPad Mini 2.

**Comment by abouhafsa** [comment] 2020-02-13 10:06
1- What iDevice are you using?
ipad Air (4.2)
2- On what version of iOS is it?
ios 12.4.5
3- What version of checkra1n are you using? GUI or CLI?
CLI & GUI
4-  is your host system (OS version? Hackintosh? VM? etc.)?
Ubuntu 18.0.4 on windows 10
5- How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Original lightning usb
6- What are the steps to reproduce the issue?
1.
2.
3.
...
Run  ubuntu system
Run the terminal
Paste commands
Download checkra1n jailbreak
Run checkra1n
 right before trigger (this is real bug setup)  issue
7-  do you expect, and what is happening instead?
I expect the jailbreak work normally, but what's happening is the exact opposite.
8-  the issue also occur if you enable Safe Mode?
Yes
9-  other info, error logs, screenshots, ...?
No

**Comment by AMDBartek** [comment] 2020-03-13 18:43
This is a known issue. #984

**Comment by Siguza** [comment] 2020-03-21 05:40
Marking this as duplicate of #984 (this issue is older, but the other one is more generic and thoroughly documented).

**Closed as completed by Siguza** 2020-03-21 05:40 UTC
Labels: status-duplicate
