### ISSUE TITLE
AMD Hackintosh Checkra1n stuck on preparation stage. (Catalina)

### ISSUE THREAD

**Issue by r3dlobst3r** [checkra1n/BugTracker#39] opened 2019-11-10 14:52 UTC
Although hacks may not be supported, I figured I would drop my issue in here. Checkra1n has been stuck at the Checkm8 preparation stage for 20 minutes.

> imac-pro:Applications andrew$ ./checkra1n.app/Contents/MacOS/checkra1n_gui 
- [*] Waiting for DFU devices
- [*] DFU mode device found
- [*] Attempting to perform checkm8 on 8015 11...
- [*] == Checkm8 Preparation stage ==

**Comment by FM1337** [comment] 2019-11-10 14:55
#9 is basically this issue

**Comment by nullpixel** [comment] 2019-11-10 14:58
Closing as a dupe of #9

**Closed as completed by nullpixel** 2019-11-10 14:58 UTC
Labels: status-duplicate
