### ISSUE TITLE
Questions about A7 equipment

### ISSUE THREAD

**Issue by wtgj** [checkra1n/BugTracker#1471] opened 2020-06-12 13:16 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPad Mini 2
2. On what version of iOS is it?
12.4.7
3. What version of checkra1n are you using?
latest
4. What is your host system (OS version? Hackintosh? VM? etc.)?
ubuntu 20.04
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A to Apple lightning
**What are the steps to reproduce the issue?**
1. As long as the device that uses a7 chip, it will be stuck in Right before trigger
2. 
3.
...

**What do you expect, and what is happening instead?**
I have tried the quick-plug USB, but now this method does not work.
This method was also available last week.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yes

**Any other info, error logs, screenshots, ...?**
No

**Comment by wtgj** [comment] 2020-06-12 13:55
Miracles are not without it. Once I waited a long time, I successfully escaped from prison, but I never succeeded again.

**Comment by wtgj** [comment] 2020-06-12 13:58
[#1169](https://github.com/checkra1n/BugTracker/issues/1169) I was able to succeed this method last week, but when I tried again this weekend, I found that nothing could succeed.

**Comment by Siguza** [comment] 2020-06-12 21:09
Gonna mark this as a duplicate of #1169. A7 support is still broken on Linux. :/

**Closed as completed by Siguza** 2020-06-12 21:09 UTC
Labels: status-duplicate
