### ISSUE TITLE
MY IPHONE  DO NOT BOOT UP

### ISSUE THREAD

**Issue by elkinguerrab** [checkra1n/BugTracker#962] opened 2020-02-25 21:43 UTC
**Tell us about your setup:**
1. What iDevice are you using?
Iphone 8
2. On what version of iOS is it?
13.4 beta1
3. What version of checkra1n are you using? GUI or CLI?
0.9.8
4. What is your host system (OS version? Hackintosh? VM? etc.)?
macbook High Sierra
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-a official 
**What are the steps to reproduce the issue?**
1. start
2. booting
3.booting
...

**What do you expect, and what is happening instead?**
my phone do not boot up

**Does the issue also occur if you enable Safe Mode?**
my phone do not boot up

**Any other info, error logs, screenshots, ...?**
No

**Comment by Siguza** [comment] 2020-02-25 23:08
Duplicate of #877.

**Closed as completed by Siguza** 2020-02-25 23:08 UTC
Labels: status-duplicate
