### ISSUE TITLE
Cydia Crashes after Checkra!n install/ ssh timeout

### ISSUE THREAD

**Issue by joethemacc** [checkra1n/BugTracker#648] opened 2019-12-17 21:16 UTC
**Tell us about your setup:**
iPhone 8 Plus
12.4 (16g77)
Checkra1n 0.9.7
Mac OS 10.15.1
usb c to lightening

1. install checkra1n
2. install Lydia
3.open cydia... crashes
4. reinstall Cydia checkra1n crashes
...
put checkra!n and Cydia in folder then it crashed and did a restore from checkera!n 
Tried reinstalling checkrain ..and then Cydia then crashed again
restore from checkrain
reinstalled checkrain.. then Cydia. then put them back in the folder and removed them and then open Lydia and crashed...
restore from checkrain
then
tried to ssh root@ and keep getting a port 22: operation timed out.

tried to install checkrain in safe mode..
then installed cydia
and Cydia crashes 

not sure how to get passed the ssh root issue to try and fix the issue

**Comment by antontech393** [comment] 2019-12-18 00:50
Install termius from the appstore
Set up a host witht the Hostname : localhost 
user:root
Password: alpine
Port 44
ReJailbreak with checkra1n and install cydia
Launch Termius and enter the following command when you access your terminal:

rm /var/mobile/Library/Cydia/metadata.cb0

The command is Case sensitive so enter it properly. Exit termius and launch cydia it should launch properly.

**Comment by adminy** [comment] 2019-12-18 05:49
@antontech393 do you realise that openssh is not installed and port 44 is not open because there is no port proxying ... checkr1in does not make install anything by default... except allowing you to install/re-install cydia

**Comment by antontech393** [comment] 2019-12-18 12:27
I had the same issue and it worked for me

**Comment by dernyn** [comment] 2019-12-19 11:33
after triggering the re-checkra1n jailbreak how can you install/re-install Cydia from SSH or Shell without the touch screen being involved?

**Comment by Siguza** [comment] 2020-02-07 00:35
Duplicate of #60.

**Closed as completed by Siguza** 2020-02-07 00:35 UTC
Labels: status-duplicate
