### ISSUE TITLE
ipads Air2 stuck in booting

### ISSUE THREAD

**Issue by MrAdVa** [checkra1n/BugTracker#1887] opened 2020-12-08 18:55 UTC
using checkra for long to jb several ipad air2 on div. ios Version.

on latest (12.1) version all devices stuck in boot until it runs out of time. usinf 11.0 version works perfect even on newer, not supported iOS Version for that release.

using checkra on MAC Catalina 10.15.7

**Comment by Mentalbass** [comment] 2020-12-09 12:42
> using checkra for long to jb several ipad air2 on div. ios Version.
> 
> on latest (12.1) version all devices stuck in boot until it runs out of time. usinf 11.0 version works perfect even on newer, not supported iOS Version for that release.
> 
> using checkra on MAC Catalina 10.15.7

Did you succeed in jailbreak with another version of checknra1n, another app/program or stuck in this matter?
I have same issue, it times out. Seems the air 2 is stuck on boot.

**Comment by MrAdVa** [comment] 2020-12-09 16:03
11.0 works issue free even on ios 14.1 air2. 
on actual release it remains in boot and getting out of that screen need to "hard" turnoff by pressing pwr+homebutton.
issue same with ios 13.2 ; 13.6; 13.7 and 14.1 like i said above.

**Comment by Mentalbass** [comment] 2020-12-09 19:53
> 11.0 works issue free even on ios 14.1 air2.
> on actual release it remains in boot and getting out of that screen need to "hard" turnoff by pressing pwr+homebutton.
> issue same with ios 13.2 ; 13.6; 13.7 and 14.1 like i said above.

I’ll give checkra1n ver 11 a try. Thanks

**Comment by Mentalbass** [comment] 2020-12-10 07:58
![8ADF79BB-59EE-4284-A0D5-924D144C9E9E](https://user-images.githubusercontent.com/59539707/101737906-c6033780-3ac5-11eb-961f-cf7b76d61414.jpeg)

I tried Checkra1n 11 and it result in not accessing NVRAM and than quits the task

**Comment by karkowg** [comment] 2020-12-14 14:53
> ![8ADF79BB-59EE-4284-A0D5-924D144C9E9E](https://user-images.githubusercontent.com/59539707/101737906-c6033780-3ac5-11eb-961f-cf7b76d61414.jpeg)
> 
> I tried Checkra1n 11 and it result in not accessing NVRAM and than quits the task

Same here.

**Comment by osxest** [comment] 2020-12-14 22:02
Same here. 0.12.1 doesn't work on iPad Air 2 for iOS 14.2.
Log attached.
[log.txt](https://github.com/checkra1n/BugTracker/files/5691838/log.txt)

**Comment by huqfeVmewzy3w** [comment] 2020-12-18 02:40
> using checkra for long to jb several ipad air2 on div. ios Version.
> 
> on latest (12.1) version all devices stuck in boot until it runs out of time. usinf 11.0 version works perfect even on newer, not supported iOS Version for that release.
> 
> using checkra on MAC Catalina 10.15.7

**Comment by Mentalbass** [comment] 2020-12-18 06:22
> using checkra for long to jb several ipad air2 on div. ios Version.
> 
> on latest (12.1) version all devices stuck in boot until it runs out of time. usinf 11.0 version works perfect even on newer, not supported iOS Version for that release.
> 
> using checkra on MAC Catalina 10.15.7

OK, I’ve tried checkra1n 11 on same os Catalina iMac. Where did you got yours? And do you have a link?
Than what could be the problem? What is blocking the jailbreak?

**Comment by Siguza** [comment] 2021-01-02 02:32
Duplicate of #1880.

**Closed as completed by Siguza** 2021-01-02 02:32 UTC
Labels: status-duplicate
