### ISSUE TITLE
iOS 14.2 iPad Air 2

### ISSUE THREAD

**Issue by tizouk17** [checkra1n/BugTracker#1892] opened 2020-12-16 04:08 UTC
**Tell us about your setup:
1. What iDevice are you using? iPad Air 2
2. On what version of iOS is it? 14.2
3. What version of checkra1n are you using? 0.12.1
4. What is your host system (OS version? Hackintosh? VM? etc.)? Mac OS catalina
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple câble usb lightning
**What are the steps to reproduce the issue?**
1. I try checkrain 
2.  Rainusb
3. Linux Checkrain

i dont arrive to jailbreak with checkrain
Someone have a solution ?

**Comment by lopsandrea** [comment] 2020-12-30 14:50
i have the same problem

**Comment by Siguza** [comment] 2021-01-02 02:31
Duplicate of #1880.

**Closed as completed by Siguza** 2021-01-02 02:31 UTC
Labels: status-duplicate
