### ISSUE TITLE
Infinite Right before trigger OR usbmux: Failed to connect (error code: -79) AND DFUSyncUpload FAILED: -1

### ISSUE THREAD

**Issue by suconakh** [checkra1n/BugTracker#795] opened 2020-02-05 23:04 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPad Air Cellular (A7)

2. On what version of iOS is it?
12.4.3

3. What version of checkra1n are you using? GUI or CLI?
0.9.8 both GUI and CLI

4. What is your host system (OS version? Hackintosh? VM? etc.)?
OS - XUbuntu 18.04 via WUBI
CPU - AMD Ryzen 2200g
MoBo - MSI B350M PRO-VD PLUS

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
3rd party MFI USB-A . No USB hubs

**What are the steps to reproduce the issue?**
1. Install checkra1n from repo
2. Run sudo checkra1n
I have a feeling that this is AMD hardware issue. Something related to motherboard's usb, but i might be wrong

**What do you expect, and what is happening instead?**
Obviously expected jailbroken device, but some problems occurred.
First of all i tried to run checkra1n by sudo checkra1n but when it goes to Right before trigger stage, nothing happens. No errors just infinite Right before trigger text. Then i tried it with GUI app but it was the same. If i try to disconnect device while jailbreak is "frozen" in terminal, it shows DFUSyncUpload FAILED: -1. However in GUI app freezes and i can't close it.

Then i tried this workaround:
```
sudo chmod +x checkra1n
sudo checkra1n -c -v
```
and also
```
sudo checkra1n -c -v -V -s 
```
(i've also tried to enable all options in GUI and terminal, but nothing worked)

Now there's something different. When im connecting my device, it shows this:
```
<Warning>: connection refused?!
<Error>: usbmux: Failed to connect (error code: -79)
```
Then jailbreaking process begins and again it fails on Right before trigger stage, but now it does not "freeze" as it was in terminal and GUI app and device exits DFU mode when there's "<Verbose>: Checkmate!" line in the terminal. More on screenshot down below

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
[Screenshot](https://i.imgur.com/jYaJvZi.png)

**Comment by AMDBartek** [comment] 2020-03-13 18:35
This is a known issue. #984

**Comment by Siguza** [comment] 2020-03-21 05:38
Marking this as duplicate of #984 (this issue is older, but the other one is more generic and thoroughly documented).

**Closed as completed by Siguza** 2020-03-21 05:38 UTC
Labels: status-duplicate
