### ISSUE TITLE
iPad Air iOS 12.4.7 won't work via macOS checkra1n

### ISSUE THREAD

**Issue by ghost** [checkra1n/BugTracker#1490] opened 2020-06-17 16:56 UTC
1. iPad Air 
2. 12.4.7
3. 0.10.2
4. macOS 10.15.5
5. A through a hub to my macbook pro

**What are the steps to reproduce the issue?**
1. checkra1n fails to run, either fails at first (usually happens here, heap spray) or second step (right before trigger)

**What do you expect, and what is happening instead?**
I do not get the freeze thing that people have fixed using the unplug method

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Yup

**Comment by tryfontheo** [comment] 2020-06-17 21:14
I posted this, seems to be very similar to #1488

**Comment by Siguza** [comment] 2020-06-21 07:18
Feel like this is a dupe of #1447.

**Closed as completed by Siguza** 2020-06-21 07:18 UTC
Labels: status-duplicate

**Comment by tryfontheo** [comment] 2020-06-21 16:48
> Feel like this is a dupe of #1447.

Still not working
![Screen Shot 2020-06-21 at 12 46 50 PM](https://user-images.githubusercontent.com/23111073/85230359-73ba4700-b3bd-11ea-944d-40537cb01f1c.png)

**Comment by tryfontheo** [comment] 2020-06-21 16:51
![Screen Shot 2020-06-21 at 12 51 34 PM](https://user-images.githubusercontent.com/23111073/85230417-f6db9d00-b3bd-11ea-8974-a37b5632c8f4.png)
