### ISSUE TITLE
iPad Mini 2 Raspberry Pi 4 USB error -77 no passcode

### ISSUE THREAD

**Issue by ibrahimk157** [checkra1n/BugTracker#1377] opened 2020-05-21 14:42 UTC
**Tell us about your setup:**
1. What iDevice are you using?

iPad Mini 2 (Cellular)

2. On what version of iOS is it?

12.4.7

3. What version of checkra1n are you using?

0.10.1 arm

4. What is your host system (OS version? Hackintosh? VM? etc.)?

Raspbian buster lite on a raspberry pi 4B (4GB RAM)

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

USB A Apple lightening cable... tried three different ones
**What are the steps to reproduce the issue?**
1. Connect the iPad mini 2 to the raspberry pi
2. Run checkra1n and follow the instructions 
3. You’ll either get “Failed to get string descriptor: LIBUSB_ERROR_TIMEOUT 0” during the dfu instructions. Or you’ll get into dfu mode successfully but instantly get a usb error -77 when it tries to run (again, no passcode!) along with the same “Failed to get string descriptor: LIBUSB_ERROR_TIMEOUT 0” error

**What do you expect, and what is happening instead?**

I expect it to smoothly proceed with the jailbreak. But the above happens instead.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
 
Yup, it still does.

**Any other info, error logs, screenshots, ...?**

USB error -77

Failed to get string descriptor: LIBUSB_ERROR_TIMEOUT 0

**Comment by Siguza** [comment] 2020-05-22 05:50
Duplicate of #1169.  
Basically A7 is broken on Linux. :/

**Closed as completed by Siguza** 2020-05-22 05:50 UTC
Labels: status-duplicate

**Comment by ibrahimk157** [comment] 2020-05-22 10:45
> Duplicate of #1169.
> Basically A7 is broken on Linux. :/

Oh wow didn’t come across that. Apologies, it’s insanely hard to go through each one of the issues here.

**Comment by Siguza** [comment] 2020-05-23 22:36
Yeah I know, no worries.
