### ISSUE TITLE
Cannot Open Dmg

### ISSUE THREAD

**Issue by B3NT03** [checkra1n/BugTracker#163] opened 2019-11-11 07:50 UTC
**What device + iOS version are you on?**
MacBook Retina Early 2015 (OS X 10.10.5
iphone 8 iOS 13.2
**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1.opening the dmg file.
2.
3.
...

**What do you expect, and what is happening instead?**
being able to open it and install checkra1n

**Any other info, error logs, screenshots, ...?**
![7A3E2850-617B-4333-B79A-32700035C338](https://user-images.githubusercontent.com/57615865/68570285-26342f80-0415-11ea-9a64-0984494452b8.jpeg)

**Comment by nullpixel** [comment] 2019-11-11 07:52
Closed as a dupe of #28

**Closed as completed by nullpixel** 2019-11-11 07:52 UTC
Labels: status-duplicate
