### ISSUE TITLE
Error -20 iPad air 2 iOS 14.4

### ISSUE THREAD

**Issue by lei33** [checkra1n/BugTracker#2023] opened 2021-03-05 05:51 UTC
**Tell us about your setup:**
1. What iDevice are you using? iPad air 2 (wifi)
2. On what version of iOS is it? 14.4
3. What version of checkra1n are you using? 0.12.2
4. What is your host system (OS version? Hackintosh? VM? etc.)? MacOS Big Sur 11.0.1, MBP (early 2015)
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB-A Apple

**What are the steps to reproduce the issue?**
1. iPad freshly restored from finder, lauched Checkra1n, went into DFU mode, booting then got Error code: -20
2. Tried with Safe mode option, same result
3.
...

**What do you expect, and what is happening instead?**
Wishing to get Jailbroken again ! Cannot jailbreak my device anymore.

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
No popup on the device I cannot enter Safe mode, only the Checkra1n app saying : Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
Same

**Any other info, error logs, screenshots, ...?**
Nope

**Comment by archiVanGraf** [comment] 2021-03-07 22:08
The same problem as well, tried 20 times but can not jailbreak Ipad Air 2 WiFi model 14.4 iOs

**Comment by lei33** [comment] 2021-03-10 18:24
I wonder if this is related to checkra1n on Mac and if it does also apply to Ra1nbox for exemple ?

**Comment by archiVanGraf** [comment] 2021-03-11 02:53
I tried on Mac, windows, ra1nusb and no success. Its a common jailbreak problem. I checked with 14.4.1 update and 14.5 (beta) - no success (bootstrap, 20 error). Ipad Air 2 LTE - successful jailbreak with 14.5 (beta)

**Comment by lei33** [comment] 2021-03-11 05:17
Tyvm for the info !

**Comment by Groh12** [comment] 2021-03-13 15:17
Model MGGX2FD/a ipad air 2 cellurar easy jailbroken, but model MH312 LL/A ipad air 2 cellurar not jailbroken ( booting and stop (

**Comment by lei33** [comment] 2021-03-13 15:18
> Model MGGX2FD/a ipad air 2 cellurar easy jailbroken, but model MH312 LL/A ipad air 2 cellurar not jailbroken ( booting and stop (

Hopefully Checkra1n team will get that fixed !

**Comment by Groh12** [comment] 2021-03-13 15:22
I tried last checkn1x, checkra1n 11.0 patched, Checkra1nRG, official 12.0, 12.1, 12.2 on macbook pro 2018, 2019, hackintosh catalina, Mojave ((( booting and stop too.

**Comment by lei33** [comment] 2021-03-13 15:49
> I tried last checkn1x, checkra1n 11.0 patched, Checkra1nRG, official 12.0, 12.1, 12.2 on macbook pro 2018, 2019, hackintosh catalina, Mojave ((( booting and stop too.

Tyvm for the info 👍🏼

**Comment by lei33** [comment] 2021-03-14 11:57
> I tried last checkn1x, checkra1n 11.0 patched, Checkra1nRG, official 12.0, 12.1, 12.2 on macbook pro 2018, 2019, hackintosh catalina, Mojave ((( booting and stop too.

Do you think with a Ra1nbox it would make any difference ?

**Comment by Groh12** [comment] 2021-03-14 16:27
> Do you think with a Ra1nbox it would make any difference ?
No. Wait new checkra1n or patched checkra1n specially for ipad air 2 and ipad mini 4.

**Comment by lei33** [comment] 2021-03-14 20:31
> > Do you think with a Ra1nbox it would make any difference ?
> 
> No. Wait new checkra1n or patched checkra1n specially for ipad air 2 and ipad mini 4. 
> 
> 

No idea, I thought it was due to a bad tweak blocking ota update since I cannot open general and update, gonna get a Ra1nbox this week, needed since my new M1 Mac won't be able to run Checkra1n... gonna try and tell you.

**Comment by lei33** [comment] 2021-03-15 13:33
> > Do you think with a Ra1nbox it would make any difference ?
> 
> No. Wait new checkra1n or patched checkra1n specially for ipad air 2 and ipad mini 4. 
> 
> 

Tyvm for your answer sir !

**Comment by Groh12** [comment] 2021-03-15 18:00
> No idea, I thought it was due to a bad tweak blocking ota update since I cannot open general and update, gonna get a Ra1nbox this week, needed since my new M1 Mac won't be able to run Checkra1n... gonna try and tell you.

My ipad on Hello screen. I want jailbreak for bypass.

**Comment by moabbikr** [comment] 2021-03-16 01:18
If you look thru the issues this pops up several times, very common issue that has gone unfixed for a very long time. I wouldn't get your hopes up..

**Comment by Siguza** [comment] 2021-04-30 02:02
Duplicate of #1880.

**Closed as completed by Siguza** 2021-04-30 02:02 UTC
Labels: status-duplicate
