### ISSUE TITLE
nvram: Error setting variable - 'com.apple.System.boot-nonce': (iokit/common) general error

### ISSUE THREAD

**Issue by 0neday** [checkra1n/BugTracker#278] opened 2019-11-13 12:15 UTC
**What device + iOS version are you on?**
ios 12.4.1

**What checkra1n version are you using?**

0.9.2
**What are the steps to reproduce the issue?**
1.nvram: Error setting variable - 'com.apple.System.boot-nonce': (iokit/common) general error
2.
3.
...

**What do you expect, and what is happening instead?**

noncesetter or patch nonce

**Any other info, error logs, screenshots, ...?**

**Comment by littlelailo** [comment] 2019-11-13 12:19
nvram doesn't get unlocked atm. We will prob add a patch in a newer version.

**Comment by nullpixel** [comment] 2019-12-01 15:06
Closed as a dupe of #181

**Closed as completed by nullpixel** 2019-12-01 15:06 UTC
Labels: status-duplicate
