### ISSUE TITLE
iPad Mini 2 error -20 and -31

### ISSUE THREAD

**Issue by petsrdjan** [checkra1n/BugTracker#1092] opened 2020-03-25 23:33 UTC
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using? GUI or CLI?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. iPad Mini 2 wifi
2. 12.4.6
3. 0.9.8.2
4. Catalina
5. USB-A Apple
...

**What do you expect, and what is happening instead?**
I have tried repeatedly and in most cases throw a -20 error. Even if he does manage to finish somehow, when it starts up I can't use the home button or click on any icon. No icon is visible in the dock. 

**Does the issue also occur if you enable Safe Mode?**
Yes

**Any other info, error logs, screenshots, ...?**
Error -20 and -31

**Comment by macross1412** [comment] 2020-03-26 00:49
You can use checkra1n 0.9.7 or beta 0.10
Success for my iPad Mini 2 (Cellular) 16GB on 12.4.6

**Comment by petsrdjan** [comment] 2020-03-26 01:24
> You can use checkra1n 0.9.7 or beta 0.10
> Success for my iPad Mini 2 (Cellular) 16GB on 12.4.6

Did your home button work? I can't even click on the icons. 

With 12.4.3 I managed, however auto update remained on, and after update I hawe this problem. I also used checkm8 for iCloud Bypass.

**Comment by macross1412** [comment] 2020-03-26 02:51
Home button work fine
You can try DFU 12.4.6 For ipad
But I guess problem you used iCloud Bypass

**Comment by Siguza** [comment] 2020-03-26 03:19
Sounds like a duplicate of #984.

**Closed as completed by Siguza** 2020-03-26 03:19 UTC
Labels: status-duplicate
