### ISSUE TITLE
Latest checkra1n version stuck at booting

### ISSUE THREAD

**Issue by likkai** [checkra1n/BugTracker#2070] opened 2021-04-30 09:12 UTC
Tell us about your setup:

What iDevice are you using?
iPad pro 12.9-inch 1st Gen

On what version of iOS is it?
14.5

What version of checkra1n are you using?
Latest (0.12.3)

What is your host system
Ubuntu 20.04 on a usb

How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB A official cables

What are the steps to reproduce the issue?

Plug the iPad on iOS 14.5
Continue the process until it stuck at Booting

What do you expect, and what is happening instead?
Finish the process as usual but stuck indefinitely

Did you see a popup on the device stating it entered "Safe Mode" due to an error?
No

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?
Yes

Any other info, error logs, screenshots, ...?
It shows ‘Detected corrupted kerninfo’. Removing password, enter safe mode doesn’t work

**Comment by iiiii2000** [comment] 2021-04-30 11:01
The same happened with my device: Ipad Pro 9.7 1st generation using latest version of Checkra1n.

**Comment by mystrain** [comment] 2021-04-30 18:11
same is happening to me with my iPad pro 1st gen.

however checkra1n gives me error 20

**Comment by likkai** [comment] 2021-05-01 06:29
Update: Even downgrading to iOS 14.4.2 doesn't work with the latest checkra1n (0.12.3) 
This is what it showed up
![20210501_142537](https://user-images.githubusercontent.com/76016664/116797612-05383080-ab1a-11eb-9854-4c6a15bb3eea.jpg)

**Comment by mystrain** [comment] 2021-05-01 16:40
i really hope checkra1n addresses this.

this has happened before and with iOS 14.3 however it took a while to fix.

now its happening again with the A9X chipped devices or that's what im thinking as its happening on my pad pro 1st gen

**Comment by Siguza** [comment] 2021-05-01 23:53
Duplicate of #2074.

**Closed as completed by Siguza** 2021-05-01 23:53 UTC
Labels: status-duplicate
