### ISSUE TITLE
Factory reset does not fully remove the JB

### ISSUE THREAD

**Issue by Luber905** [checkra1n/BugTracker#211] opened 2019-11-11 21:19 UTC
**What device + iOS version are you on?**
13.2.2

**What checkra1n version are you using?**
0.9.1b
**What are the steps to reproduce the issue?**
1.jailbreak as per instructions, works fine. 
2.factory reset to remove jailbreak. 
3.apps (Rogers Ignite TV) still recognize the phone as JB. Cydia still appears on home screen but does not open. 
...

**What do you expect, and what is happening instead?**
Expected the factory reset to remove all vestiges of the JB

**Any other info, error logs, screenshots, ...?**
![01AE6CC5-8DBF-4094-9E53-56D1D59B4DBA](https://user-images.githubusercontent.com/57642908/68621950-fb8eb900-049e-11ea-9144-e0b71f0d2e0a.jpeg)
Screenshot from Ignite TV after factory reset.

**Comment by mehmeteminkartal** [comment] 2019-11-11 22:45
In order to remove the jailbreak completely you need to restore it using your computer.

**Comment by Luber905** [comment] 2019-11-11 22:49
Thanks I accomplished it by restoring to a previous iCloud backup. 

Gotta say restoring to a current backup did not remove Cydia icon or the JB warning from Ignite TV app. Restoring to previous backup did it.

**Comment by nullpixel** [comment] 2019-11-11 23:08
To fully remove it you have to restore rootfs and erase all contents and settings in Settings. Closing as a dupe of #62

**Closed as completed by nullpixel** 2019-11-11 23:08 UTC
Labels: status-duplicate

**Comment by Shadowedstalker** [comment] 2019-11-12 20:37
Liberty Lite stops detection

**Comment by Luber905** [comment] 2019-11-12 20:49
Yes! Except my issue was after attempting to remove jailbreak. No JB, no Liberty Lite. But my factory-reset and restored phone still had files that made it look JB to my app. Solved by restoring to an older (pre-JB) iCloud backup.
