### ISSUE TITLE
Checkra1n task getting blocked

### ISSUE THREAD

**Issue by Cucklord420** [checkra1n/BugTracker#970] opened 2020-02-26 23:44 UTC
**Tell us about your setup:**
1.IPad mini 3 WiFi Edition
2. 12.4.5
3.GUI
4. Bootra1n
5.USBa to lightning both first party and third party adapters

**What are the steps to reproduce the issue?**
1. Boot up
2. Trust computer
3.sudo checkra1n
4.DFU mode
5.task blocked
...

**What do you expect, and what is happening instead?**
iPad to get jailbroken
Instead I get INFO: task checkra1n:1188 blocked for more than 122 seconds

**Does the issue also occur if you enable Safe Mode?** yes

**Any other info, error logs, screenshots, ...?**
![image](https://user-images.githubusercontent.com/48045150/75398539-f592db80-58c7-11ea-9bb2-f1943557a213.jpg)

**Comment by Nico239SF** [comment] 2020-02-27 15:08
I have the same problem with the same device...

**Comment by Siguza** [comment] 2020-03-23 05:19
Sounds like the generic A7 issue. Marking as dupe of #984.

**Closed as completed by Siguza** 2020-03-23 05:19 UTC
Labels: status-duplicate
