### ISSUE TITLE
SO SAD

### ISSUE THREAD

**Issue by adamdwisusanto** [checkra1n/BugTracker#1286] opened 2020-04-28 20:05 UTC
I just made a mistake just now I installed MakeRespringGreatAgain and RespringProgress tweaks and after that my respring was looping forever, so I decided to force restart my device.  

And seen on my HomeScreen there is no CheckRa1n app anymore and still leaving the Cydia, I can't open Cydia even when I try to re-jailbreak with BootRa1n again, the status on my PC is "All Done" without error, but the display on my device was still stuck on Apple boot with lots of text from Checkra1n. 

Is there a way to remove the last tweak that I installed or maybe a way to totally reset my Cydia, via BootRa1n? can someone please help me😔

**Comment by Siguza** [comment] 2020-04-28 23:24
Tick the "Safe Mode" checkbox in checkra1n options.

**Comment by adamdwisusanto** [comment] 2020-04-29 04:34
Thank you very much I’m successfully using your method. And now a new problem pop up that every time I open any tweaks from Cydia, my device immediately force close. I've tried to restore Cydia also deleting and adding repos but the results are the same.  Do you know to fix this?

**Comment by nergzd723** [comment] 2020-04-30 12:32
You should remove Cydia metadata at /var/mobile/library/cydia/metadata.cb0

**Comment by Siguza** [comment] 2020-05-03 04:34
Gonna mark this as a dupe of either #60 or #804 then.

**Closed as completed by Siguza** 2020-05-03 04:34 UTC
Labels: status-duplicate
