### ISSUE TITLE
iOS 12.4.6 iPad mini2 stuck at Right before the trigger

### ISSUE THREAD

**Issue by iM4CH3T3** [checkra1n/BugTracker#1207] opened 2020-04-13 06:50 UTC

**Comment by iM4CH3T3** [comment] 2020-04-13 06:53
Running Ubuntu machine 18.04
iOS 12.4.6
iPad mini 2
Latest checkra1n 
Dell e6410

**Comment by iM4CH3T3** [comment] 2020-04-13 07:35
Worked after a fresh restore on iOS 12.4.4

**Comment by chienerp** [comment] 2020-04-13 08:06
It worked for version 0.10.0  Dear Linux user you guys have to borrow a Macbook from someone or have to wait for new version lmao

**Comment by iM4CH3T3** [comment] 2020-04-13 08:31
Yeah downgraded to 12.4.4 till the update comes ...

**Comment by nergzd723** [comment] 2020-04-13 09:25
nope, see #1169 for a workaround

**Comment by iM4CH3T3** [comment] 2020-04-13 10:01
It actually only Jailbreaks my iPad mini 2 when fresh restored...
Was successful on 12.4.6 but after a fresh restore... 3 times I was able to Jailbreak after fresh restore.
When once rebooted it doesn’t work no more ... it gets stuck at right before the trigger...
Even unplug and plug in again has no effect after rebooted once...
Strange huh ?

**Comment by iM4CH3T3** [comment] 2020-04-13 10:46
> nope, see #1169 for a workaround

Thx

**Comment by iM4CH3T3** [comment] 2020-04-13 11:10
Oh could rejailbreak after reboot after few tries with the unplug method...
The first time actually I didn’t needed to restore....

**Comment by Siguza** [comment] 2020-04-13 12:41
Marking as dupe of #1169.

**Closed as completed by Siguza** 2020-04-13 12:41 UTC
Labels: status-duplicate
