### ISSUE TITLE
Powerloghelperd and accountsd crashing

### ISSUE THREAD

**Issue by ahanank** [checkra1n/BugTracker#353] opened 2019-11-14 19:48 UTC
I believe the latest version of checkra1n makes these daemons constantly crash, spiking up CPU usage, and therefore, causing insane battery drops and the phone heating up. On an iPhone X using iOS 13.2. I have tried disabling all of the tweaks I currently use with no luck.

**Comment by nullpixel** [comment] 2019-11-15 16:39
dupe of #343

**Closed as completed by nullpixel** 2019-11-15 16:39 UTC
Labels: status-duplicate
