### ISSUE TITLE
Ipad Mini 2

### ISSUE THREAD

**Issue by pimposama** [checkra1n/BugTracker#1026] opened 2020-03-09 20:11 UTC
**Tell us about your setup:**
1. What iDevice are you using?
**Ipad Mini 2 and checkra1n on my macbook air 11**
2. On what version of iOS is it?
**12.4.4**
3. What version of checkra1n are you using? GUI or CLI?
**Version beta 0.9.8, tried 0.9.2 before that, was also unsuccessful**
4. What is your host system (OS version? Hackintosh? VM? etc.)?
**macOS Mojave, 10.14.16**
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? 
**Apple original cable, tried a usual USB-C, no difference, through a normal port on macbook air  **

**What are the steps to reproduce the issue?**
1. Recovering mode success (tried to put into recovery myself, without the app, didn't help)
2. DFU mode success (tried holding for longer, no changes) 
3. Error Report (Error Code -31) and also 20 
Right after that the device starts booting (see screenshots), usually stops at booting 
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**
Yes, I tried all variations: safe mode alone, safe mode with verbose boot, and untested option. When all together were on it once showed a cydia icon on the app after the mistake warning and everything, but then it disappeared

**Any other info, error logs, screenshots, ...?**
Please, find screenshots 
![Screenshot 2020-03-09 at 21 09 17](https://user-images.githubusercontent.com/48772331/76253107-54ead700-624a-11ea-8743-8953f0e0bf8d.png)
![Screenshot 2020-03-09 at 21 09 05](https://user-images.githubusercontent.com/48772331/76253110-55836d80-624a-11ea-9172-ba3c202840ea.png)
![Screenshot 2020-03-09 at 21 08 42](https://user-images.githubusercontent.com/48772331/76253111-561c0400-624a-11ea-80e7-cfca076b7296.png)
![Screenshot 2020-03-09 at 21 03 59](https://user-images.githubusercontent.com/48772331/76253113-56b49a80-624a-11ea-8965-eec5e863c965.png)

attached

**Comment by ja1lbreaker** [comment] 2020-03-18 22:15
This seems to be a common issue with ios 12. I am getting these two errors too. On an iPhone 5s with ios 12.4

**Comment by Siguza** [comment] 2020-03-21 05:59
I _feel_ like this is a duplicate of #984, but the fact that 0.9.2 didn't work for you strikes me as odd. Have you tried 0.9.6?  
We should have a release with a fix for A7 in the next few days. I'm gonna mark this issue as a duplicate for now, if it turns out not to be, just comment here and I'll reopen it.

**Closed as completed by Siguza** 2020-03-21 05:59 UTC
Labels: status-duplicate
