### ISSUE TITLE
No PUBKEY on Linux

### ISSUE THREAD

**Issue by barl3y** [checkra1n/BugTracker#2246] opened 2022-01-25 19:41 UTC
Hey there,
I'm on Ubuntu 20.04 and whenever adding the checkra1n repo i get an NO PUBKEY error.
I precisely followed the 4 steps in the instructions and also tried some steps to get the keys from reddit etc. but as far as I read it, it should be provided within the steps.

Not a linux pro so if I just did a rookie mistake forgive me.

Thanks
barl3y

LOG from the terminal: 

barley@Barleys-IdeaPad:~$ sudo wget -O /usr/share/keyrings/checkra1n.gpg https://assets.checkra.in/debian/archive.key
[sudo] password for barley: 
--2022-01-25 20:34:28--  https://assets.checkra.in/debian/archive.key
Resolving assets.checkra.in (assets.checkra.in)... 190.2.133.122
Connecting to assets.checkra.in (assets.checkra.in)|190.2.133.122|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1684 (1,6K) [application/octet-stream]
Saving to: ‘/usr/share/keyrings/checkra1n.gpg’

/usr/share/keyrings 100%[===================>]   1,64K  --.-KB/s    in 0s      

2022-01-25 20:34:28 (141 MB/s) - ‘/usr/share/keyrings/checkra1n.gpg’ saved [1684/1684]

barley@Barleys-IdeaPad $ echo 'deb [signed-by=/usr/share/keyrings/checkra1n.gpg] https://assets.checkra.in/debian /' | sudo tee /etc/apt/sources.list.d/checkra1n.list
deb [signed-by=/usr/share/keyrings/checkra1n.gpg] https://assets.checkra.in/debian /
barley@Barleys-IdeaPad:$ 
barley@Barleys-IdeaPad:$ sudo apt-get update
Hit:1 http://de.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu focal-updates InRelease              
Hit:3 https://dl.winehq.org/wine-builds/ubuntu focal InRelease                 
Get:4 https://assets.checkra.in/debian  InRelease [2.170 B]                    
Hit:5 http://de.archive.ubuntu.com/ubuntu focal-backports InRelease            
Hit:6 http://security.ubuntu.com/ubuntu focal-security InRelease               
Err:4 https://assets.checkra.in/debian  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7F9943C7A5217279
Reading package lists... Done
W: GPG error: https://assets.checkra.in/debian  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7F9943C7A5217279
E: The repository 'https://assets.checkra.in/debian  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Scottyboy808** [comment] 2022-01-30 21:33
Im having the same issue. ;-----

tps://assets.checkra.in/debian/archive.key.gpg htt
--2022-01-30 21:09:11--  https://assets.checkra.in/debian/archive.key
Resolving assets.checkra.in (assets.checkra.in)... 190.2.133.122
Connecting to assets.checkra.in (assets.checkra.in)|190.2.133.122|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1684 (1.6K) [application/octet-stream]
Saving to: ‘/usr/share/keyrings/checkra1n.gpg’

/usr/share/keyrings 100%[===================>]   1.64K  --.-KB/s    in 0s      

2022-01-30 21:09:12 (90.7 MB/s) - ‘/usr/share/keyrings/checkra1n.gpg’ saved [1684/1684]

scott@scott-Virtual-Machine:~$ echo 'deb [signed-by=/usr/share/keyrings/checkra1n.gpg] https://assets.checkra.in/debian /' | sudo tee /etc/apt/sources.list.d/checkra1n.list
deb [signed-by=/usr/share/keyrings/checkra1n.gpg] https://assets.checkra.in/debian /
scott@scott-Virtual-Machine:~$ 
scott@scott-Virtual-Machine:~$ sudo apt-get update
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                        
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]      
Get:4 https://assets.checkra.in/debian  InRelease [2,170 B]                    
**Err:4 https://assets.checkra.in/debian  InRelease                      
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7F9943C7A5217279**
Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Reading package lists... Done                                 
W: GPG error: https://assets.checkra.in/debian  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7F9943C7A5217279
E: The repository 'https://assets.checkra.in/debian  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
scott@scott-Virtual-Machine:~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7F9943C7A5217279
Executing: /tmp/apt-key-gpghome.QSSdsr9LBA/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 7F9943C7A5217279
gpg: key 7F9943C7A5217279: "checkra1n team (checkra1n Signing Key) <buildbot@checkra.in>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
scott@scott-Virtual-Machine:~$ apt-get update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
scott@scott-Virtual-Machine:~$ sudo apt-get update
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                        
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]      
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]    
Get:5 https://assets.checkra.in/debian  InRelease [2,170 B]                    
Get:6 http://security.ubuntu.com/ubuntu bionic-security/main amd64 DEP-11 Metadata [55.0 kB]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 DEP-11 Metadata [59.3 kB]
Err:5 https://assets.checkra.in/debian  InRelease                     
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7F9943C7A5217279
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 DEP-11 Metadata [297 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 DEP-11 Metadata [2,464 B]
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 DEP-11 Metadata [301 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 DEP-11 Metadata [2,468 B]
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 DEP-11 Metadata [9,272 B]
Reading package lists... Done                 
W: GPG error: https://assets.checkra.in/debian  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7F9943C7A5217279
E: The repository 'https://assets.checkra.in/debian  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
scott@scott-Virtual-Machine:~$ sudo wget -O /usr/share/keyrings/checkra1n.gpg https://assets.checkra.in/debian/archive.key
--2022-01-30 21:16:14--  https://assets.checkra.in/debian/archive.key
Resolving assets.checkra.in (assets.checkra.in)... 190.2.133.122
Connecting to assets.checkra.in (assets.checkra.in)|190.2.133.122|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1684 (1.6K) [application/octet-stream]
Saving to: ‘/usr/share/keyrings/checkra1n.gpg’

/usr/share/keyrings 100%[===================>]   1.64K  --.-KB/s    in 0s      

2022-01-30 21:16:14 (240 MB/s) - ‘/usr/share/keyrings/checkra1n.gpg’ saved [1684/1684]

scott@scott-Virtual-Machine:~$ echo 'deb [signed-by=/usr/share/keyrings/checkra1n.gpg] https://assets.checkra.in/debian /' | sudo tee /etc/apt/sources.list.d/checkra1n.list
deb [signed-by=/usr/share/keyrings/checkra1n.gpg] https://assets.checkra.in/debian /
scott@scott-Virtual-Machine:~$ sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                
Get:3 https://assets.checkra.in/debian  InRelease [2,170 B]                    
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Err:3 https://assets.checkra.in/debian  InRelease                        
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7F9943C7A5217279
Hit:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done                      
W: GPG error: https://assets.checkra.in/debian  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7F9943C7A5217279
E: The repository 'https://assets.checkra.in/debian  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
scott@scott-Virtual-Machine:~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7F9943C7A5217279
Executing: /tmp/apt-key-gpghome.zdmqVKEaxH/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 7F9943C7A5217279
gpg: key 7F9943C7A5217279: "checkra1n team (checkra1n Signing Key) <buildbot@checkra.in>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
scott@scott-Virtual-Machine:~$ sudo apt-get install checkra1n
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package checkra1n
scott@scott-Virtual-Machine:~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7F9943C7A5217279
Executing: /tmp/apt-key-gpghome.Y2Cj3lqLuM/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 7F9943C7A5217279
gpg: key 7F9943C7A5217279: "checkra1n team (checkra1n Signing Key) <buildbot@checkra.in>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
scott@scott-Virtual-Machine:~$ sudo apt-get install checkra1n
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package checkra1n
scott@scott-Virtual-Machine:~$ sudo apt-get update
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                        
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease              
Get:5 https://assets.checkra.in/debian  InRelease [2,170 B]                    
Err:5 https://assets.checkra.in/debian  InRelease                             
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7F9943C7A5217279
Reading package lists... Done
W: GPG error: https://assets.checkra.in/debian  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7F9943C7A5217279
E: The repository 'https://assets.checkra.in/debian  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
scott@scott-Virtual-Machine:~$ 

Any idea what the issue is  ?

**Comment by second2falcon** [comment] 2022-01-31 13:47
@Scottyboy808 I think apt-get doesn't allow you  to install it since the repository that checkra1n is coming from isn't signed. I have tried to bypass that, but was unsuccessful.

**Comment by Nadabyah** [comment] 2022-01-31 14:11
Any such fix yet for Ubuntu 20.10?

**Comment by second2falcon** [comment] 2022-01-31 19:27
> Any such fix yet for Ubuntu 20.10?

You could try forcing it with apt-get update --allowinsecurerepositories (not sure if the -- flag comes before or after update. But as said, I was unsuccessful with it. I realized like 2 hours later that I have a macmini sitting in the closet. Booger that thing up and it worked perfectly.

**Comment by Siguza** [comment] 2022-02-02 16:37
Sorry for the issue, everyone. The repo key was in the wrong format. You should be able to fix it with this:

    wget -O - https://assets.checkra.in/debian/archive.key | gpg --dearmor | sudo tee /usr/share/keyrings/checkra1n.gpg >/dev/null

Updated the instruction page as well, so this shouldn't happen anymore.

Closing this in the hope that it's resolved. If not, just ping me again.

**Closed as completed by Siguza** 2022-02-02 16:37 UTC
Labels: status-fixed
