### ISSUE TITLE
Checkra1n stopped working on iOS 13.4

### ISSUE THREAD

**Issue by Kimiblock** [checkra1n/BugTracker#990] opened 2020-03-03 15:03 UTC
**Tell us about your setup:**
1. What iDevice are you using?iPhone 7
2. On what version of iOS is it?iOS13.4
3. What version of checkra1n are you using? CLI
4. What is your host system (OS version? Hackintosh? VM? etc.)? Linux 
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? USB A

**What are the steps to reproduce the issue?**
1. Run Checkra1n
2. 
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**

**Comment by Stux-Sec** [comment] 2020-03-07 18:53
I know checkra1n doesn’t support beta builds of iOS but hopefully it’ll be fixed when official 13.4 comes out.

**Comment by Siguza** [comment] 2020-03-23 01:15
Duplicate of #877.

**Closed as completed by Siguza** 2020-03-23 01:15 UTC
Labels: status-duplicate
