### ISSUE TITLE
iPhone X Global 14.4.2 tried both 0.12.2 & 0.12.3 Crashes when adding a passcode- But iPad Pro 1st gen 14.4 OK- OS 10.13.6 USB A

### ISSUE THREAD

**Issue by Sa1rain** [checkra1n/BugTracker#2079] opened 2021-05-02 09:23 UTC
iPhone X Global 14.4.2 tried both 0.12.2 & 0.12.3 Crashes when adding a passcode- But iPad Pro 1st gen 14.4 OK-  USB A Direct in MacBook Pro OS 10.13.6

You all are awesome, keep up the great work! It's a lot to take on!

**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**
no

**Comment by DrJapan** [comment] 2021-05-02 10:00
If you jailbroke using the bypass A11 BPR check, I'm pretty sure you can't use those features.

**Comment by DrJapan** [comment] 2021-05-02 10:01
Passcode or FaceID won't work.

**Comment by Sa1rain** [comment] 2021-05-02 10:25
Unless something changed with this release, from what I know you have to jailbreak with A11 BPR check with an iPhone X. And yes, I did figure out passcode and face id don't work, which is what brought me to here. I've always been able to use passcode and face id before 14.4.2, so it not the BPR check. I'm just giving info so when they create a new version, more info the better. I have 8 simple common tweaks I've been using for a long time and none have to do with security to interfere.

Just to let commenters know, I'm not looking for answers. This is something they will have to work out eventually in a later release.

Thanks!

**Comment by Siguza** [comment] 2021-05-02 11:46
> I've always been able to use passcode and face id before 14.4.2

I believe this when I see it.  
A11 has not been able to use a passcode since iOS 14.0 beta 1.

So this is a duplicate of #2026 and won't be fixed until we have a new SEP bug.

**Closed as completed by Siguza** 2021-05-02 11:46 UTC
Labels: status-duplicate
