### ISSUE TITLE
checkra1n beta 0.10.2 safe mode option not working on untested iOS

### ISSUE THREAD

**Issue by PJ09github** [checkra1n/BugTracker#1665] opened 2020-09-12 09:39 UTC
The safe mode option toggle doesn't work/trigger safe mode on untested iOS (13.7).

Right now the only way to enter in safe mode after a reboot is holding volume up while running the tool.

Tested on 6S, 7 Plus, X and iPad Pro

**Comment by Siguza** [comment] 2020-09-13 18:07
Duplicate of #1613.

**Closed as completed by Siguza** 2020-09-13 18:07 UTC
Labels: status-duplicate
