### ISSUE TITLE
Loader App not showing 

### ISSUE THREAD

**Issue by angelobdev** [checkra1n/BugTracker#1821] opened 2020-11-09 21:49 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPhone X (GSM) 10,6 64GB
2. On what version of iOS is it?
iOS 14.1
3. What version of checkra1n are you using?
0.12.0
4. What is your host system (OS version? Hackintosh? VM? etc.)?
macOS BigSur 11.0.1 Beta
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
Apple USB-A to Lightning cable.

**What are the steps to reproduce the issue?**
1. Connect iPhone to the Mac so checkra1n detects it.
2. Start the procedure.
3. Having the issue of not founding the Loader App on the screen.

**What do you expect, and what is happening instead?**
Founding the loader app, but even tho I wait some time it doesn't appear... 😕

Hoping you will fix this soon. I can't wait for the new JB!

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by Siguza** [comment] 2020-11-16 06:58
Duplicate of #1810.

**Closed as completed by Siguza** 2020-11-16 06:58 UTC
Labels: status-duplicate
