### ISSUE TITLE
Error code -5

### ISSUE THREAD

**Issue by mamadufrance** [checkra1n/BugTracker#1328] opened 2020-05-10 23:02 UTC
**Tell us about your setup:**
1. What iDevice are you using? iPad Air 2
2. On what version of iOS is it? 13.4.1
3. What version of checkra1n are you using? 0.10.1 beta
4. What is your host system (OS version? Hackintosh? VM? etc.)? OS X 10.8.5
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? Original MFi lighting USB-A

**What are the steps to reproduce the issue?**
1. After my iPad comes to DFU mode the jailbreak installation stops.
2. Shows USB ERROR (error code -5)
3.
...

**What do you expect, and what is happening instead?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**
![F2A1B4EE-0422-4966-B565-363C452020BC](https://user-images.githubusercontent.com/65137974/81512654-d9310780-932a-11ea-9f9c-34e1a7837bbd.jpeg)

**Comment by Siguza** [comment] 2020-05-16 01:54
Duplicate of #1168.

**Closed as completed by Siguza** 2020-05-16 01:54 UTC
Labels: status-duplicate
