### ISSUE TITLE
iPhone 5s gets stuck at Right Before Trigger

### ISSUE THREAD

**Issue by 7voxels221** [checkra1n/BugTracker#1410] opened 2020-05-28 17:16 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 5s
2. On what version of iOS is it?
12.4.5
3. What version of checkra1n are you using?
0.10.2
4. What is your host system (OS version? Hackintosh? VM? etc.)?
Arch Linux
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
3rd party cable

**What are the steps to reproduce the issue?**
1. Literally just start the jailbreak. It has never worked for me.
2. 
3.
...

**What do you expect, and what is happening instead?**
I expect a working jailbreak, but it gets stuck at Right Before Trigger.

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
No.

**Any other info, error logs, screenshots, ...?**
![Screenshot_20200528_131540](https://user-images.githubusercontent.com/58532328/83172288-5f986800-a0e5-11ea-85c0-d32bb3382434.png)

**Comment by demhademha** [comment] 2020-05-29 20:37
Some devices have an option called “legacy usb support” 
Check for it

**Comment by Siguza** [comment] 2020-05-30 13:54
Duplicate of #1169.

**Closed as completed by Siguza** 2020-05-30 13:54 UTC
Labels: status-duplicate

**Comment by YamiYukiSenpai** [comment] 2020-09-26 22:28
> Some devices have an option called “legacy usb support”
> Check for it

How do you enable that?
