### ISSUE TITLE
-

### ISSUE THREAD

**Issue by cuj** [checkra1n/BugTracker#1893] opened 2020-12-16 08:17 UTC
>

**Comment by crystall1nedev** [comment] 2021-01-01 20:19
pongoOS is open-source now, I saw that on Reddit.

**Comment by Siguza** [comment] 2021-01-01 23:35
Yes it will be, once we have a working Windows release. Sorry that we didn't quite hit the 2020 mark that we planned for.

Marking this as dupe of #566.

**Closed as completed by Siguza** 2021-01-01 23:35 UTC
Labels: status-duplicate
