### ISSUE TITLE
什么时候可以在M1芯片的MacBook Ari上运行？

### ISSUE THREAD

**Issue by Fangyouchun** [checkra1n/BugTracker#2058] opened 2021-04-19 09:42 UTC
**Tell us about your setup:**
1. What iDevice are you using?
2. On what version of iOS is it?
3. What version of checkra1n are you using?
4. What is your host system (OS version? Hackintosh? VM? etc.)?
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?

**What are the steps to reproduce the issue?**
1. MacBook ari
2. 11
3.0.12.2
4.MacOS
5.USB-A
**What do you expect, and what is happening instead?**

希望可以在M1芯片的Mac上打开并运行，谢谢！
**Did you see a popup on the device stating it entered "Safe Mode" due to an error?**

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**

**Any other info, error logs, screenshots, ...?**

**Comment by Un1Gfn** [comment] 2021-04-20 18:14
Possible duplicate of #1862

**Comment by asdfugil** [comment] 2021-04-21 05:02
Translation:
> When can I run this on a M1 Macbook Air?

**Closed as completed** 2021-04-30 01:22 UTC
Labels: status-duplicate

**Comment by wengxianxun** [comment] 2022-02-22 02:02
最新款m1pro芯片的macbook pro上越狱失败
