### ISSUE TITLE
Checkra1n 0.11.0 - iOS 14 - NO support for iPad Pro 1st Gen. (2016)

### ISSUE THREAD

**Issue by wasif9241** [checkra1n/BugTracker#1709] opened 2020-09-27 16:09 UTC
**Tell us about your setup:**
**_1. What iDevice are you using?_** 
iPad Pro 1st Gen. 9.7" (2016)
iPad6,4 (A1674)

**_2. On what version of iOS is it?_**
iOS 14.0

**_3. What version of checkra1n are you using?_**
Checkra1n version 0.11.0

**_4. What is your host system (OS version? Hackintosh? VM? etc.)?_**
I've tried these systems: 1. Hackintosh (OS Catalina) 2. MacOS High Sierra on Mac Mini

**_5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?_**
USB-A / 3rd party cable 
But i've used same cable with iPad Air 2 and it worked fine.

_Does the issue also occur if you tick "Safe Mode" in the checkra1n options?_
Yes I've also tried with safe mode, and other options but didn't worked.

_Any other info, error logs, screenshots, ...?_
So I tried to jailbreak my iPad Pro 9.7 2016 with checkra1n 0.11.0 and everything was going flawlessly and then my ipad goes to boot screen and comes to apple logo and then turns on but checkra1n windows stays stuck on booting..... screen and after a while en error comes which i have shown in photo.
Error-20: Timed out waiting for bootstrap upload (Likely caused by an incompatible tweak, to enable Safe Mode check the option on main screen) (Error code: -20)

Remember same version i've tried on ipad air 2  with ios 14 and it worked flawlessly so it is definitely problem with iPad Pro i think there is no support for it.

Please kindly check and solve the problem.
Thanks
![WhatsApp Image 2020-09-27 at 3 33 43 PM](https://user-images.githubusercontent.com/17291732/94369852-1a606300-00e4-11eb-8975-44171d9ac033.jpeg)

**Comment by Siguza** [comment] 2020-09-27 20:51
Duplicate of #1692.

**Closed as completed by Siguza** 2020-09-27 20:51 UTC
Labels: status-duplicate
