### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by AdrianD80** [checkra1n/BugTracker#957] opened 2020-02-24 18:34 UTC
**Tell us about your setup:**
1. What iDevice are you using?
iPhone 6S 16GB
2. On what version of iOS is it?
13.3.1
3. What version of checkra1n are you using? GUI or CLI?
GUI
4. What is your host system (OS version? Hackintosh? VM? etc.)?
MAC 10.11.6
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)? 
USB A 3rd party

**What are the steps to reproduce the issue?**
1. Happens Randomly with heavy use of phone. Watching video or using safari (happened twice while trying to submit this report, now using a PC)
2. Phone still works but no access to screen at all
3. Does come back eventually, not sure when however. I usually hard reset and then rejailbreak. As of right now I have had it on for a few hours and its fine however sometimes after re-jailbreaking it happens after 5 mins. 
...

**What do you expect, and what is happening instead?**
Screen goes black no access to anything. NFC still works as well SIRI. 

**Does the issue also occur if you enable Safe Mode?**
Not sure haven't tried. 

**Any other info, error logs, screenshots, ...?**
No

**Comment by ann0see** [comment] 2020-02-24 20:38
Does it also happen if you are unjailbroken?

If this is the case maybe it’s a hardware issue.

**Comment by AdrianD80** [comment] 2020-02-24 20:42
It does not happen when not jailbroken.

**Comment by ann0see** [comment] 2020-02-24 21:52
Ok. So it’s probably a tweak. Try to disable tweak by tweak via iCleaner Pro. Maybe you can find it through this method.

**Comment by AdrianD80** [comment] 2020-02-25 11:24
Sweet thanks for the helps. I think i found the culprit, appears to be smart tap x. Which is too bad cause I love that tweak lol

**Comment by ann0see** [comment] 2020-02-25 12:45
> Sweet thanks for the helps. I think i found the culprit, appears to be smart tap x. Which is too bad cause I love that tweak lol


You could try to message the developer. Maybe he can fix the problem.

**Comment by Siguza** [comment] 2020-02-25 23:39
Glad you find the root cause, but gonna close this as invalid since it's not a checkra1n issue.

**Closed as completed by Siguza** 2020-02-25 23:39 UTC
Labels: status-invalid
