### ISSUE TITLE
Crashes installing Cydia on iPad Pro2

### ISSUE THREAD

**Issue by cnassaney** [checkra1n/BugTracker#26] opened 2019-11-10 14:18 UTC
iPad Pro 2nd Gen ios 13.2.2

**What are the steps to reproduce the issue?**
1. Launch checkra1n
2. Install cydia
3. crash
...

**What do you expect, and what is happening instead?**

**Any other info, error logs, screenshots, ...?**

**Comment by woachk** [comment] 2019-11-10 14:19
Duplicate of #2.

**Closed as completed by woachk** 2019-11-10 14:19 UTC
Labels: status-duplicate
