### ISSUE TITLE
iPad Pro 10.5 fails installing bootstrap

### ISSUE THREAD

**Issue by clarityzzz** [checkra1n/BugTracker#4] opened 2019-11-10 13:37 UTC
**What device + iOS version are you on?**
iPad Pro 10.5'' 13.1.3

**What are the steps to reproduce the issue?**
1. Run checkra1n
2. Fully boot, open checkra1n app
3. Wait for internet connection, press Cydia inside the app and the app crashes right away.

**What do you expect, and what is happening instead?**
Bootstrap to be installed and Cydia to appear on the home screen.

**Any other info, error logs, screenshots, ...?**

https://pastebin.com/xbaCXDFb

**Comment by nullpixel** [comment] 2019-11-10 13:49
Hi, I've closed this issue as a duplicate of #2.

**Closed as completed by nullpixel** 2019-11-10 13:49 UTC
Labels: status-duplicate
